### PR TITLE
RES: Resolve stdlib items in detached files

### LINKED ISSUE #9422: No autocompletion of stdlib items in detached files
## Environment

IntelliJ Rust plugin version: 0.4.179.4903-222
Rust toolchain version: rustup 1.25.1 (bb60b1e89 2022-07-12)
IDE name and version: Clion 2022.2
Operating system: MacOS 12.6

## Problem description
- String:: not give auto completion

image

- Not support std module auto import
image

## Steps to reproduce

The code is easy to find. They are exercises in project rustlings, file string1.rs and module3.rs . Click [string1.rs](https://github.com/rust-lang/rustlings/blob/main/exercises/strings/strings1.rs) and [module3.rs](https://github.com/rust-lang/rustlings/blob/main/exercises/modules/modules3.rs) to check

### PR DESCRIPTION
**Pull request by dima74**
Fixes #9422
Partial solution for #8853
Note that `containingCrate` of detached files is still null, so inspections will not work (and thus auto-import)

changelog: Now items from stdlib are resolved in detached and scratch files

### CODE REVIEW

File: src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt [hunk 1]
```diff
@@ -381,7 +382,7 @@ class ImplLookup(
             .filter { useImplsFromCrate(it.containingCrates) }
 
     private fun useImplsFromCrate(crates: List<Crate>): Boolean =
-        containingCrate == null || crates.any { containingCrate.hasTransitiveDependencyOrSelf(it) }
+        containingCrate is FakeCrate || crates.any { containingCrate.hasTransitiveDependencyOrSelf(it) }
```
Comment (vlad20012) [inline src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt:385]: I think now we can remove `containingCrate is FakeCrate` part

File: src/main/kotlin/org/rust/lang/core/psi/RsFile.kt [hunk 2]
```diff
@@ -165,9 +169,14 @@ class RsFile(
         // This occurs if the file is not included to the project's module structure, i.e. it's
         // most parent module is not mentioned in the `Cargo.toml` as a crate root of some target
         // (usually lib.rs or main.rs). It's anyway useful to know cargoProject&workspace in this case
-        val cargoProject = project.cargoProjects.findProjectForFile(virtualFile) ?: return EMPTY_CACHED_DATA
-        val workspace = cargoProject.workspace ?: return CachedData(cargoProject)
-        return CachedData(cargoProject, workspace)
+        val stdlibCrates = project.crateGraph.topSortedCrates
+            .filter { it.origin == PackageOrigin.STDLIB }
```
Comment (vlad20012) [inline src/main/kotlin/org/rust/lang/core/psi/RsFile.kt:173]: Since stdlib crates are always first in the top sorted list, we can write it this way:
```suggestion
            .takeWhile { it.origin == PackageOrigin.STDLIB }
```

**Review by vlad20012 — APPROVED** [review]

**Comment by dima74** [comment]
bors r=vlad20012

**Comment by dima74** [comment]
bors r=vlad20012

File: src/main/kotlin/org/rust/lang/core/psi/RsFile.kt (hunk 2 above)
Comment (dima74) [reply src/main/kotlin/org/rust/lang/core/psi/RsFile.kt]: There are also `STDLIB_DEPENDENCY` so can't use `takeWhile`

**Comment by dima74** [comment]
bors r=vlad20012

File: src/main/kotlin/org/rust/lang/core/psi/RsFile.kt (hunk 2 above)
Comment (vlad20012) [reply src/main/kotlin/org/rust/lang/core/psi/RsFile.kt:179]: Then it could be `.takeWhile { it.origin == PackageOrigin.STDLIB || it.origin == PackageOrigin.STDLIB_DEPENDENCY }` :D
