### PR TITLE
Support "Create field" quick-fix for struct literals with `Self`

### LINKED ISSUE #9651: Struct initialization with Self keyword does not invoke "Create field" option
## Environment

* **IntelliJ Rust plugin version:** 0.4.183.4980-223-nightly
* **Rust toolchain version:** 1.64.0 (a55dd71d5 2022-09-19) x86_64-apple-darwin
* **IDE name and version:** CLion 2022.3 EAP (CL-223.7255.15)
* **Operating system:** macOS 12.5.1
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.macros.proc.function-like, org.rust.macros.proc

Originally posted in https://youtrack.jetbrains.com/issue/CPP-30924/Rust-Struct-initialization-with-Self-keyword-does-not-invoke-Create-field-option 

## Problem description
When you attempt to initialize a struct with the Self keyword, CLion does not offer the Create field option as it does when you explicitly use the struct's own name.

## Steps to reproduce
```rust
struct A { }
impl A {
    fn new() -> A {
        let x = 0;
        A {
            x // <- invokes "Create field" option
        }
    }
    
    fn new2() -> A {
        let x = 0;
        Self {
            x // <- does not invoke "Create field" option
        }
    }
}

```

### PR DESCRIPTION
**Pull request by dima74**
Fixes #9651

changelog: Support `Create field` quick-fix for struct literals with `Self`

### CODE REVIEW

File: src/main/kotlin/org/rust/ide/annotator/fixes/CreateStructFieldFromConstructorFix.kt [hunk 1]
```diff
@@ -63,15 +63,19 @@ class CreateStructFieldFromConstructorFix private constructor(
             val fieldName = field.identifier?.text ?: return null
             val fieldType = field.type
             if (!canUse(fieldType)) return null
-            val struct = field.resolveToStructItem() ?: return null
+            val struct = field.parentStructLiteral.path.resolveToStructItem() ?: return null
```
Comment (vlad20012) [inline src/main/kotlin/org/rust/ide/annotator/fixes/CreateStructFieldFromConstructorFix.kt:66]:
```suggestion
            val struct = field.parentStructLiteral.path.deepResolve() ?: return null
```

File: src/main/kotlin/org/rust/ide/annotator/fixes/CreateStructFieldFromConstructorFix.kt [hunk 2]
```diff
@@ -63,15 +63,19 @@ class CreateStructFieldFromConstructorFix private constructor(
...
         }
 
-        private fun RsStructLiteralField.resolveToStructItem(): RsStructItem? {
-            return parentStructLiteral.path.reference?.resolve() as? RsStructItem
+        private fun RsPath.resolveToStructItem(): RsStructItem? {
+            return when (val result = reference?.resolve()) {
+                is RsStructItem -> result
+                is RsImplItem -> (result.typeReference as? RsPathType)?.path?.reference?.resolve() as? RsStructItem
+                else -> null
+            }
```
Comment (vlad20012) [inline src/main/kotlin/org/rust/ide/annotator/fixes/CreateStructFieldFromConstructorFix.kt:78]:
```suggestion
```

**Review by vlad20012 — APPROVED** [review]

**Comment by dima74** [comment]
bors r=vlad20012
