### PR TITLE
REPL: Fix macro completion inside Rust Console

### LINKED ISSUE #4752: No macro completion inside Rust Console
## Environment

* **IntelliJ Rust plugin version:** 0.2.113.2810-193-nightly
* **Rust toolchain version:** 1.41.0-nightly (710a362dc 2019-12-05) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2019.3 Ultimate Edition (IU-193.5233.102)
* **Operating system:** macOS 10.13.6

## Problem description
Completion inside Rust Console doesn't suggest macros from stdlib like `println!`

### PR DESCRIPTION
**Pull request by dima74**
Fix #4752

### CODE REVIEW

File: src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt [hunk 1]
```diff
@@ -207,7 +208,14 @@ inline fun <reified T : PsiElement> PsiElement.descendantsWithMacrosOfType(): Co
  * Same as [PsiElement.getContainingFile], but return a "fake" file. See [org.rust.lang.core.macros.RsExpandedElement].
  */
 val PsiElement.contextualFile: PsiFile
-    get() = contextOrSelf() ?: error("Element outside of file: $text")
+    get() {
+        val file = contextOrSelf<PsiFile>() ?: error("Element outside of file: $text")
+        return if (file is RsReplCodeFragment) {
```
Comment (vlad20012) [inline src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt]: Btw looks like this should be applied to any types of code fragments
