### PR TITLE
COMP: Don't complete built-in attributes for qualified path

### LINKED ISSUE #10058: Don't suggest builtin attributes during completion non-first segment in attribute path
## Environment

* **IntelliJ Rust plugin version:** 0.4.188.5171-223-nightly
* **Rust toolchain version:** 1.66.0 (69f9c33d7 2022-12-12) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2022.3.1 Ultimate Edition (IU-223.8214.52)
* **Operating system:** macOS 12.5.1
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.macros.proc.attr, org.rust.cargo.emulate.terminal

## Problem description
The plugin suggested builtin attributes after `::` in an attribute path

Screenshot 2023-01-30 at 12 11 58

## Steps to reproduce
`main.rs`
```rust
#[tokio::t]
fn test() {
    
}
```

`Cargo.toml`
```toml
[package]
name = "rust-project"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version="1.24.2", features=["full"] }
```

### PR DESCRIPTION
**Pull request by dima74**
Fixes #10058

changelog: Don't complete built-in attributes for qualified path

### CODE REVIEW

File: src/main/kotlin/org/rust/lang/core/completion/RsAttributeCompletionProvider.kt [hunk 1]
```diff
@@ -82,10 +83,12 @@ object RsAttributeCompletionProvider : RsCompletionProvider() {
...
 
     override val elementPattern: ElementPattern<PsiElement>
-        get() {
-            return psiElement(RsElementTypes.IDENTIFIER)
-                .withParent(psiElement<RsPath>().withParent(rootMetaItem))
-        }
+        get() = psiElement(RsElementTypes.IDENTIFIER)
+            .withParent(
+                psiElement<RsPath>()
+                    .with("Unqualified") { it: RsPath -> it.path == null }
```
Comment (vlad20012) [inline src/main/kotlin/org/rust/lang/core/completion/RsAttributeCompletionProvider.kt:89]: Let's also cover `::foo` case
```suggestion
                    .with("Unqualified") { it: RsPath -> it.coloncolon == null }
```

File: src/test/kotlin/org/rust/lang/core/completion/RsAttributeCompletionTest.kt [hunk 2]
```diff
@@ -272,6 +272,11 @@ class RsAttributeCompletionTest : RsAttributeCompletionTestBase() {
         fn foo() {}
     """)
 
+    fun `test no builtin attr completion for qualified path`() = checkNoCompletion("""
+        #[tokio::mai/*caret*/]
```
Comment (vlad20012) [inline src/test/kotlin/org/rust/lang/core/completion/RsAttributeCompletionTest.kt:276]: It seems that `main` attribute is outdated and we should remove it from completion. So let's better test the `test` attribute

**Review by vlad20012 — APPROVED** [review]

**Comment by dima74** [comment]
bors r=vlad20012
