### PR TITLE
TY: fix `todo!()` macro type inference

### LINKED ISSUE #9355: todo! and early return causes the whole match to be marked as unreachable
## Environment

* **IntelliJ Rust plugin version:** 0.4.178.4873-222
* **Rust toolchain version:** 1.65.0-nightly (1d37ed661 2022-09-09) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2022.2.1 (CL-222.3739.54)
* **Operating system:** Windows 11 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.macros.proc

## Problem description
Using todo! macro and an early return inside of match arms causes the whole match expression to be marked as unreachable:
obraz

## Steps to reproduce
```rs
fn foo(a: u32) -> u32 {
    match a {
        42 => todo!(),
        _ => return 123,
    }
}
```

### PR DESCRIPTION
**Pull request by vlad20012**
Fixes #9355

changelog: Fix `todo!()` macro type inference

### CODE REVIEW

File: src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt [hunk 1]
```diff
@@ -1333,7 +1333,7 @@ class RsTypeInferenceWalker(
             name == "format_args" -> items.Arguments.asTy()
             name == "unimplemented" || name == "unreachable" || name == "panic" -> TyNever
             name == "write" || name == "writeln" -> inferredTy
-            else -> TyUnknown
+            else -> inferredTy
```
Comment (ortem) [inline src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt:1336]: I am wondering if there are other such macros besides `todo!`. Do you know how we can check that we covered them all? 🤔

**Review by ortem — CHANGES_REQUESTED** [review]
Let's also add a corresponding test case to `RsUnreachableCodeInspectionTest` to ensure there is no false-positive warning reported in #9355

File: src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt (hunk 1 above)
Comment (vlad20012) [reply src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt:1336]: The same bug could apply to other format-like macros ("format", "format_args", "format_args_nl", "write", "writeln", "print", "println", "eprint", "eprintln", "panic", "unimplemented", "unreachable", "todo"), but in this PR a fix the general case, so all of them should be covered. And I have no idea about other possible bugs like this

**Review by ortem — APPROVED** [review]
LGTM
bors r+
