### PR TITLE
ANN: add "Create field" quick fix for "No such field" error

### LINKED ISSUE #2363: Inspections to create fields on initialize
For example:
```rust
struct S {}
impl S {
    fn new(foo: String) -> S {
        S {
            foo/*caret*/
        }
    }
}
```
after

```rust
struct S {
    foo: String
}
impl S {
    fn new(foo: String) -> S {
        S {
            foo
        }
    }
}
```

### PR DESCRIPTION
**Pull request by t-kameyama**
Fixes #2363.

demo

### CODE REVIEW

File: src/main/kotlin/org/rust/ide/annotator/fixes/CreateStructFieldFromConstructorFix.kt [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+                if (struct.identifier == null) return null
+            }
+            return CreateStructFieldFromConstructorFix(field)
+        }
+
+        private fun RsStructLiteralField.structItem(): RsStructItem? {
+            return parentStructLiteral.path.reference.resolve() as? RsStructItem
+        }
+
+        private fun RsStructLiteralField.nameAndType(): Pair<String, RsTypeReference>? {
```
Comment (mchernyavsky) [inline src/main/kotlin/org/rust/ide/annotator/fixes/CreateStructFieldFromConstructorFix.kt]: I think we should use `Ty` instead of `RsTypeReference`. This will help us support a more complex case, like this:

```rust
fn foo((x, y): (i32, i32)) {
    S { x }
}
```
You can simply get the field's type:

```rust
private fun RsStructLiteralField.inferFieldTy(): Ty {
    val type = if (colon == null) resolveToBinding()?.type else expr?.type
    return type ?: TyUnknown
}
```

And then check if we can use it in the context of struct item:

```rust
fun canUse(ty: Ty): Boolean {
    val result = ty.visitWith(object : TypeVisitor {
        override fun visitTy(ty: Ty): Boolean = when (ty) {
            is TyUnknown, is TyTypeParameter, is TyAnon, is TyInfer, is TyProjection -> true
            else -> ty.superVisitWith(this)
        }

        override fun visitRegion(region: Region): Boolean = region !is ReStatic
    })
    return !result
}
```

This function returns `false` in these cases:

```rust
struct St {}
trait Tr {}

fn foo<T>(x: T, t: impl Tr, z: &str) {
    St { x, y, z }
}
```

p.s. You can use `insertionSafeTextWithLifetimes` in `createBlockFields` to render `Ty`.

**Comment by mchernyavsky** [comment]
@t-kameyama could you please squash your commits?
