### PR TITLE
TY: Coerce container type while index expr type inference

### LINKED ISSUE #1748: type inference doesn't work through array indexes on references to Vecs.
'm' has an unknown type in the following example:
```rust
fn foo() -> u32 {
    let r: Vec<u32> = Vec::new();
    let p = &r;
    let m = p[0];
    m
}
```

### PR DESCRIPTION
**Pull request by Undin**
Fixes #1748

### CODE REVIEW

File: src/test/kotlin/org/rust/lang/core/type/RsIndexTypeInferenceTest.kt [hunk 1]
```diff
@@ -129,4 +129,61 @@ class RsIndexTypeInferenceTest : RsTypificationTestBase() {
...
+        pub trait Deref {
+            type Target: ?Sized;
+            fn deref(&self) -> &Self::Target;
+        }
+
+        #[lang = "index"]
+        pub trait Index<Idx: ?Sized> {
+            type Output: ?Sized;
+            fn index(&self, index: Idx) -> &Self::Output;
+        }
```
Comment (matklad) [inline src/test/kotlin/org/rust/lang/core/type/RsIndexTypeInferenceTest.kt]: Let's do the same trick here as for `org.rust.lang.core.resolve.RsClosuresResolveTest` to avoid repeating index impl every time?

File: src/test/kotlin/org/rust/lang/core/type/RsIndexTypeInferenceTest.kt [hunk 2]
```diff
@@ -129,4 +129,61 @@ class RsIndexTypeInferenceTest : RsTypificationTestBase() {
...
+
+        fn foo(v: Vec<u32>) -> u32 {
+            let p = &v;
+            let m = p[0];
+            m
+          //^ u32
+        }
+    """)
+
+    fun testTransitiveCoercion() = testExpr("""
```
Comment (matklad) [inline src/test/kotlin/org/rust/lang/core/type/RsIndexTypeInferenceTest.kt]: Let's use `test transitive coercion`'like names for new tests?

File: src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt [hunk 3]
```diff
@@ -163,7 +163,7 @@ class ImplLookup(private val project: Project, private val items: StdKnownItems)
         return subst + associated
     }
 
-    fun derefSequence(baseTy: Ty): Sequence<Ty> {
+    fun coercionSequence(baseTy: Ty): Sequence<Ty> {
```
Comment (matklad) [inline src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt]: Is this intended to include real coercions in the future? For the current implementation, `deref` makes more sense to me as a name...

Comment (Undin) [reply src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt]: This method already does coercion because it converts `TyArray` to `TySlice`.
But if you consider the previous name is better I'll revert renaming - I don't insist:)

Comment (matklad) [reply src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt]: Let's make it `coercion` then, @vlad20012 could change it later if he disagrees :)

**Comment by Undin** [comment]
Fixed comments

**Comment by matklad** [comment]
bors r+

Thanks!
