### PR TITLE
INSP: Make the "Convert to assert_(eq|ne)!" fixes not kick in for non-Debug types

### LINKED ISSUE #2539: assert!(a == b) wrongly correct to assert_eq!(a, b) where T: !Debug
Code such as
```rust
#[derive(PartialEq, Eq)] // Note: NOT Debug
struct X(u32);

fn a() {
    assert!(X(0) == X(0));
}
```

will trigger a suggestion to convert the assertion to `assert_eq!(X(0), X(0))`. This is incorrect because X isn't Debug, and `assert_eq!` requires this.

### PR DESCRIPTION
**Pull request by JakubAdamWieczorek**
Fixes #2539.

### CODE REVIEW

**Comment by Undin** [comment]
bors r+
Thanks!

File: src/test/kotlin/org/rust/ide/inspections/RsAssertEqualInspectionTest.kt [hunk 1]
```diff
@@ -82,19 +82,50 @@ class RsAssertEqualInspectionTest : RsInspectionsTestBase(RsAssertEqualInspectio
...
         }
-    """)
+    """, checkWeakWarn = true)
 
     fun `test simple assert_ne fix with format_args`() = checkFixByText("Convert to assert_ne!", """
         fn main() {
             let x = 10;
             let y = 10;
-            <weak_warning descr="assert!(a == b) can be assert_eq!(a, b)">assert!(x != y, "format {}", 0<caret>)</weak_warning>;
+            <weak_warning descr="assert!(a != b) can be assert_ne!(a, b)">assert!(x != y, "format {}", 0<caret>)</weak_warning>;
```
Comment (Undin) [inline src/test/kotlin/org/rust/ide/inspections/RsAssertEqualInspectionTest.kt]: 👍
