### PR TITLE
COMP: move caret insice '()' after method completion in UFCS

### LINKED ISSUE #4248: Wrong caret navigation while method completion in UFCS
## Environment

* **IntelliJ Rust plugin version:** 0.2.103.2707-192-nightly
* **Rust toolchain version:** 1.38.0-nightly (d3f8a0b5d 2019-08-04) x86_64-apple-darwin
* **IDE name and version:** IU-192.5728.98
* **Operating system:** macOS 10.13.6

## Problem description
After method completion in UFCS form the plugin navigates caret after `()`. But In UFCS you need pass `&self` parameter explicitly, so caret should be navigated inside `()`

## Steps to reproduce
```rust
struct Foo;

impl Bar for Foo {
    fn assoc() -> Self { Foo }
    fn bar(&self) {}
}
pub trait Bar {
    fn assoc() -> Self;
    fn bar(&self);
}

fn main() {
    Bar::ba/*caret*/
}

```

### PR DESCRIPTION
**Pull request by t-kameyama**
Fixes #4248

### CODE REVIEW

File: src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt [hunk 1]
```diff
@@ -810,4 +810,37 @@ class RsCompletionTest : RsCompletionTestBase() {
...
+            fn bar(&self) {}
+        }
+        pub trait Bar {
+            fn assoc() -> Self;
+            fn bar(&self);
+        }
+        
+        fn main() {
+            Bar::ba/*caret*/
+        }
```
Comment (Undin) [inline src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt]: Test code example can be shrunk to
```rust
struct Foo;
impl Foo {
    fn foo(&self) {}
}

fn main() {
    Foo::foo()
}
```

**Comment by Undin** [comment]
@t-kameyama Looks ok
Could your squash your commits please?

**Comment by Undin** [comment]
bors retry
