### PR TITLE
COMP: Fix raw identifier in `use` cannot be complete

### LINKED ISSUE #9031: Completion `use ..r#fnname` with raw identifier adds inapplicable`()`
## Environment

* **IntelliJ Rust plugin version:** 0.4.175.4733-221-nightly
* **Rust toolchain version:** 1.64.0-nightly (7b46aa594 2022-07-05) x86_64-apple-darwin
* **IDE name and version:** CLion 2022.1.3 (CL-221.5921.27)
* **Operating system:** macOS 11.4
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description

https://user-images.githubusercontent.com/49211026/178102167-2a795e86-13cd-4db5-a6d3-80795e34c1c0.mov

## Steps to reproduce
in kva.rs:
```rust
pub mod mymod {
    pub fn r#break(){
        println!("hello")
    }
}
```
in main.rs:
```rust
mod kva;
use kva::mymod::r#break(); 
```

### PR DESCRIPTION
**Pull request by Stzx**
Fixes #9031

```rust
use self::foo::break
```

The original content of the above error caused the PSI element to escape from `USE_ITEM`

changelog: Fix raw identifier in `use declarations` not complete

### CODE REVIEW

File: src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt [hunk 1]
```diff
@@ -259,19 +259,20 @@ open class RsDefaultInsertHandler : InsertHandler<LookupElement> {
         context: InsertionContext,
         item: LookupElement
     ) {
-        val document = context.document
-        val startOffset = context.startOffset
-        val curUseItem = context.getElementOfType<RsUseItem>()
+        val document= context.document
```
Comment (dima74) [inline src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt:262]:
```suggestion
        val document = context.document
```

File: src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt [hunk 2]
```diff
@@ -1354,4 +1354,27 @@ class RsCompletionTest : RsCompletionTestBase() {
...
+        }
+
+        fn main() {
+            use self::foo::r#break;/*caret*/
+
+            r#break();
+        }
+    """)
 }
+
```
Comment (dima74) [inline src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt:1380]: Please remove this newline

File: src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt [hunk 3]
```diff
@@ -259,19 +259,20 @@ open class RsDefaultInsertHandler : InsertHandler<LookupElement> {
...
+
         if (element is RsNameIdentifierOwner && !RsNamesValidator.isIdentifier(scopeName) && scopeName !in CAN_NOT_BE_ESCAPED) {
-            document.insertString(startOffset, RS_RAW_PREFIX)
+            document.insertString(context.startOffset, RS_RAW_PREFIX)
+            context.commitDocument() // Fixed PSI element escape
```
Comment (dima74) [inline src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt:266]: I don't see problems with such approach
@vlad20012 could you please also review it

**Review by dima74 — APPROVED** [review]

**Review by vlad20012 — APPROVED** [review]
LGTM

bors r=dima74
