### PR TITLE
INT: don't show "remove unnecessary parens" for struct literals in for-loop iterator

### LINKED ISSUE #3039: Bad diagnostics on struct literal in for-loop iterator expression
## Environment

* **Intellij-Rust plugin version:** 0.2.0.2471-182-nightly
* **Rust toolchain version:** rustc 1.32.0-nightly (8b096314a 2018-11-02)
* **IDE name and version (and Windows version, helpfully provided by the "About" dialog):**
IntelliJ IDEA 2018.2.2 (Ultimate Edition)
Build #IU-182.4129.33, built on August 21, 2018
Licensed to Austin Bonander
Subscription is active until May 11, 2019
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

## Problem description

Rust as of 1.32 Nightly (and probably for a long time before) requires parenthesis around struct
literals when used in the iterator expression of a `for` loop:

```rust
struct SomeIter {
    foo: ()
}

impl Iterator for SomeIter { /* irrelevant */ }

fn main() {
    // error: expected expression, found struct
    for val in SomeIter { foo: () } {}
}
```

IntelliJ-Rust fails to resolve the reference to `SomeIter` in this form:
image

The compiler helpfully suggests wrapping it in parenthesis, but then IntelliJ-Rust displays a false lint warning about them:
image
(this form compiles successfully without lint warnings from the compiler)

### PR DESCRIPTION
**Pull request by t-kameyama**
Fixes #3039

### CODE REVIEW

File: src/main/kotlin/org/rust/ide/intentions/RemoveParenthesesFromExprIntention.kt [hunk 1]
```diff
@@ -16,7 +16,9 @@ class RemoveParenthesesFromExprIntention : RsElementBaseIntentionAction<RsParenE
     override fun getFamilyName(): String = text
 
     fun isAvailable(expr: RsParenExpr?): Boolean {
-        if (expr?.ancestorStrict<RsCondition>() == null && expr?.ancestorStrict<RsMatchExpr>() == null) return true
+        if (expr?.ancestorStrict<RsCondition>() == null &&
+            expr?.ancestorStrict<RsMatchExpr>() == null &&
+            expr?.ancestorStrict<RsForExpr>() == null) return true
```
Comment (vlad20012) [inline src/main/kotlin/org/rust/ide/intentions/RemoveParenthesesFromExprIntention.kt]: Consider use
```
PsiTreeUtil.getContextOfType(
        expr,
        false,
        RsCondition::class.java,
        RsMatchExpr::class.java,
        RsForExpr::class.java
    )
```
to avoid multiple tree traverse

**Comment by vlad20012** [comment]
:+1: Just squash commits :)
