### PR TITLE
MACRO: support `:pat_param` `macro_rules!` matcher, fix `:pat` matcher

### LINKED ISSUE #7372: Pattern in `matches!` and `assert_matches!` isn't semantically highlighted
## Environment

* **IntelliJ Rust plugin version:** 0.4.150.3935-211-nightly
* **Rust toolchain version:** 1.55.0-nightly (ce1d5611a 2021-06-18) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2021.1.2 (CL-211.7442.42)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

Pattern in `matches!` and `assert_matches!` isn't semantically highlighted. See image below:

bug_report

There is also no autocompletion for the pattern.

## Steps to reproduce

Paste code snippet below into IDE:

 ```rust
#![feature(assert_matches)]

fn main() {
   let a = Some(0);

   matches!(a, Some(_));
   assert_matches!(a, Some(_));
}
 ```

### PR DESCRIPTION
**Pull request by vlad20012**
Fixes #7372

Support [`:pat_param`](https://blog.rust-lang.org/2021/05/11/edition-2021.html#or-patterns-in-macro_rules) `macro_rules!` matcher (from Rust 1.53.0)

Fix `:pat` matcher - now it should not parse `or patterns` (this behavior should be changed on [2021 edition](https://blog.rust-lang.org/2021/05/11/edition-2021.html#or-patterns-in-macro_rules))

changelog: FEATURE: Support [`:pat_param`](https://blog.rust-lang.org/2021/05/11/edition-2021.html#or-patterns-in-macro_rules) `macro_rules!` matcher (from Rust 1.53.0), FIX: Fix `:pat` matcher - now it should not parse `or patterns`

### CODE REVIEW

File: src/test/kotlin/org/rust/lang/core/macros/decl/RsMacroExpansionTest.kt [hunk 1]
```diff
@@ -1128,6 +1158,25 @@ class RsMacroExpansionTest : RsMacroExpansionTestBase() {
...
+        macro_rules! matches {
+            ($ expression:expr, $( $ pattern:pat_param )|+ $( if $ guard: expr )? $(,)?) => {
+                match $ expression {
+                    $( $ pattern )|+ $( if $ guard )? => true,
+                    _ => false
+                }
+            }
+        }
+        fn main() {
+            let _ = matches!(Some(1), Some(2) | Some(3));
```
Comment (sum-elier) [inline src/test/kotlin/org/rust/lang/core/macros/decl/RsMacroExpansionTest.kt:1171]: Would this feature also work with the newly introduced [Or patterns](https://blog.rust-lang.org/2021/06/17/Rust-1.53.0.html#or-patterns)?

```rust
let _ = matches!(Some(1), Some(2 | 3));
```

Comment (Undin) [reply src/test/kotlin/org/rust/lang/core/macros/decl/RsMacroExpansionTest.kt:1171]: Yep
image

Comment (Undin) [reply src/test/kotlin/org/rust/lang/core/macros/decl/RsMacroExpansionTest.kt:1171]: @vlad20012 let's add a test with or_patterns

**Review by Undin — APPROVED** [review]
LGTM

File: src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt [hunk 2]
```diff
@@ -726,4 +726,9 @@ object RustParserUtil : GeneratedParserUtilBase() {
     fun parseCodeBlockLazy(builder: PsiBuilder, level: Int): Boolean {
         return PsiBuilderUtil.parseBlockLazy(builder, LBRACE, RBRACE, BLOCK) != null
     }
+
+    @JvmStatic
+    fun parserPatWithoutOrPats(builder: PsiBuilder): Boolean {
```
Comment (Undin) [inline src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt:731]: `WithoutOrPats` suffix is quite confusing because it makes me think that it doesn't parse or_patterns at all. But it doesn't pars or_patterns only in top level. Maybe it's better not to introduce new function with a confusing name and just inline it?

Comment (vlad20012) [reply src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt:731]: It cant' be inlined because `RustParser.SimplePat` is package-private because of weird grammar-kit visibility rules

Comment (Undin) [reply src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt:731]: Well, what do you think about `parseSimplePat` name? `SimplePat` is already used in our grammar so it shouldn't confuse reader

Comment (vlad20012) [reply src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt]: Ok

**Comment by vlad20012** [comment]
bors r=undin
