### PR TITLE
RUN: Suggest to install wasm32 target in wasm-pack configuration

### LINKED ISSUE #6714: Building of wasm-pack configuration fails if wasm32 target is not installed
image

### PR DESCRIPTION
**Pull request by avrong**
Fixes #6714

In wasm-pack configuration before launch Build step checks if `wasm32-unknown-unknown` target is installed and suggests installing it if It is not.

### CODE REVIEW

File: src/main/kotlin/org/rust/cargo/toolchain/tools/Rustup.kt [hunk 1]
```diff
@@ -130,5 +173,24 @@ class Rustup(toolchain: RsToolchain, private val projectDirectory: Path) : RsToo
 
             return needInstall
         }
+
+        private fun checkNeedInstallTarget(
```
Comment (ortem) [inline src/main/kotlin/org/rust/cargo/toolchain/tools/Rustup.kt:177]: Let's add `@Suppress("SameParameterValue")` above this method

File: src/main/kotlin/org/rust/cargo/toolchain/tools/Rustup.kt [hunk 2]
```diff
@@ -43,12 +45,28 @@ class Rustup(toolchain: RsToolchain, private val projectDirectory: Path) : RsToo
...
+        }
+    }
+
     fun listComponents(): List<Component> =
         createBaseCommandLine(
             "component", "list",
             workingDirectory = projectDirectory
         ).execute()?.stdoutLines?.map { Component.from(it) }.orEmpty()
 
+    fun listTargets(): List<Target> =
```
Comment (ortem) [inline src/main/kotlin/org/rust/cargo/toolchain/tools/Rustup.kt:64]:
```suggestion
    private fun listTargets(): List<Target> =
```

File: src/main/kotlin/org/rust/cargo/toolchain/tools/Rustup.kt [hunk 3]
```diff
@@ -43,12 +45,28 @@ class Rustup(toolchain: RsToolchain, private val projectDirectory: Path) : RsToo
...
+        companion object {
+            fun from(line: String): Target {
+                val name = line.substringBefore(' ')
+                val isInstalled = line.substringAfter(' ') == "(installed)"
+                return Target(name, isInstalled)
+            }
+        }
+    }
+
     fun listComponents(): List<Component> =
```
Comment (ortem) [inline src/main/kotlin/org/rust/cargo/toolchain/tools/Rustup.kt:58]:
```suggestion
    private fun listComponents(): List<Component> =
```

File: src/main/kotlin/org/rust/cargo/toolchain/tools/Rustup.kt [hunk 4]
```diff
@@ -43,12 +45,28 @@ class Rustup(toolchain: RsToolchain, private val projectDirectory: Path) : RsToo
         }
     }
 
+    data class Target(val name: String, val isInstalled: Boolean) {
+        companion object {
+            fun from(line: String): Target {
+                val name = line.substringBefore(' ')
+                val isInstalled = line.substringAfter(' ') == "(installed)"
```
Comment (ortem) [inline src/main/kotlin/org/rust/cargo/toolchain/tools/Rustup.kt:52]: Hmm, I'm not sure why we check `"(default)"` case in `Component#from`, and I haven't managed to simulate such output from `rustup component list` and `rustup target list` (but such output is definetely possible for `rustup toolchain list`).

@mchernyavsky Could you please explain is it really necessary?

File: src/main/kotlin/org/rust/ide/actions/InstallTargetAction.kt [hunk 5]
```diff
@@ -0,0 +1,42 @@
...
+import com.intellij.openapi.project.DumbAwareAction
+import org.rust.cargo.project.settings.toolchain
+import org.rust.cargo.toolchain.tools.rustup
+import org.rust.cargo.util.DownloadResult
+import org.rust.ide.notifications.showBalloon
+import java.nio.file.Path
+
+class InstallTargetAction(
+    val projectDirectory: Path,
+    val targetName: String
```
Comment (ortem) [inline src/main/kotlin/org/rust/ide/actions/InstallTargetAction.kt:22]:
```suggestion
    private val projectDirectory: Path,
    private val targetName: String
```

**Review by ortem — CHANGES_REQUESTED** [review]

File: src/main/kotlin/org/rust/cargo/toolchain/tools/Rustup.kt (hunk 4 above)
Comment (mchernyavsky) [reply src/main/kotlin/org/rust/cargo/toolchain/tools/Rustup.kt:52]: I think this is needed on older rustup versions

(see the output from this issue - https://github.com/rust-lang/rustup/issues/1544)

Comment (ortem) [reply src/main/kotlin/org/rust/cargo/toolchain/tools/Rustup.kt]: @mchernyavsky Thank you! So we added `"(default)"` case for targets as well just in case

**Review by ortem — APPROVED** [review]
LGTM
bors r+
