### PR TITLE
Fix escape handling for non-byte strings

### LINKED ISSUE #283: Fix escape handling for non-byte strings
Basically, fix this: https://github.com/intellij-rust/intellij-rust/commit/2886d63e9c12b4ba86dfcc4e39de842b2dc46efe

Kudos to @jajakobyly for investigation

### PR DESCRIPTION
**Pull request by jajakobyly**
Fix #283

### CODE REVIEW

File: src/main/kotlin/org/rust/lang/utils/RustEscapesUtils.kt [hunk 1]
```diff
@@ -32,7 +32,7 @@ fun parseRustStringCharacters(chars: String, outChars: StringBuilder, sourceOffs
 
     val outOffset = outChars.length
     var index = 0
-    chars.tokenize(RustEscapesLexer(STRING_LITERAL, true, true)).forEach {
+    chars.tokenize(RustEscapesLexer(STRING_LITERAL, true, true, true)).forEach {
```
Comment (matklad) [inline src/main/kotlin/org/rust/lang/utils/RustEscapesUtils.kt]: Why we use `extended` here and not [here](https://github.com/intellij-rust/intellij-rust/pull/296/files#diff-d2d81e2509892bcb970852e6f23f80d0R124) ?

Comment (jajakobyly) [inline src/main/kotlin/org/rust/lang/utils/RustEscapesUtils.kt]: Unfortunately, I don't understand what you mean :confused:

Comment (matklad) [inline src/main/kotlin/org/rust/lang/utils/RustEscapesUtils.kt]: Here, we use `extendedByte = true` for `STRING_LITERAL`, but in the `of` method for `STRING_LITERAL` we don't pass any argument for `extendedByte` and it is thus `false`. This seems strange

Comment (matklad) [inline src/main/kotlin/org/rust/lang/utils/RustEscapesUtils.kt]: Linking to the diff was probably a bad idea. I am talking about this two lines

https://github.com/jajakobyly/intellij-rust/blob/lex-fix/src/main/kotlin/org/rust/lang/core/lexer/RustEscapesLexer.kt#L125
https://github.com/jajakobyly/intellij-rust/blob/lex-fix/src/main/kotlin/org/rust/lang/utils/RustEscapesUtils.kt#L35

Comment (jajakobyly) [inline src/main/kotlin/org/rust/lang/utils/RustEscapesUtils.kt]: Ah, now I get it :smile: That `STRING_LITERAL` in `parseRustStringCharacters` is only there because I had to pass something as an argument. We don't care what default token type is used in this method, we only need offsets of the escapes. This is exactly the same situation as in `unescapeRust`.

I'll put some comments with explanation for future generations.

Comment (matklad) [inline src/main/kotlin/org/rust/lang/utils/RustEscapesUtils.kt]: is there any way to refactor this in such a way that comments are not needed?

**Comment by matklad** [comment]
Thanks!
