### PR TITLE
Index macro expansions

### LINKED ISSUE #2458: Support impls defined by macros
We just landed #2331 that allows to expand macros. But currently we use it only for resolve and can't collect impls from macros. This is a very complex long-term task.

### LINKED ISSUE #2615: chain_error support?
I understand that Advanced Macro Support feature has been merged to master. I use the latest published version of the plugin but chain_err still produces `<unknown>` result type. I have enabled macro expansion feature in the settings. I wonder what is not right? Asking again, because [this](https://github.com/intellij-rust/intellij-rust/pull/2331#issuecomment-391914435) was left unanswered.

### LINKED ISSUE #2787: Invalid resolution for function defined in a macro.
## Environment

* **Intellij-Rust plugin version:** 0.2.0.2104-182
* **Rust toolchain version:** 1.28.0
* **IDE name and version:** CLion 2018.2.1
* **Operating system:** macOS 10.13.6

## Project description
`Cargo.toml`:
```toml
[package]
name = "idea-issue"
version = "0.1.0"
authors = ["blackbeam <aikorsky@gmail.com>"]

[dependencies]
exonum = "0.9.1"
```

`src/lib.rs`:
```rust
#[macro_use]
extern crate exonum;

encoding_struct! {
    struct Dummy {
        foo: u8,
    }
}

fn foo() {
    let dummy = Dummy::new(0);
}
```

## Problem description
Resolution for `Dummy` is correct:

However, resolution for `Dummy::new` is somehow `digest::digest::Digest::new`:

So an error reported as a result:

And this is true for every struct defined using `encoding_struct!` macro and leads to gazillions of annoying errors:

### LINKED ISSUE #2902: lazy_static! macro is not expanded correctly
## Environment

* **Intellij-Rust plugin version:** 0.2.0.2106-182
* **Rust toolchain version:** 1.28
* **IDE name and version:** IntelliJ IDEA 2018.2.1
* **Operating system:** Linux

## Problem description

The `lazy_static!` macro is not expanded correctly.

For example, given the following invocation:

```rust
lazy_static! {
    static ref MANIFEST_DIR: PathBuf = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
}
```

if I perform "Show recursive macro expansion" on this invocation, the resulting expansion is:

```
static MANIFEST_DIR: PathBuf = &PathBuf::from(env!("CARGO_MANIFEST_DIR"));
```

This is not the correct expansion. The correct expansion, as printed by `rustc -Z unstable-options --pretty=expanded`, is:

```rust
#[allow(missing_copy_implementations)]
#[allow(non_camel_case_types)]
#[allow(dead_code)]
struct MANIFEST_DIR {
    __private_field: (),
}
#[doc(hidden)]
static MANIFEST_DIR: MANIFEST_DIR = MANIFEST_DIR{__private_field: (),};
impl ::__Deref for MANIFEST_DIR {
    type
    Target
    =
    PathBuf;
    #[allow(unsafe_code)]
    fn deref<'a>(&'a self) -> &'a PathBuf {
        unsafe {
            #[inline(always)]
            fn __static_ref_initialize() -> PathBuf {
                PathBuf::from("<...>")
            }
            #[inline(always)]
            unsafe fn __stability() -> &'static PathBuf {
                use std::sync::ONCE_INIT;
                static mut LAZY: ::lazy::Lazy<PathBuf> =
                    ::lazy::Lazy(0 as *const PathBuf, ONCE_INIT);
                LAZY.get(__static_ref_initialize)
            }
            __stability()
        }
    }
}
```

### LINKED ISSUE #3006: Move analysis error
## Environment

* **Intellij-Rust plugin version:** 0.2.0.2109-182
* **Rust toolchain version:** rustc 1.30.0 (da5f414c2 2018-10-24)
* **IDE name and version:** IntelliJ IDEA 2018.2.5
* **Operating system:** Windows

## Problem description

I have some code that uses [nalgebra](https://crates.io/crates/nalgebra).

The plugin does not seem to understand that `Point2` (and many other types in `nalgebra`) are `Copy`.

## Steps to reproduce

* `cargo new repro`
* Add `nalgebra = "0.16.7"` to `Cargo.toml`
* Add this code:

```rust
extern crate nalgebra as na;

use na::Point2;

fn plot(point: Point2<f32>) {}

pub fn main() {
    let point = Point2::origin();
    plot(point);
    plot(point);
}
```

This compiles fine with `cargo build`, but the IDE doesn't like the second call to `plot()`.

### PR DESCRIPTION
**Pull request by vlad20012**
Now most macros are expanded once (together with indexing) and stored persistently. This opens the way to index macro expansions, and thus support impls/modules declared with macros, and also make auto-import, find symbol/usages (and other index-driven features) to work with macros. 

Also it should significantly increases performance.

Closes #2458

TODO:
- [x] support macro call insertion (bug)
- [x] replace java-serialization with something more meaningful
- [ ] compress expansion-file urls
- [x] fix spawning tons of background tasks
- [x] use write-priority retryable read actions
- [x] support modules defined with a macro (improve module index)
- [x] add possibility for auto-import to import items from macros
- [ ] split expansion task into several batches (?)
- [x] validate expanded macros sequentially (don't re-expand macros that may be invalidated by other expansions in same task)
- [ ] disable inspections/annotators while expanding macros
- [x] think about project root / search scopes
- [x] re-validate only workspace macros on local change
- [x] clear dangling expansions (check consistency) on startup
- [x] fix expansion of not-item macros
- [x] fix performance tests
- [ ] add completion tests
- [ ] clear macros directory if not accessed for a long time

### CODE REVIEW

File: src/main/kotlin/org/rust/stdext/CompletableFuture.kt [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+
+// :-(
+// https://hackage.haskell.org/package/base-4.10.0.0/docs/Data-Traversable.html
+fun <T> List<CompletableFuture<T>>.joinAll(): CompletableFuture<List<T>> =
+    CompletableFuture.allOf(*this.toTypedArray()).thenApply { map { it.join() } }
+
+fun <T> supplyAsync(executor: Executor, supplier: () -> T): CompletableFuture<T> =
+    CompletableFuture.supplyAsync(Supplier { supplier() }, executor)
+
+fun <T, R> CompletableFuture<T>.thenApplyAsync(executor: Executor, action: (T) -> R): CompletableFuture<R> =
```
Comment (mchernyavsky) [inline src/main/kotlin/org/rust/stdext/CompletableFuture.kt]: Unused.

File: src/main/kotlin/org/rust/lang/core/macros/MacroExpansionService.kt [hunk 2]
```diff
@@ -0,0 +1,723 @@
...
+sealed class MacroExpansionMode {
+    object Disabled : MacroExpansionMode()
+    object Old : MacroExpansionMode()
+    data class New(val scope: MacroExpansionScope) : MacroExpansionMode()
+
+    companion object {
+        val DISABLED = MacroExpansionMode.Disabled
+        val OLD = MacroExpansionMode.Old
+        val NEW_ALL = New(MacroExpansionScope.ALL)
+        val NEW_MacroExpansionScope = New(MacroExpansionScope.WORKSPACE)
```
Comment (mchernyavsky) [inline src/main/kotlin/org/rust/lang/core/macros/MacroExpansionService.kt]: Unused.

File: src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingTest.kt [hunk 3]
```diff
@@ -0,0 +1,238 @@
...
+import org.rust.openapiext.toPsiFile
+
+@ExpandMacros
+class RsMacroExpansionCachingTest : RsMacroExpansionTestBase() {
+    private fun type(text: String = "a"): () -> Unit = {
+        myFixture.type(text)
+        PsiDocumentManager.getInstance(project).commitAllDocuments()
+    }
+
+    private fun touchFile(path: String): (TestProject) -> Unit = { p ->
```
Comment (mchernyavsky) [inline src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingTest.kt]: Unused.

File: src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingTest.kt [hunk 4]
```diff
@@ -0,0 +1,238 @@
...
+    }
+
+    private fun replaceInFile(path: String, find: String, replace: String): (TestProject) -> Unit = { p ->
+        val file = p.root.findFileByRelativePath(path)!!
+        runWriteAction {
+            VfsUtil.saveText(file, VfsUtil.loadText(file).replace(find, replace))
+        }
+    }
+
+    private fun uncommentIn(path: String): (TestProject) -> Unit =
```
Comment (mchernyavsky) [inline src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingTest.kt]: Unused.

File: src/main/kotlin/org/rust/openapiext/utils.kt [hunk 5]
```diff
@@ -76,6 +88,40 @@ fun checkIsBackgroundThread() {
...
 
+fun checkIsDispatchThread() =
+    ApplicationManager.getApplication().assertIsDispatchThread()
+
+fun checkIsSmartMode(project: Project) {
+    if (DumbService.getInstance(project).isDumb) throw IndexNotReadyException.create()
+}
+
+fun <T: Any> invokeOnEdtAndWait(action: () -> T): T {
+    check(!ApplicationManager.getApplication().isDispatchThread) {
```
Comment (mchernyavsky) [inline src/main/kotlin/org/rust/openapiext/utils.kt]: `checkIsBackgroundThread`?

File: src/main/kotlin/org/rust/openapiext/utils.kt [hunk 6]
```diff
@@ -76,6 +88,40 @@ fun checkIsBackgroundThread() {
...
+            result = action()
+        } catch (t: Throwable) {
+            exception = t
+        }
+    }
+    exception?.let { throw it }
+    return result!!
+}
+
+fun <T: Any> runWriteActionAndWait(action: () -> T): T {
```
Comment (mchernyavsky) [inline src/main/kotlin/org/rust/openapiext/utils.kt]: Unused.

File: src/main/kotlin/org/rust/stdext/HashCode.kt [hunk 7]
```diff
@@ -0,0 +1,50 @@
...
+
+    override fun toString(): String {
+        return Hex.encodeHexString(hash)
+    }
+
+    fun toByteArray(): ByteArray = hash
+
+    companion object {
+        const val ARRAY_LEN: Int = 20
+        private val SHA256 by ThreadLocalDelegate { MessageDigest.getInstance("SHA-1") }
```
[the remark this answers is not in the document]
Comment (vlad20012) [reply src/main/kotlin/org/rust/stdext/HashCode.kt]: > Is it possible that it throws NoSuchAlgorithmException

In short, no =)

File: src/main/kotlin/org/rust/lang/core/macros/ExpandedMacrosStorage.kt [hunk 8]
```diff
@@ -0,0 +1,620 @@
...
+            rebind()
+            return infos.map { info ->
+                info.makePipeline()
+            }
+        }
+    }
+
+    @Synchronized
+    fun bindCalls(calls: List<RsMacroCall>): List<Pipeline.Stage1> {
+        checkReadAccessAllowed()
```
[the remark this answers is not in the document]
Comment (vlad20012) [reply src/main/kotlin/org/rust/lang/core/macros/ExpandedMacrosStorage.kt]: Yes, b/c we access PSI

File: src/main/kotlin/org/rust/lang/core/macros/MacroExpansionService.kt [hunk 9]
```diff
@@ -0,0 +1,723 @@
...
+        val hashBasedRebindCallHit = Testmark("hashBasedRebindCallHit")
+        val hashBasedRebindNotHit = Testmark("hashBasedRebindNotHit")
+    }
+}
+
+private fun updateDirs(projectDirName: String?): VirtualFile {
+    return updateDirs0(projectDirName ?: RandomStringUtils.randomAlphabetic(8))
+}
+
+private fun updateDirs0(projectDirName: String): VirtualFile {
```
[the remark this answers is not in the document]
Comment (vlad20012) [reply src/main/kotlin/org/rust/lang/core/macros/MacroExpansionService.kt]: It's done to shadow `projectDirName` name =(

File: src/main/kotlin/org/rust/lang/core/macros/MacroExpansionService.kt [hunk 10]
```diff
@@ -0,0 +1,723 @@
...
+    }
+
+    private fun cleanMacrosDirectory() {
+        val baseProjectDirVi = baseProjectDirVi
+        taskQueue.run(object : Task.Backgroundable(project, "Cleaning outdated macros") {
+            override fun run(indicator: ProgressIndicator) {
+                checkReadAccessNotAllowed()
+                FileUtils.cleanDirectory(baseProjectDirVi.pathAsPath.toFile())
+                supplyAsync(transactionExecutor) {
+                    runWriteAction {
```
[the remark this answers is not in the document]
Comment (vlad20012) [reply src/main/kotlin/org/rust/lang/core/macros/MacroExpansionService.kt]: Yes, b/c write action can be executed from EDT only, and we need write action to perform refresh and clean the storage

File: src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro.kt [hunk 11]
```diff
@@ -58,3 +59,10 @@ val RsMacro.macroBodyStubbed: RsMacroBody?
             )
         }
     }
+
+val RsMacro.bodyHash: HashCode?
+    get() = CachedValuesManager.getCachedValue(this) {
+        val body = stub?.macroBody ?: macroBody?.text
```
[the remark this answers is not in the document]
Comment (vlad20012) [reply src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro.kt]: Looks like we shouldn't because there is a PSI access where read access is also checked

File: src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt [hunk 12]
```diff
@@ -50,38 +54,43 @@ val RsMacroCall.macroBody: String?
             ?: vecMacroArgument?.braceListBodyText()?.toString()
     }
 
-val RsMacroCall.expansion: MacroExpansion?
-    get() = CachedValuesManager.getCachedValue(this) {
-        expandMacro(this)
+val RsMacroCall.bodyHash: HashCode?
+    get() = com.intellij.psi.util.CachedValuesManager.getCachedValue(this) {
+        val body = macroBody
```
[the remark this answers is not in the document]
Comment (vlad20012) [reply src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt]: Looks like we shouldn't because there is a PSI access where read access is also checked

File: src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt [hunk 13]
```diff
@@ -0,0 +1,626 @@
...
+        synchronized(this) {
+            rebind()
+            return infos.map { info ->
+                info.makePipeline()
+            }
+        }
+    }
+
+    @Synchronized
+    fun bindCalls(calls: List<RsMacroCall>): List<Pipeline.Stage1> {
```
Comment (fedochet) [inline src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt]: This function is called only in one place (in `makeExpansionTask`); however, its return value is not used there. Maybe it should not create that list (since it's not used) and not create `Stage1`? This way, `Stage1`'s constructor may become more strict (accept `ExpandedMacroInfo` instead of `ExpandedMacroInfo?`)

Comment (fedochet) [reply src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt]: Removing this does not affect the passing of the tests

Comment (vlad20012) [reply src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt]: :+1: :+1: :+1:

**Comment by vlad20012** [comment]
We decided not to enable it by default, see #3628.
Can be merged now
