### PR TITLE
Fix navigation to derive items in 2020.2

### LINKED ISSUE #5531: Goto definition action doesn't navigate to the derive items
## Environment

* **IntelliJ Rust plugin version:** 0.2.124.SNAPSHOT-202-dev
* **Rust toolchain version:** 1.46.0-nightly (0262de554 2020-06-07) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.2 EAP (CL-202.5103.16)
* **Operating system:** macOS 10.13.6

## Problem description
Before 2020.2 `Goto definition` action navigates you to meta item in `derive` attribute if it provides generation of the corresponding item (function, method, etc).
But it doesn't work since 2020.2.

## Steps to reproduce
```rust
#[derive(Default)]
struct Foo(i32);

fn main() {
    Foo::default();
}
```

### PR DESCRIPTION
**Pull request by vlad20012**
Fixes #5531

The old hack doesn't work anymore, I invented a new one

### CODE REVIEW

File: src/main/kotlin/org/rust/ide/navigation/goto/RsCurrentActionService.kt [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+import com.intellij.codeInsight.navigation.actions.GotoDeclarationOnlyAction
+import com.intellij.openapi.actionSystem.AnAction
+import com.intellij.openapi.actionSystem.AnActionEvent
+import com.intellij.openapi.actionSystem.DataContext
+import com.intellij.openapi.actionSystem.ex.AnActionListener
+import com.intellij.openapi.components.Service
+import com.intellij.openapi.components.service
+
+@Service
+class RsCurrentActionService {
```
Comment (Undin) [inline src/main/kotlin/org/rust/ide/navigation/goto/RsCurrentActionService.kt:18]: Let's rename it somehow (for example, to `RsGoToDeclarationService`) or move out from `navigation.goto` package

File: src/main/kotlin/org/rust/ide/navigation/goto/RsCurrentActionService.kt [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+    var isGoToDeclarationAction: Boolean = false
+        private set
+
+    private class Listener : AnActionListener {
+        override fun beforeActionPerformed(action: AnAction, dataContext: DataContext, event: AnActionEvent) {
+            if (action is GotoDeclarationAction || action is GotoDeclarationOnlyAction) {
```
Comment (Undin) [inline src/main/kotlin/org/rust/ide/navigation/goto/RsCurrentActionService.kt:24]: Let's extract this condition into property/function not to duplicate logic

Something like

```kotlin
    private val AnAction.isGoToDeclarationAction: Boolean get() = 
        this is GotoDeclarationAction || this is GotoDeclarationOnlyAction
```

File: src/main/kotlin/org/rust/ide/navigation/goto/RsCurrentActionService.kt [hunk 3]
```diff
@@ -0,0 +1,39 @@
...
+import com.intellij.openapi.actionSystem.AnAction
+import com.intellij.openapi.actionSystem.AnActionEvent
+import com.intellij.openapi.actionSystem.DataContext
+import com.intellij.openapi.actionSystem.ex.AnActionListener
+import com.intellij.openapi.components.Service
+import com.intellij.openapi.components.service
+
+@Service
+class RsCurrentActionService {
+    var isGoToDeclarationAction: Boolean = false
```
Comment (Undin) [inline src/main/kotlin/org/rust/ide/navigation/goto/RsCurrentActionService.kt:19]: Let's add some synchronization for this property. As I can see, we use it from different threads and call setter not under write action

File: src/main/kotlin/org/rust/ide/navigation/goto/RsCurrentActionService.kt [hunk 4]
```diff
@@ -0,0 +1,39 @@
...
+        private set
+
+    private class Listener : AnActionListener {
```
Comment (Undin) [inline src/main/kotlin/org/rust/ide/navigation/goto/RsCurrentActionService.kt:22]: Let's add `@Suppress("unused")` to avoid false positive `unused` annotation

File: src/main/resources/META-INF/rust-core.xml [hunk 5]
```diff
@@ -983,6 +983,11 @@
                   topic="org.rust.cargo.project.model.CargoProjectsService$CargoProjectsListener" />
     </projectListeners>
 
+    <applicationListeners>
```
Comment (Undin) [inline src/main/resources/META-INF/rust-core.xml:986]: nit: I'd personally move `applicationListeners` before `projectListeners` because they have a "wider" scope. But it's up to you

**Comment by vlad20012** [comment]
bors r=undin
