### PR TITLE
RES: fix namespace shadowing for a path in a type argument position

### LINKED ISSUE #9878: Struct is not shadowed for a path in a type argument position
## Environment

* **IntelliJ Rust plugin version:** 0.4.185.5058-223-nightly
* **Rust toolchain version:** 1.65.0 (897e37553 2022-11-02) x86_64-unknown-linux-gnu
* **IDE name and version:** IntelliJ IDEA 2022.3 Ultimate Edition (IU-223.7571.182)
* **Operating system:** Linux 5.15.0-56-generic
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.cargo.emulate.terminal

## Problem description

#7479 introduced a bug with name shadowing:

```rust
mod a {
    pub struct S;
}
use a::*;
struct S {}

trait Trait<T> {}
impl Trait<S> for S {}
         //^ Should be resolved to `struct S {}`, but actually multiresolved
```

### PR DESCRIPTION
**Pull request by vlad20012**
Fixes #9878

Also slightly speeds up name resolution because of less calls to `RsNamedElement.namespaces`

### CODE REVIEW

File: src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt [hunk 1]
```diff
@@ -52,30 +54,34 @@ fun processItemDeclarationsUsingModInfo(
...
-        val elements = hashSetOf<RsNamedElement>()
         for ((visItems, namespace) in perNs.getVisItemsByNamespace()) {
             if (namespace !in ns) continue
             for (visItem in visItems) {
                 if (ipm == WITHOUT_PRIVATE_IMPORTS && visItem.visibility == Visibility.Invisible) continue
                 if (namespace == Namespace.Types && visItem.visibility.isInvisible && name in defMap.externPrelude) continue
                 val visibilityFilter = visItem.visibility.createFilter()
                 for (element in visItem.toPsi(info, namespace)) {
-                    if (!elements.add(element)) continue
-                    if (processor.process(name, element, visibilityFilter)) return true
```
Comment (dima74) [inline src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt:67]: Why can't we use

```kotlin
if (processor.process(name, element, element.namespaces, visibilityFilter)) return true
```

Comment (vlad20012) [reply src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt:67]: This test would not pass then:

```rust
mod a {
    pub struct S;
}
use a::*;
struct S {}
     //X
trait Trait<T> {}
impl Trait<S> for S {}
         //^
```

We should use actual namespaces in which the item is available in the scope, not scopes in which the item is defined

**Review by dima74 — APPROVED** [review]
bors r+
