### PR TITLE
REF: Create public trait if needed in "Extract trait" refactoring

### LINKED ISSUE #8468: `Extract Trait` refactoring doesn't add `pub`
## Environment

* **IntelliJ Rust plugin version:** 0.4.165.4391-213-nightly
* **Rust toolchain version:** 1.59.0-nightly (0b42deacc 2021-12-09) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2021.3.1 Ultimate Edition (IU-213.6461.79)
* **Operating system:** macOS 11.5.1
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.features.settings.gutter

## Problem description
`Extract Trait` refactoring doesn't add trait imports for usages and doesn't add `pub`

## Steps to reproduce

- There is a code

```rust
pub mod color {
    pub struct Color(pub u8, pub u8, pub u8);
}

pub mod values {
    use super::color::Color;
    impl Color {
        /*caret*/ pub fn red() -> Color {
            Color(255, 0, 0)
        }
    }
}

pub use self::color::Color;
fn main() {
    color::Color::red();
}
```
- Call `Refactor -> Extract / Introduce -> Trait`

## Expected Results
```rust
pub mod color {
    pub struct Color(pub u8, pub u8, pub u8);
}

pub mod values {
    use super::color::Color;

    impl ExtractedTrait for Color {
        fn red() -> Color {
            Color(255, 0, 0)
        }
    }

    pub trait ExtractedTrait {
        fn red() -> Color;
    }
}

use crate::values::ExtractedTrait;
pub use self::color::Color;
fn main() {
    color::Color::red();
}
```

## Actual Results
There is no import for usages
```rust
pub mod color {
    pub struct Color(pub u8, pub u8, pub u8);
}

pub mod values {
    use super::color::Color;

    impl ExtractedTrait for Color {
        fn red() -> Color {
            Color(255, 0, 0)
        }
    }

    trait ExtractedTrait {
        fn red() -> Color;
    }
}

pub use self::color::Color;
fn main() {
    color::Color::red();
}
```

### PR DESCRIPTION
**Pull request by dima74**
Fixes #8468

changelog: Fix visibility of created trait in "Extract trait" refactoring

### CODE REVIEW

File: src/test/kotlin/org/rust/ide/refactoring/extractTrait/RsExtractTraitFromImplTest.kt [hunk 1]
```diff
@@ -77,11 +77,42 @@ class RsExtractTraitTest : RsExtractTraitBaseTest() {
...
+        pub trait Trait {
             fn a(&self);
         }
     """)
 
+    fun `test public method with usage`() = doTest("""
+        mod inner {
+            pub struct S;
+            impl S {
+                /*caret*/pub fn a(&self) {}
```
Comment (ortem) [inline src/test/kotlin/org/rust/ide/refactoring/extractTrait/RsExtractTraitFromImplTest.kt:89]: What do you think about processing items with restricted visibilities like `pub(crate)`? Currently, the refactoring transforms `pub(crate)` to `pub`, but maybe it could preserve it. In any case, we could add such tests to declare the expected behaviour.

**Review by ortem — APPROVED** [review]
LGTM except for one question

File: src/main/kotlin/org/rust/ide/refactoring/extractTrait/RsExtractTraitProcessor.kt [hunk 2]
```diff
@@ -155,6 +156,16 @@ class RsExtractTraitProcessor(
...
 
+    private fun getTraitVisibility(): String {
+        val visibilities = when (traitOrImpl) {
+            is RsTraitItem -> listOf(traitOrImpl.visibility)
+            is RsImplItem -> members.map { it.visibility }
+            else -> return ""
+        }
+        val unitedVisibility = visibilities.reduce(RsVisibility::unite)
+        return unitedVisibility.format()
+    }
```
Comment (ortem) [inline src/main/kotlin/org/rust/ide/refactoring/extractTrait/RsExtractTraitProcessor.kt:167]: [minor] this might be more clear
```suggestion
    private fun getTraitVisibility(): String {
        val unitedVisibility = when (traitOrImpl) {
            is RsTraitItem -> traitOrImpl.visibility
            is RsImplItem -> members.map { it.visibility }.reduce(RsVisibility::unite)
            else -> error("unreachable")
        }
        return unitedVisibility.format()
    }
```

File: src/main/kotlin/org/rust/lang/core/psi/ext/RsVisibility.kt [hunk 3]
```diff
@@ -96,6 +96,30 @@ fun RsVisibility.intersect(other: RsVisibility): RsVisibility = when (this) {
     }
 }
 
+fun RsVisibility.unite(other: RsVisibility): RsVisibility = when {
+    this is RsVisibility.Restricted && other is RsVisibility.Restricted -> {
```
Comment (ortem) [inline src/main/kotlin/org/rust/lang/core/psi/ext/RsVisibility.kt:100]: It looks like this branch is not covered by tests, as well as `else` branch

**Review by ortem — APPROVED** [review]
LGTM except for two comments

**Comment by dima74** [comment]
bors r=ortem
