### PR TITLE
COMP: don't show popup for let binding starting with a lowercase char

### LINKED ISSUE #7249: Please do not show auto-completing (of existing identifiers) for identifier declaration
## Environment

* **IntelliJ Rust plugin version:** 0.3.146.3826-211
* **Rust toolchain version:** 1.52.1 (9bc8c42bb 2021-05-09) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2021.1.1 Ultimate Edition (IU-211.7142.45)
* **Operating system:** macOS 11.2.1
* **Macro expansion engine:** new
* **Name resolution engine:** old

## Problem description

When I declare some identifier, the Intellij Rust shows an auto-completing window and focuses the top hit.
I think that's not good.

## Steps to reproduce

1. Create a rust project.
2. Write `let s` in your code.
3. PROBLEM1: then IntelliJ Rust shows auto-completing window focusing `std`.
4. Please enter a space after `let s`
5. PROBLEM2: then IntelliJ Rust enters as `let std `

image

### PR DESCRIPTION
**Pull request by vlad20012**
Fixes #7249

Don't show a completion popup automatically when typing a `let binding` identifier starting with a lowercase letter. You still can invoke the completion explicitly (using `ctrl`+`enter`, for example).

https://user-images.githubusercontent.com/3221931/127017258-40e10085-f531-4dc7-a615-7243c28e2906.mp4

If the identifier is uppercase, the user probably wants to type a destructuring pattern (`let Foo { ... }`), so we show the completion popup in this case. In `match`, `if let` and `while let` constructions completion popup is shown as before.

changelog: Don't show a completion popup automatically when typing a `let binding` identifier starting from a lowercase letter. You still can invoke the completion explicitly (using `ctrl`+`enter`, for example).

### CODE REVIEW

**Review by ortem — CHANGES_REQUESTED** [review]
Discussed in person that popup should be shown for `mut` keyword

**Comment by vlad20012** [comment]
Fixed
https://user-images.githubusercontent.com/3221931/127740726-7fab987f-e066-401e-baac-fd5f24b74f61.mp4

File: src/test/kotlin/org/rust/lang/core/completion/RsCompletionAutoPopupTest.kt [hunk 1]
```diff
@@ -66,6 +66,68 @@ class RsCompletionAutoPopupTest : RsCompletionTestBase() {
...
+        fn main() {
+            let /*caret*/
+        }
+    """, "m")
+
+    fun `test popup is shown when typing let mut 2`() = checkPopupIsShownAfterTyping("""
+        fn main() {
+            let m/*caret*/
+        }
+    """, "u")
```
Comment (ozkriff) [inline src/test/kotlin/org/rust/lang/core/completion/RsCompletionAutoPopupTest.kt:129]: I'd be good to add a test for writing an identifier after mut - `let mut /*caret*/`

File: src/main/kotlin/org/rust/lang/core/completion/RsCompletionConfidence.kt [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+import com.intellij.psi.PsiElement
+import com.intellij.psi.PsiFile
+import com.intellij.util.ThreeState
+import org.rust.lang.core.psi.RsElementTypes.IDENTIFIER
+import org.rust.lang.core.psi.RsLetDecl
+import org.rust.lang.core.psi.RsPatBinding
+import org.rust.lang.core.psi.ext.elementType
+import org.rust.lang.core.psi.ext.topLevelPattern
+
+class RsCompletionConfidence : CompletionConfidence() {
```
Comment (ozkriff) [inline src/main/kotlin/org/rust/lang/core/completion/RsCompletionConfidence.kt:18]: Maybe it's better to check if the crate suppresses any of the standard non_camel_case_types/non_snake_case/etc warnings?

Comment (vlad20012) [reply src/main/kotlin/org/rust/lang/core/completion/RsCompletionConfidence.kt:18]: I don't think this is helpful. Even if warnings are disabled, it is still unlikely that the user wants to do destructuring there. At first, I was going to not show this popup in all cases, and only then I came up with this heuristic. That is, if there is no heuristic, then in my opinion it is still better not to show the completion popup at all. A user can always call the completion manually in that 0.1% of cases when they needs it

**Review by ortem — APPROVED** [review]
bors r+

**Review by ozkriff — APPROVED** [review]
