### PR TITLE
RES: prefer enum variant over associated items

### LINKED ISSUE #7464: Dependency bitvec breaks syntax highlighting / analysis
## Environment

* **IntelliJ Rust plugin version:** 0.4.150.3968-211
* **Rust toolchain version:** cargo 1.53.0 (4369396ce 2021-04-27)
* **IDE name and version:** 
```
CLion 2021.1.2
Build #CL-211.7442.42, built on June 1, 2021
Runtime version: 11.0.11+9-b1341.57 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2000M
Cores: 8
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: org.toml.lang (0.2.150.3968-211), org.rust.lang (0.4.150.3968-211), ru.adelf.idea.dotenv (2021.2)
```
* **Operating system:** macos Big Sur

## Problem description

In a simple project, if you include a dependency on `bitvec` it appears to break highlighting and analysis of code that uses the name `Store`.

## Steps to reproduce

1. Code that works as expected:
`Cargo.toml`
```Toml
[package]
name = "test-weird-store"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
```
and
`main.rs`
```Rust
enum Hello {
    World(String),
    Store { name: String },
}

fn thing(hi: Hello) {
    match hi {
        Hello::World(_) => {}
        Hello::Store { name } => {
            println!("{}", name);
        }
    }
}

fn main() {
    thing(Hello::World("hi".to_string()));
    println!("Hello, world!");
}
```
This highlights and analyses the `Store` token correctly. See screenshot and note that, in the `match`, the `Hello::Store` arm is highlighted properly, and the `name` field has type `String`:
Screen Shot 2021-07-06 at 12 24 04 PM

2. Code the produces the error:
`Cargo.toml`
```Toml
[package]
name = "test-weird-store"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "*"
```
and
`main.rs`
```Rust
enum Hello {
    World(String),
    Store { name: String },
}

fn thing(hi: Hello) {
    match hi {
        Hello::World(_) => {}
        Hello::Store { name } => {
            println!("{}", name);
        }
    }
}

fn main() {
    thing(Hello::World("hi".to_string()));
    println!("Hello, world!");
}
```
This fails to highlight and analyse the `Store` token. See the screenshot and note that the `Store` arm is *not* syntax highlighted and the type of the `name` field is now `unknown`:
Screen Shot 2021-07-06 at 12 24 19 PM

### PR DESCRIPTION
**Pull request by vlad20012**
Fixes #7464

```rust
trait Trait { type Foo; }
impl<T> Trait for T { type Foo = (); }
enum E {
    Foo {},
    Bar {}
}
fn main() {
    let a = E::Foo {}; // This Foo is a enum variant
    if let E::Foo {} = a {} // This Foo is a enum variant
} 
```

```rust
trait Trait { fn Foo(a: i32); }
impl<T> Trait for T { fn Foo(a: i32) {} }
enum E {
    Foo(i32),
    Bar()
}
fn main() {
    let a = E::Foo(1); // This Foo is a enum variant
    if let E::Foo(_) = a {} // This Foo is a enum variant
}
```

### CODE REVIEW

File: src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt [hunk 1]
```diff
@@ -432,16 +432,19 @@ private fun processQualifiedPathResolveVariants(
         if (processor("self", base)) return true
     }
 
+    val prevScope = mutableMapOf<String, Set<Namespace>>()
```
Comment (dima74) [inline src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt:435]: [minor]
```suggestion
    val prevScope = hashMapOf<String, Set<Namespace>>()
```

**Review by dima74 — APPROVED** [review]

**Comment by vlad20012** [comment]
bors r=dima74
