### PR TITLE
(INTENTION, FIX) Fixed add derive intention in presence of pub modifiers

### LINKED ISSUE #329: Fix `add derive clause` intention if visibility is present
```
pub struct S;
```

`Alt+Enter, add derive clause`

```
pub #[derive()]struct S;
```

@netvl you may be interested in this :)

### PR DESCRIPTION
**Pull request by netvl**
Fixes #329 

@matklad please review

### CODE REVIEW

File: src/main/kotlin/org/rust/ide/intentions/AddDerive.kt [hunk 1]
```diff
@@ -31,12 +31,12 @@ class AddDerive : PsiElementBaseIntentionAction()
...
         }
         val item = element.parentOfType<RustItem>() ?: return false
-        return getStructOrEnumKeyword(item) != null
+        return getLeftmostStructOrEnumKeyword(item) != null
     }
 
-    private fun getStructOrEnumKeyword(item: RustItem): PsiElement? = when (item) {
-        is RustStructItem -> item.struct
-        is RustEnumItem   -> item.enum
+    private fun getLeftmostStructOrEnumKeyword(item: RustItem): PsiElement? =when (item) {
```
Comment (matklad) [inline src/main/kotlin/org/rust/ide/intentions/AddDerive.kt]: A space is missing after `=`. 

Another way to write this is to return `firstChild`. I'm not sure which one is better.

Comment (netvl) [inline src/main/kotlin/org/rust/ide/intentions/AddDerive.kt]: Thanks, missed it.

As for `firstChild`, I'm not sure it would work. It would mean inserting the new attribute before all other attributes, for example. I'd personally prefer it to be the "inmost" one.

Comment (netvl) [inline src/main/kotlin/org/rust/ide/intentions/AddDerive.kt]: Fixed.

**Comment by matklad** [comment]
Thanks!
