### PR TITLE
Fix `Lift return` inspection on empty match expr

### LINKED ISSUE #5677: False positive `Lift return` inspection on empty match
## Environment

* **IntelliJ Rust plugin version:** 0.2.124.3122-201-nightly
* **Rust toolchain version:** 1.43.1 (8d69840ab 2020-05-04) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2020.1.1 Ultimate Edition (IU-201.7223.91)
* **Operating system:** macOS 10.15.3

## Problem description
`Lift return out of 'match'` inspection suggests wrong quick-fix on an empty match.

It transforms the following code
```Rust
fn foo() {
    match/*caret*/ true { // `Lift return` is available
    }
    let x = 1;
}
```
into
```Rust
fn foo() {
    return match/*caret*/ true {} // `Lift return` is available again but does nothing
    let x = 1;
}
```

### PR DESCRIPTION
**Pull request by ortem**
Fixes #5677

### CODE REVIEW

File: src/test/kotlin/org/rust/ide/inspections/RsLiftInspectionTest.kt [hunk 1]
```diff
@@ -233,4 +233,12 @@ class RsLiftInspectionTest : RsInspectionsTestBase(RsLiftInspection::class) {
             }
         }
     """, checkWeakWarn = true)
+
+    fun `test lift return in empty match unavailable`() = checkFixIsUnavailable("Lift return out of 'match'", """
+        fn foo() {
+            match true {
```
Comment (Undin) [inline src/test/kotlin/org/rust/ide/inspections/RsLiftInspectionTest.kt:239]:
```suggestion
            match/*caret*/ true {
```

**Comment by ortem** [comment]
bors r=Undin

**Comment by ortem** [comment]
bors retry
