### PR TITLE
INSP: Add `#[repr(...)]` quick fix for E0308 error

### LINKED ISSUE #7894: Provide `Add repr()` attribute quick fix for E0308 error
## Environment

* **IntelliJ Rust plugin version:** 0.4.157.4136-212-nightly
* **Rust toolchain version:** 1.56.0-nightly (b7404c898 2021-09-03) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2021.2.2 Ultimate Edition (IU-212.5284.40)
* **Operating system:** macOS 10.15.6
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
If the enum variant discriminant type doesn't match enum "type", the plugin produces [E0308](https://doc.rust-lang.org/error-index.html#E0308) error (in the same way as the compiler does). 
image
image

But currently, the plugin suggests only `safe cast` quick-fix, i.e. plugin suggests changing expression type.
image

But I may want to change "base type" (i.e. enum variant "type") instead of expression type, i.e. add `#[repr(%some_type%)]` attribute ot change existing one.
It would be great to add described quick fix.

Note, the plugin already does a similar thing for functions. It suggests not only changing expression type but also changing this type of function
image

## Steps to reproduce
```rust
const PIC1_OFFSET: u8 = 32;

pub enum InterruptIndex {
    Timer = PIC1_OFFSET
}
```
or
```rust
const PIC1_OFFSET: u8 = 32;

#[repr(u16)]
pub enum InterruptIndex {
    Timer = PIC1_OFFSET
}
```

### PR DESCRIPTION
**Pull request by serid**
Fixes https://github.com/intellij-rust/intellij-rust/issues/7894.

changelog: Add a quick fix for [type mismatch E0308](https://doc.rust-lang.org/error-index.html#E0308) error that adds a `#[repr(...)]` attribute to a enum:

```rust
enum Foo {
    FooVariant = 1u16 // Error: expected `isize`, found `u16`
}
```

=>

```rust
#[repr(u16)]
enum Foo {
    FooVariant = 1u16
}
```

### CODE REVIEW

**Comment by serid** [comment]
This quick fix was strongly inspired by [this](https://github.com/intellij-rust/intellij-rust/commit/194a0eec911ca7d7f42a7ff99a061ab8762cf259#diff-7b45f27fd09aa0558b2b7cea8f77cf3d243c0cec47ed2f4b019cb18a3b71dd45) commit that added a quick fix for changing function return type.

File: src/test/kotlin/org/rust/ide/inspections/typecheck/ChangeReprAttributeFixTest.kt [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+
+    fun `test don't offer fix for non-integral types`() = checkFixIsUnavailable(
+        "Change representation of enum 'Foo' to '#[repr(u16)]'", """
+        enum Foo {
+            FooVariant = <error>'a'<caret></error>
+        }
+    """
+    )
+
+    fun `test don't offer fix for aliased types`() = checkFixIsUnavailable(
```
Comment (mchernyavsky) [inline src/test/kotlin/org/rust/ide/inspections/typecheck/ChangeReprAttributeFixTest.kt:47]: I'm not sure about this one. Maybe it's better to suggest changing the representation to `u8` in this case?

Screen Shot 2021-12-01 at 06 04 33

@Undin What do you think?

File: src/main/kotlin/org/rust/ide/annotator/fixes/ChangeReprAttributeFix.kt [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+    }
+
+    companion object {
+        private fun findEnumOwner(element: PsiElement): RsEnumItem? = element.contextStrict()
+
+        fun createIfCompatible(element: RsElement, actualTy: Ty): ChangeReprAttributeFix? {
+            if (element.containingCrate?.origin != PackageOrigin.WORKSPACE) return null
+
+            // fix only works for integral expressions inside enums. expression type should not be an alias
+            if (actualTy.isIntegral && actualTy.aliasedBy == null && findEnumOwner(element) != null)
```
Comment (mchernyavsky) [inline src/main/kotlin/org/rust/ide/annotator/fixes/ChangeReprAttributeFix.kt:74]: `findEnumOwner(element) != null` produces a false-positive in this case:

Screen Shot 2021-12-01 at 06 09 04

**Review by mchernyavsky — CHANGES_REQUESTED** [review]

**Comment by mchernyavsky** [comment]
I have rebased the branch on master and pushed some minor changes.

**Review by vlad20012 — APPROVED** [review]
bors r+

**Comment by serid** [comment]
Confratulations, guys! i tried to finish this a few months ago but couldn't run the test suit, glad you got around to it 😄
