### PR TITLE
Fix project settings serialization

### LINKED ISSUE #1870: Toolchain settings forgotten on project load
After the latest update (0.2.0.2073), no matter what I do I get the following error when opening a project:

```
Cargo project update failed:
	Can't update Cargo project, no Rust toolchain
```

Clicking "Setup toolchain", then "Ok" fixes the problem, but on the next reload the plugin loses the toolchain information again.

### PR DESCRIPTION
**Pull request by matklad**
closes #1870

Ideas serialization can't deserialize `java.nio.Path`.

r? @vlad20012

### CODE REVIEW

File: src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt [hunk 1]
```diff
@@ -90,13 +90,16 @@ interface CargoProject {
 }
 
 fun guessAndSetupRustProject(project: Project): Boolean {
+    println("project.rustSettings.toolchain = ${project.rustSettings.toolchain}")
```
Comment (vlad20012) [inline src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt]: Hmmmmmmm ?

Comment (matklad) [reply src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt]: 😊 fixed

**Comment by matklad** [comment]
bors try

**Comment by matklad** [comment]
bors try

File: src/main/kotlin/org/rust/openapiext/utils.kt [hunk 2]
```diff
@@ -40,6 +43,7 @@ fun checkWriteAccessAllowed() {
     }
 }
 
+@Suppress("unused")
```
Comment (mkaput) [inline src/main/kotlin/org/rust/openapiext/utils.kt]: Why?

**Comment by matklad** [comment]
Merge manually so as to make a new alpha release :)

File: src/main/kotlin/org/rust/openapiext/utils.kt (hunk 2 above)
Comment (matklad) [reply src/main/kotlin/org/rust/openapiext/utils.kt]: This function is indeed unused, so we probably can just remove it...

But perhaps it should be used somewhere? :) I think all our services are now thread safe, so we don't actually need to enforce  usages of read actions, but it be nice to audit them never the less :)

Comment (mkaput) [reply src/main/kotlin/org/rust/openapiext/utils.kt]: I think it is nice to leave comments every time such annotation is used :)

I thought it might be used via reflection or sth
