### PR TITLE
COMP: Add completion for dependency tables using crates local index

### LINKED ISSUE #7128: Strange behavior of auto-completion of crate versions in Cargo.toml
## Environment

* **IntelliJ Rust plugin version:** 0.3.146.3804-211-nightly
* **Rust toolchain version:** 1.53.0-nightly (16bf626a3 2021-04-14) x86_64-pc-windows-msvc
* **IDE name and version:** PyCharm 2021.1 Professional Edition (PY-211.6693.115)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Experimental feature** `ort.rust.crates.local.index`: enabled

## Problem description
Confusing autocompletion of versions at Cargo.toml.
There are 3 cases:
1. Plain dependency definition `reqwest = "0.11.3"`: autocompletion **works** as expexted
2. Long dependency definition `reqwest = {version = "0.11.3}`: **no** autocompletion
3. Dedicated dependency definition - **parital** autocompletion, plugin suggests only the last version.
```toml
[dependencies.reqwest]
version = "0.11.3"
```

## Steps to reproduce

https://user-images.githubusercontent.com/28485306/115091098-48da4a00-9f1f-11eb-9a94-476713d5638d.mp4

### PR DESCRIPTION
**Pull request by avrong**
Closes #7128

changelog: Complete table dependency specifications using crates local index. Note, currently this feature is experimental and can be enabled with `org.rust.crates.local.index` option in `Experimental Features` dialog.

### CODE REVIEW

**Comment by ortem** [comment]
@avrong Please rebase onto master

File: toml/src/main/kotlin/org/rust/toml/completion/CargoTomlCompletionContributor.kt [hunk 1]
```diff
@@ -21,12 +21,13 @@ class CargoTomlCompletionContributor : CompletionContributor() {
         if (tomlPluginIsAbiCompatible()) {
             extend(BASIC, inKey, CargoTomlKeysCompletionProvider())
             extend(BASIC, inValueWithKey("edition"), CargoTomlKnownValuesCompletionProvider(listOf("2015", "2018")))
-            extend(BASIC, inSpecificDependencyHeaderKey, CratesIoCargoTomlSpecificDependencyHeaderCompletionProvider())
-            extend(BASIC, inSpecificDependencyKeyValue, CratesIoCargoTomlSpecificDependencyVersionCompletionProvider())
             extend(BASIC, inFeatureDependencyArray, CargoTomlFeatureDependencyCompletionProvider())
             extend(BASIC, inDependencyPackageFeatureArray, CargoTomlDependencyFeaturesCompletionProvider())
 
+            // Available using crates local index
```
Comment (ortem) [inline toml/src/main/kotlin/org/rust/toml/completion/CargoTomlCompletionContributor.kt:27]: AFAIU they are available anyway but uses the different providers internally depending on the crates local index availability

File: toml/src/main/kotlin/org/rust/toml/completion/CargoTomlDependencyCompletionProvider.kt [hunk 2]
```diff
@@ -30,3 +29,39 @@ class CargoTomlDependencyCompletionProvider : CompletionProvider<CompletionParam
         delegate.addCompletionVariants(parameters, context, result)
     }
 }
+
+class CargoTomlSpecificDependencyHeaderCompletionProvider : CompletionProvider<CompletionParameters>() {
+    private val localCompletionProvider = LocalCargoTomlSpecificDependencyHeaderCompletionProvider()
+    private val cratesIoCompletionProvider = CratesIoCargoTomlSpecificDependencyHeaderCompletionProvider()
+
+    private val delegate: CompletionProvider<CompletionParameters>
```
Comment (ortem) [inline toml/src/main/kotlin/org/rust/toml/completion/CargoTomlDependencyCompletionProvider.kt:37]: Consider introducing a base class for these three providers to avoid code duplication

File: toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt [hunk 3]
```diff
@@ -58,32 +61,101 @@ class LocalCargoTomlDependencyCompletionProvider : TomlKeyValueCompletionProvide
...
+        }
 
-        val elements = sortedVersions.mapIndexed { index, variant ->
-            val lookupElement = LookupElementBuilder.create(variant.version)
-                .withInsertHandler(StringValueInsertionHandler(keyValue))
-                .withTailText(if (variant.isYanked) " yanked" else null)
+        val elements = crateNames.map { variant ->
+            LookupElementBuilder.create(variant)
+                .withIcon(AllIcons.Nodes.PpLib)
+                .withInsertHandler { ctx, item ->
```
Comment (ortem) [inline toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt:90]: [minor] could be renamed to `_`

File: toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt [hunk 4]
```diff
@@ -58,32 +61,101 @@ class LocalCargoTomlDependencyCompletionProvider : TomlKeyValueCompletionProvide
...
+
+        result.addAllElements(elements)
+    }
+}
+
+class LocalCargoTomlSpecificDependencyVersionCompletionProvider : TomlKeyValueCompletionProviderBase() {
+    override fun completeKey(keyValue: TomlKeyValue, result: CompletionResultSet) {
+        result.addElement(
+            LookupElementBuilder.create("version")
+                .withInsertHandler { ctx, item ->
```
Comment (ortem) [inline toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt:112]: `Duplicated code fragment (14 lines long)`
Please try to reduce code duplication in all these providers

**Review by ortem — CHANGES_REQUESTED** [review]

File: toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt [hunk 5]
```diff
@@ -6,25 +6,28 @@
...
 import org.rust.toml.crates.local.CratesLocalIndexService
+import org.toml.lang.psi.TomlKeySegment
 import org.toml.lang.psi.TomlKeyValue
+import org.toml.lang.psi.TomlTable
 
 class LocalCargoTomlDependencyCompletionProvider : TomlKeyValueCompletionProviderBase() {
     override fun completeKey(keyValue: TomlKeyValue, result: CompletionResultSet) {
-        val prefix = CompletionUtil.getOriginalElement(keyValue.key)?.text ?: return
+        val keySegment = keyValue.key.segments.singleOrNull() ?: return
+        val prefix = CompletionUtil.getOriginalElement(keySegment)?.text ?: return
```
Comment (ortem) [inline toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt:30]: Could you please add a test for these change? Currently, when I change these lines back, all tests pass

File: toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt [hunk 6]
```diff
@@ -37,53 +40,130 @@ class LocalCargoTomlDependencyCompletionProvider : TomlKeyValueCompletionProvide
...
                 (-crateName.length).toDouble()
             )
         }
         result.withPrefixMatcher(CargoDependenciesPrefixMatcher(prefix)).addAllElements(elements)
     }
 
     override fun completeValue(keyValue: TomlKeyValue, result: CompletionResultSet) {
-        val name = CompletionUtil.getOriginalElement(keyValue.key)?.text ?: return
+        val keySegment = keyValue.key.segments.singleOrNull() ?: return
+        val name = CompletionUtil.getOriginalElement(keySegment)?.text ?: return
```
Comment (ortem) [inline toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt:52]: Could you please add a test for these change? Currently, when I change these lines back, all tests pass

File: toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt [hunk 7]
```diff
@@ -37,53 +40,130 @@ class LocalCargoTomlDependencyCompletionProvider : TomlKeyValueCompletionProvide
...
+        EditorModificationUtil.moveCaretRelatively(context.editor, 4)
+
+        if (!alreadyHasValue) {
+            // Triggers dependency version completion
+            AutoPopupController.getInstance(context.project).scheduleAutoPopup(context.editor)
+        }
     }
 }
 
+fun makeVersionCompletions(sortedVersions: List<CargoRegistryCrateVersion>, keyValue: TomlKeyValue): List<LookupElement> {
```
Comment (ortem) [inline toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt:149]: Could be `private`?

File: toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt [hunk 8]
```diff
@@ -37,53 +40,130 @@ class LocalCargoTomlDependencyCompletionProvider : TomlKeyValueCompletionProvide
...
+    return sortedVersions.mapIndexed { index, variant ->
+        val lookupElement = LookupElementBuilder.create(variant.version)
+            .withInsertHandler(StringValueInsertionHandler(keyValue))
+            .withTailText(if (variant.isYanked) " yanked" else null)
+        PrioritizedLookupElement.withPriority(lookupElement, index.toDouble())
+    }
+}
+
+val versionsSorter: CompletionSorter = CompletionSorter.emptySorter()
```
Comment (ortem) [inline toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt:158]: Could be `private`?

File: toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt [hunk 9]
```diff
@@ -37,53 +40,130 @@ class LocalCargoTomlDependencyCompletionProvider : TomlKeyValueCompletionProvide
...
+    .weigh(RealPrefixMatchingWeigher())
+    .weigh(object : LookupElementWeigher("priority", true, false) {
+        override fun weigh(element: LookupElement): Double = (element as PrioritizedLookupElement<*>).priority
+    })
+
+fun TomlKeyValue.getDependencyKeyFromTableHeader(): TomlKeySegment {
```
Comment (ortem) [inline toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt:164]: Could be `private`?

Comment (ortem) [inline toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt:164]: Could be `private`?

File: toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt [hunk 10]
```diff
@@ -37,53 +40,130 @@ class LocalCargoTomlDependencyCompletionProvider : TomlKeyValueCompletionProvide
...
+        } catch (e: CratesLocalIndexException) {
+            return
+        }
+        val elements = makeVersionCompletions(sortedVersions, keyValue)
+        result.withRelevanceSorter(versionsSorter).addAllElements(elements)
+    }
+
+}
+
+class KeyInsertHandlerWithCompletion : InsertHandler<LookupElement> {
```
Comment (ortem) [inline toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt:132]: Could be `private`?

File: toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt [hunk 11]
```diff
@@ -37,53 +40,130 @@ class LocalCargoTomlDependencyCompletionProvider : TomlKeyValueCompletionProvide
...
+
+class LocalCargoTomlSpecificDependencyVersionCompletionProvider : TomlKeyValueCompletionProviderBase() {
+    override fun completeKey(keyValue: TomlKeyValue, result: CompletionResultSet) {
+        result.addElement(
+            LookupElementBuilder.create("version")
+                .withInsertHandler(KeyInsertHandlerWithCompletion())
+        )
+    }
+
+    override fun completeValue(keyValue: TomlKeyValue, result: CompletionResultSet) {
```
Comment (ortem) [inline toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt:103]: Please add test(s) to cover this version completion. Run with coverage can be used to verify that tests cover everything

File: toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt [hunk 12]
```diff
@@ -37,53 +40,130 @@ class LocalCargoTomlDependencyCompletionProvider : TomlKeyValueCompletionProvide
...
+
+        val sortedVersions = try {
+            CratesLocalIndexService.getInstance().getCrate(dependencyNameKey.text)?.sortedVersions ?: return
+        } catch (e: CratesLocalIndexException) {
+            return
+        }
+        val elements = makeVersionCompletions(sortedVersions, keyValue)
+        result.withRelevanceSorter(versionsSorter).addAllElements(elements)
+    }
+
```
Comment (ortem) [inline toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt:129]: Redundant empty line

**Review by ortem — CHANGES_REQUESTED** [review]

File: toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt (hunk 5 above)
Comment (avrong) [reply toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt:30]: It prevents possible completion for complex segments like `cratename.something.else = "<caret>"`. Because `cratename.version = "<caret>"` is a valid dependency declaration, but it doesn't seem to be popular, for now I think we may just ignore it

**Review by ortem — APPROVED** [review]
LGTM except for minor comments

**Comment by Stzx** [comment]
I would like to know if there will be support for the `CARGO_HOME` ENV?
