### PR TITLE
Render negative `impl`s properly

### LINKED ISSUE #7749: the Has implementations green buttom display list item wrong
## Environment

* **IntelliJ Rust plugin version:** 0.4.155.4075-212-nightly
* **Rust toolchain version:** rustc 1.56.0-nightly (ad02dc46b 2021-08-26)
* **IDE name and version:** Clion 2021.2.1
* **Operating system:** Archlinux

## Problem description
image
the list show std::sync::mpsc::Sender implement the Sync, but actually
image
it's
```rust
impl<T> !Sync for Sender<T> {}
```

### PR DESCRIPTION
**Pull request by Undin**
Fixes #7749

changelog: Properly render negative `impl` items in `Go to implementation` popup

### CODE REVIEW

**Comment by Undin** [comment]
Question: how do we want to sort negative impl items in popup?
This implementation uses text as a comparable object so it looks 
Screen Shot 2021-08-29 at 18 44 57
But probably, we want to keep previous order, i.e.
Screen Shot 2021-08-29 at 18 52 08

File: src/main/kotlin/org/rust/ide/presentation/Utils.kt [hunk 1]
```diff
@@ -74,6 +74,9 @@ private fun presentableName(psi: RsElement): String? {
             val trait = psi.traitRef?.text
             buildString {
                 if (trait != null) {
+                    if (psi.excl != null) {
```
Comment (vlad20012) [inline src/main/kotlin/org/rust/ide/presentation/Utils.kt:77]:
```suggestion
                    if (psi.isNegativeImpl) {
```
This would be more clear

**Comment by vlad20012** [comment]
How difficult is it to change the sort order? I think it can be useful, but not too much because negative impls are quite rare.

**Comment by Undin** [comment]
It's not hard but it may be hacky

**Review by vlad20012 — APPROVED** [review]
Let's handle sorting in a separate PR (if we wish to)

bors r+
