### PR TITLE
DBG: Update BTreeMap/BTreeSet GDB pretty-printers

### LINKED ISSUE #5722: GDB BTreeMap/BTreeSet pretty printers don't work since 1.44
## Environment

* **IntelliJ Rust plugin version:** 0.2.125.3191-201
* **Rust toolchain version:** 1.44.1 (c7087fe00 2020-06-17) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2020.1.2 (CL-201.7846.88)
* **Operating system:** Linux 4.15.0-109-generic

## Problem description

Since rust 1.44.0 debugger shows nothing for `BTreeMap` and `BTreeSet` collections

| 1.43.0 | 1.44.1 |
| - | - |
| Screenshot from 2020-07-11 16-28-47 | Screenshot from 2020-07-11 16-28-01 |
## Steps to reproduce
```rust
use std::collections::{BTreeMap, BTreeSet};

fn main() {
    let mut tree_map = BTreeMap::new();
    let mut tree_set = BTreeSet::new();
    for i in 1..100 {
        tree_map.insert(i.to_string(), i);
        tree_set.insert(i.to_string());
    }
}
```

### PR DESCRIPTION
**Pull request by ortem**
Update `BTreeMap`/`BTreeSet` GDB pretty-printers to the recent rustc's version.

* Fixes #5722

* Handle zero-sized keys or values https://github.com/rust-lang/rust/pull/77788
I also added a fix to the original commit from rustc: `gdb.parse_and_eval("()")` instead of simple `"()"` in `children_of_node` method. This is needed because GDB treats `"()"` as a Rust array of two characters, not as a unit

After merge:
- [ ] Upstream a fix for zero-sized keys or values to rustc

### CODE REVIEW

File: pretty_printers_tests/tests/btree.rs [hunk 1]
```diff
@@ -24,5 +25,9 @@ fn main() {
     for i in 0..15 {
         btree_map.insert(i, i);
     }
+
+    let mut zst_btree_map: BTreeMap<(), ()> = BTreeMap::new();
```
Comment (Undin) [inline pretty_printers_tests/tests/btree.rs:29]: Maybe it worth to add the same test for `BTreeSet` as well?

**Review by Undin — COMMENTED** [review]
The current version of pretty printers doesn't work with rust 1.33. It would be great to make it works with it if possible. Otherwise, let's update `min-version` for btree tests with proper value

File: pretty_printers_tests/tests/btree.rs (hunk 1 above)
Comment (ortem) [reply pretty_printers_tests/tests/btree.rs:32]: Added

**Comment by ortem** [comment]
@Undin I've updated the minimum Rust version for the `BTreeMap`/`BTreeSet` pretty-printers tests to 1.34.0. Not sure if it's worth the time finding a way to change the code in order to support such an old version

**Review by Undin — APPROVED** [review]
bors r+

**Comment by Undin** [comment]
bors retry
