### PR TITLE
INSP: Fix renaming mod declaration by "Module naming convention"

### LINKED ISSUE #8120: Rename refactoring works incorrect via quick fix
## Environment

* **IntelliJ Rust plugin version:** 0.4.161.4249-213-nightly
* **Rust toolchain version:** 1.58.0-nightly (1af55d19c 2021-10-19) x86_64-apple-darwin
* **IDE name and version:** CLion 2021.3 Beta (CL-213.5744.5)
* **Operating system:** macOS 11.5.1
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
Rename quick fix doesn't rename files and references 

## Steps to reproduce
1. There is a piece of code.
    `src/main.rs`
    ```rust
    pub mod Week;
    
    fn main() {
        Week::sum(5,7);
    }
    ```
    `src/Week.rs`
    ```rust
    pub fn sum(a: i32,b:i32) -> i32 
    {
           let mut c = a + b; 
           c 
    }
    ```

2.Rename Week in main.rs to week via quick fix

## Expected Results:
File and all references are remaned

## Actual Results:
Only one row is renamed
rename_ref

### PR DESCRIPTION
**Pull request by dima74**
Fixes #8120

changelog: Fix renaming mod declaration by "Module naming convention" inspection

### CODE REVIEW

**Review by ozkriff — APPROVED** [review]

**Review by ortem — APPROVED** [review]
LGTM
bors r+

File: src/main/kotlin/org/rust/ide/inspections/fixes/RenameFix.kt [hunk 1]
```diff
@@ -29,6 +30,7 @@ class RenameFix(
 
     override fun invoke(project: Project, file: PsiFile, startElement: PsiElement, endElement: PsiElement) =
         invokeLater {
-            RefactoringFactory.getInstance(project).createRename(startElement, newName).run()
+            val element = (startElement as? RsModDeclItem)?.reference?.resolve() ?: startElement
```
Comment (Undin) [inline src/main/kotlin/org/rust/ide/inspections/fixes/RenameFix.kt:33]: Can this `resolve()` call be long-running (for example, read indices)? If yes, maybe it's worth extracting it into background thread?

Comment (dima74) [reply src/main/kotlin/org/rust/ide/inspections/fixes/RenameFix.kt]: Done

**Review by ortem — APPROVED** [review]
LGTM, one minor comment

File: src/main/kotlin/org/rust/openapiext/utils.kt [hunk 2]
```diff
@@ -419,16 +419,16 @@ fun <T, D> getCachedOrCompute(
     return value
 }
 
-inline fun <R> nonBlocking(project: Project, crossinline block: () -> R, crossinline uiContinuation: (R) -> Unit) {
+inline fun <R> Project.nonBlocking(crossinline block: () -> R, crossinline uiContinuation: (R) -> Unit) {
```
Comment (ortem) [inline src/main/kotlin/org/rust/openapiext/utils.kt:422]: Looks like this method is intended to be used only from the UI thread. But I suppose it might be unclear when you don't look into its implementation. Maybe add a doc comment like "Must be invoked on EDT"?

Comment (dima74) [reply src/main/kotlin/org/rust/openapiext/utils.kt:423]: Added a comment

**Comment by dima74** [comment]
bors r=ortem
