### PR TITLE
PRJ: Trim template name and URL when creating new project

### LINKED ISSUE #9968: Cannot create a new project from a template when URL contains trailing whitespace
## Environment

* **IntelliJ Rust plugin version:** 0.4.186.5089-223-nightly
* **Rust toolchain version:** 1.66.0 (69f9c33d7 2022-12-12) x86_64-apple-darwin
* **IDE name and version:** CLion 2022.3.1 (CL-223.8214.51)
* **Operating system:** macOS 11.1

## Problem description

Cannot create a new project from a template when URL contains trailing whitespace.

## Steps to reproduce

1. Open New Project dialog
2. Add project template via `+` button with a template URL containing trailing whitespace (e.g. `https://github.com/intellij-rust/wasm-pack-template `)
3. Create project using that template
4. The generated project is empty, and the plugin throws `org.rust.openapiext.RsProcessExecutionException$ProcessAborted` exception

### PR DESCRIPTION
**Pull request by ortem**
Fixes #9968.

changelog: Trim template name and URL when creating a new project using a [custom cargo-generate template](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-new-cargo-projects.html#cargo-generate)

### CODE REVIEW

File: src/main/kotlin/org/rust/ide/newProject/ui/AddUserTemplateDialog.kt [hunk 1]
```diff
@@ -43,22 +43,27 @@ class AddUserTemplateDialog : DialogWrapper(null) {
 
     override fun doOKAction() {
         // TODO: Find a better way to handle dialog form validation
-        if (nameField.text.isBlank()) return
-        if (RsUserTemplatesState.getInstance().templates.any { it.name == nameField.text }) return
+        val name = nameField.text.trim()
```
Comment (Undin) [inline src/main/kotlin/org/rust/ide/newProject/ui/AddUserTemplateDialog.kt:46]: nit: maybe introduce `trimmedText` extension property for text fields since we use it several times? We even have a file for such extensions - `src/main/kotlin/org/rust/openapiext/ui.kt`.
Don't insist

**Comment by ortem** [comment]
* Added `JBTextField.trimmedText`
* Fixed `AddUserTemplateDialog#suggestName` to suggest a trimmed name when a URL with trailing spaces was inserted

**Review by Undin — APPROVED** [review]
bors r+
