### PR TITLE
Initial reexports support for auto import

### LINKED ISSUE #2157: Auto import doesn't work
I just updated this plugin to version `0.2.0.2083` and saw in the changelog

> Initial support of auto import :tada: Now it is implemented as intention so you can try it via Alt+Enter at unresolved reference

and that sounded super awesome! But after updating and restarting IntelliJ IDEA (see below for meta stuff), I could not see any intention for the following code (simple, single-crate project) even though the "Import" intention is enabled:

```rust
fn simple() {
    let mut map = HashMap::new();
}
```

My Rust version is

```
rustc 1.24.0-nightly (7eb64b86c 2017-12-20)
```

and IDEA -> Help -> About gives me

```
IntelliJ IDEA 2017.3.1 (Community Edition)
Build #IC-173.3942.27, built on December 11, 2017
JRE: 1.8.0_152-release-1024-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-104-generic
```

### PR DESCRIPTION
**Pull request by Undin**
Part of #1737 and #2174
Fixes #2157

TODO:
* support `pub use` with wildcards
* filter import candidates for the same item (for example, `std::sync::Arc` and `alloc::arc::Arc`)

### CODE REVIEW

**Comment by Undin** [comment]
@matklad r?

File: src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt [hunk 1]
```diff
@@ -140,16 +140,6 @@ fun processItemDeclarations(
     return false
 }
 
-private val RsUseSpeck.nameInScope: String? get() {
-    alias?.name?.let { return it }
-    val baseName = path?.referenceName ?: return null
-    if (baseName == "self") {
-        NameResolutionTestmarks.selfInGroupName.hit()
```
Comment (Undin) [inline src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt]: Unfortunately, I don't know good way to make this code public, not to remove this testmark and not to add some artificial code at the same time
Any idea?

File: src/main/kotlin/org/rust/ide/intentions/import/ImportNameIntention.kt [hunk 2]
```diff
@@ -32,31 +33,48 @@ class ImportNameIntention : RsElementBaseIntentionAction<ImportNameIntention.Con
...
+
+        val parentMod = parentMod ?: return null
         val ourSuperMods = parentMod.superMods
 
         // try to find latest common ancestor module of `parentMod` and `mod` in module tree
         // we need to do it because we can use direct child items of any super mod with any visibility
         val lca = ourSuperMods.find { it in superMods }
-        val crateRelativePath = (this as? RsQualifiedNamedElement)?.crateRelativePath?.removePrefix("::") ?: return null
+        val crateRelativePath = crateRelativePath ?: return null
+        val isPublic = when (this) {
```
Comment (matklad) [inline src/main/kotlin/org/rust/ide/intentions/import/ImportNameIntention.kt]: Can be a virtual function of `ImportItem`.

File: src/main/kotlin/org/rust/ide/intentions/import/ImportNameIntention.kt [hunk 3]
```diff
@@ -32,31 +33,48 @@ class ImportNameIntention : RsElementBaseIntentionAction<ImportNameIntention.Con
...
+            .map { ImportItem.ExplicitItem(it) }
+
+        val reexportedItems = RsReexportIndex.findReexportsByName(project, basePath.referenceName)
+            .asSequence()
+            .mapNotNull {
+                val item = it.path?.reference?.resolve() as? RsQualifiedNamedElement ?: return@mapNotNull null
+                ImportItem.ReexportedItem(it, item)
+            }
+
+        val candidates = (explicitItems + reexportedItems)
```
Comment (matklad) [inline src/main/kotlin/org/rust/ide/intentions/import/ImportNameIntention.kt]: I am a bit worried that a single item can be both inside explicit and reexported items (if it is reexported under it's original name). I don't know a way to avoid it though :(

File: src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt (hunk 1 above)
Comment (matklad) [reply src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt]: I think this is fine :)

File: src/main/kotlin/org/rust/ide/intentions/import/ImportNameIntention.kt (hunk 3 above)
Comment (Undin) [reply src/main/kotlin/org/rust/ide/intentions/import/ImportNameIntention.kt]: It's next step of auto import improvement
I think we can use some heuristic rules, for example, if there are items from `std` and from other crates, exclude items from other crates. Or drop `mod::sub_mod::item` if there is reexport of this item in `mod`.

Comment (Undin) [reply src/main/kotlin/org/rust/ide/intentions/import/ImportNameIntention.kt]: At least `PyCharm` uses the last rule

File: src/main/kotlin/org/rust/ide/intentions/import/ImportNameIntention.kt (hunk 2 above)
Comment (Undin) [reply src/main/kotlin/org/rust/ide/intentions/import/ImportNameIntention.kt]: Hm, the reason why I didn't it before is check for `RsVisibile` at the beginning of method and next smart cast in `when` expression
So I can move it into separate method of `ImportItem` but in my opinion, it will be not very gracefully
Anyway, it should be refactored to support enum variants which are not `RsVisible` at all and can't be import now at all.

Comment (matklad) [reply src/main/kotlin/org/rust/ide/intentions/import/ImportNameIntention.kt]: Sounds reasonable!

**Comment by matklad** [comment]
LGTM

**Comment by Undin** [comment]
bors r=matklad
