### PR TITLE
RES: support impls for aliased types

### LINKED ISSUE #2778: Impls for aliased types are ignored
## Environment

* **Intellij-Rust plugin version:** 0.20.2103-182
* **Rust toolchain version:** stable-x86_64-pc-windows-msvc
* **IDE name and version:** IntelliJ IDEA 2018.2.2 (Ultimate Edition)
Build #IU-182.4129.26, built on August 16, 2018
Licensed to Sirguy Chikirev
Subscription is active until March 21, 2019
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
* **Operating system:**

## Problem description
IDE  IntelliSense do not recognize Rust type aliases.  

## Steps to reproduce
create default executable Rust project, and insert this snippet.
```Rust
struct EE {
    pub field1: u32,
    pub field2: u8,
}

type XX = EE;

impl XX {
    pub fn new() -> XX {
        XX { field1: 2, field2: 3 }
    }
}

fn main() {
    let xx = XX::new(); // new() is not recognized by intellisense
    println!("{:?}", xx.field2); //xx type in not recognized by intellisense

    let yy = EE::new();// new() is not recognized by intellisense
    println!("{:?}", yy.field2); //yy type in not recognized by intellisense
}
```

but the code is correct and compile / executed properly.

### PR DESCRIPTION
**Pull request by vlad20012**
Fixes #2778

```rust
struct X;
type Y = X;
impl Y { fn foo(&self) {} }
          //X
fn main() {
    X.foo();
}   //^
```

### CODE REVIEW

**Comment by Undin** [comment]
@vlad20012 What's about performance?

**Comment by vlad20012** [comment]
@Undin performance is OK with this line =D https://github.com/intellij-rust/intellij-rust/pull/4936/files#diff-bb998b1531ccb11517e209ed14d5a021R37

**Comment by Undin** [comment]
@vlad20012 link doesn't contain line number but I assume you meant the following line
`if (aliases.size > 10) return false`

**Comment by Kobzol** [comment]
I tested this on my project (which has less than 10 aliases :-D ) and it works nicely.

File: src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt [hunk 1]
```diff
@@ -403,6 +409,30 @@ class ImplLookup(
...
+                set.add(aliasFingerprint) &&
+                    canCombineTypes(selfTy, it.declaredType, it.generics) &&
+                    processor(aliasFingerprint)
+            }
+            if (result) return true
+        }
+        return processor(TyFingerprint.TYPE_PARAMETER_FINGERPRINT)
+    }
+
+    private fun canCombineTypes(ty1: Ty, ty2: Ty, genericsForTy2: List<TyTypeParameter>): Boolean {
```
[the remark this answers is not in the document]
Comment (vlad20012) [reply src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt]: Hmm, this fragment duplicates one from another place. I think I intentionally extracted it in order to make less copy-paste, but something went wrong during the rebase.

File: src/main/kotlin/org/rust/lang/core/resolve/indexes/RsTypeAliasIndex.kt [hunk 2]
```diff
@@ -0,0 +1,81 @@
...
+        }
+
+        fun index(stub: RsTypeAliasStub, sink: IndexSink) {
+            val alias = stub.psi
+            val typeRef = alias.typeReference ?: return
+            TyFingerprint.create(typeRef, emptyList())
+                .forEach { sink.occurrence(KEY, it) }
+        }
+
+        private const val ALIAS_COUNT_THRESHOLD = 10
```
Comment (Undin) [inline src/main/kotlin/org/rust/lang/core/resolve/indexes/RsTypeAliasIndex.kt]: Maybe it's better to add registry key with the same default value to have the opportunity to fix some local user issues because of too small/too large threshold?

Comment (vlad20012) [reply src/main/kotlin/org/rust/lang/core/resolve/indexes/RsTypeAliasIndex.kt]: Sounds reasonable. Done
