### PR TITLE
REPL: Fix imports

### LINKED ISSUE #5214: Imports not working in REPL console
## Environment

* **IntelliJ Rust plugin version:** 0.2.119.2172-193
* **Rust toolchain version:** 1.42.0
* **IDE name and version:** IntelliJ IDEA 2019.3.3
* **Operating system:** Linux

## Problem description
When execute import command (`use ...;`) in REPL console as separate command, it doesn't affect completion

image

## Steps to reproduce
* Execute command `use std::fs;` in REPL console
* Type `fs::` and invoke completion

### PR DESCRIPTION
**Pull request by dima74**
Fix #5214

Previously only `RsNamedElement` and `RsStmt` were added to context, so imports were ignored

### CODE REVIEW

**Comment by dima74** [comment]
Added some tests (and rebased on master)

File: src/main/kotlin/org/rust/lang/core/psi/RsCodeFragment.kt [hunk 1]
```diff
@@ -162,4 +162,5 @@ class RsReplCodeFragment(fileViewProvider: FileViewProvider, override var contex
     val tailExpr: RsExpr?
```
Comment (ortem) [inline src/main/kotlin/org/rust/lang/core/psi/RsCodeFragment.kt:162]: I'd suggest go the `org.rust.lang.core.psi.ext.RsBlockKt#getExpandedStmtsAndTailExpr` way here. It can be done even without macro expansion usage (but would be nice to use expanded macros in REPL someday), like this:
```Kotlin
val expandedStmtsAndTailExpr: Pair<List<RsExpandedElement>, RsExpr?>
    get() {
        val expandedElements = childrenOfType<RsExpandedElement>()
        val tailExpr = expandedElements.lastOrNull()?.let { it as? RsExpr }
        return when (tailExpr) {
            null -> expandedElements
            else -> expandedElements.subList(0, expandedElements.size - 1)
        } to tailExpr
    }
```
Then you can use `getExpandedStmtsAndTailExpr` instead of `stmts`, `tailExpr`, and `items` in type inference/name resolution and `org.rust.ide.console.RsConsoleOneCommandContext`.

Or maybe you will come up with another way of doing this, it'd be OK too.

File: src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt [hunk 2]
```diff
@@ -57,15 +57,21 @@ class RsConsoleCodeFragmentContext {
 }
 
 class RsConsoleOneCommandContext(codeFragment: RsReplCodeFragment) {
-    val topLevelElements: MutableMap<String, String> = mutableMapOf()
+    val topLevelItems: MutableMap<String, String> = mutableMapOf()
```
Comment (ortem) [inline src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt:60]: Do we really want to split all elements into "items" and "statements"?
Probably it may lead to bugs because order matters:
```Rust
use foo;
stmt_1;
use bar;
stmt_2;
```
can be semantically different from
```Rust
use foo;
use bar;
stmt_1;
stmt_2;
```
But maybe I'm wrong and it is OK, what do you think?

Comment (dima74) [reply src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt]: Originally we split elements into items and statements, because we want to do something with items which have same name (they are not allowed in rust functions, but are allowed in evcxr repl). This approach can indeed lead to some bugs (please see new tests which check redefining function/struct). I remove that splitting and now we use nested scopes for next commands, like so:

```rust
fn main() {
    command1;
    {
        command2;
        {
            command3;
        }
    }
}
```
And `RsBlock` surrounding last command (`command3`) will become context of codeFragment

File: src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt [hunk 3]
```diff
@@ -57,15 +57,21 @@ class RsConsoleCodeFragmentContext {
...
     val statementsText: String
 
     init {
-        for (namedElement in codeFragment.namedElements) {
-            val name = namedElement.name ?: continue
-            topLevelElements[name] = namedElement.text
+        val namedItems = codeFragment.items
```
[the remark this answers is not in the document]
Comment (dima74) [reply src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt]: Code was partially rewritten, and `items` is no longer used

File: src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt [hunk 4]
```diff
@@ -10,42 +10,61 @@ import com.intellij.openapi.project.DumbService
...
 import org.rust.lang.core.psi.*
-import org.rust.lang.core.psi.ext.descendantOfTypeStrict
+import org.rust.lang.core.psi.ext.*
 import org.rust.openapiext.toPsiFile
 
 class RsConsoleCodeFragmentContext {
 
-    private val topLevelElements: MutableMap<String, String> = mutableMapOf()
-    private val allCommandsText: StringBuilder = StringBuilder()
+    private val itemsNames: Set<String> = mutableSetOf()
```
Comment (ortem) [inline src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt:18]: Looks like `itemsNames` is always empty, so `commands` contains only one element and nested scopes are not used later

Comment (dima74) [reply src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt]: Thanks! Should be fixed now. Also I updated tests, so now they behave closer to real REPL

File: src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt [hunk 5]
```diff
@@ -10,42 +10,87 @@ import com.intellij.openapi.project.DumbService
...
+            // ```
+            val functionBody = commands.joinToString("\n{\n") + "\n}".repeat(commands.size - 1)
+            val rsFile = RsPsiFactory(project).createFile("fn main() { $functionBody }")
 
             val crateRoot = originalCrateRoot ?: findAnyCrateRoot(project)
             crateRoot?.let { rsFile.originalFile = crateRoot }
 
-            return rsFile.descendantOfTypeStrict()!!
+            var block: RsBlock = rsFile.childOfType<RsFunction>()!!.block!!
+            repeat(commands.size - 1) {
```
Comment (ortem) [inline src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt:89]: Consider using `generateSequence` instead

File: src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt [hunk 6]
```diff
@@ -57,15 +102,17 @@ class RsConsoleCodeFragmentContext {
...
 
     init {
-        for (namedElement in codeFragment.namedElements) {
-            val name = namedElement.name ?: continue
-            topLevelElements[name] = namedElement.text
-        }
+        val elements = codeFragment.expandedStmtsAndTailExpr.first
+        command = elements.joinToString("\n") { it.text }
+
+        itemsNames = elements.filterIsInstance<RsNamedElement>()
```
[the remark this answers is not in the document]
Comment (dima74) [reply src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt:113]: I think we don't need uniqueness here, code in `RsConsoleCodeFragmentContext` would work correctly if there are duplicates. Also if there are items with same name, then command will not be executed successfully, so `RsConsoleOneCommandContext` will not be used

File: src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt [hunk 7]
```diff
@@ -57,15 +102,17 @@ class RsConsoleCodeFragmentContext {
 }
 
 class RsConsoleOneCommandContext(codeFragment: RsReplCodeFragment) {
-    val topLevelElements: MutableMap<String, String> = mutableMapOf()
-    val statementsText: String
+    val command: String
+    val itemsNames: List<String>
```
[the remark this answers is not in the document]
Comment (dima74) [reply src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt:106]: I am not sure that we need `Set` here:
* we don't need fast lookups (because we don't do lookups)
* we don't need uniqueness (actually if command is executed successfully then all names should already be unique)

File: src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt [hunk 8]
```diff
@@ -10,42 +10,98 @@ import com.intellij.openapi.project.DumbService
...
+import org.rust.lang.core.resolve.findPrelude
+import org.rust.lang.core.resolve.processNestedScopesUpwards
 import org.rust.openapiext.toPsiFile
 
-class RsConsoleCodeFragmentContext {
+class RsConsoleCodeFragmentContext(codeFragment: RsReplCodeFragment?) {
 
-    private val topLevelElements: MutableMap<String, String> = mutableMapOf()
-    private val allCommandsText: StringBuilder = StringBuilder()
+    private val itemsNames: MutableSet<String> = mutableSetOf()
```
Comment (ortem) [inline src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt:23]: Maybe use `ContainerUtil.newConcurrentSet()` and get rid of synchronized `addItemsNames`?

File: src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt (hunk 6 above)
[the remark this answers is not in the document]
Comment (ortem) [reply src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt:124]: It just looks a bit confusing that there are two cases when all named elements are needed, but they are collected in different ways. Probably there could be something like:
```Kotlin
val namedElementsUnique: Map<String, RsNamedElement>
    get() = expandedStmtsAndTailExpr.first  // to take expanded named elements into account when you implement processing macros in `expandedStmtsAndTailExpr`
        .filterIsInstance<RsNamedElement>()
        .filter { it.name != null }
        .associateBy { it.name!! }
```
So this property can be used when named elements or just their names are needed. But this can be done later.

File: src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt [hunk 9]
```diff
@@ -10,42 +10,98 @@ import com.intellij.openapi.project.DumbService
...
+    private val commands: MutableList<String> = mutableListOf()
 
-    fun addToContext(lastCommandContext: RsConsoleOneCommandContext) {
-        topLevelElements.putAll(lastCommandContext.topLevelElements)
-        allCommandsText.append(lastCommandContext.statementsText)
+    init {
+        if (codeFragment != null) {
+            DumbService.getInstance(codeFragment.project).runWhenSmart {
```
Comment (ortem) [inline src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt:28]: Looks like the user can redefine some items from prelude before this code is invoked. I mean completion may be invalid in such case:
```Rust
>> let foo = Some(1);
>> struct Some(i32, i32);
// indexing ends, `addItemsNamesFromPrelude` is invoked
>> foo./*caret*/
```

File: src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt (hunk 6 above)
[the remark this answers is not in the document]
Comment (dima74) [reply src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt]: Ok, I agree that it is confusing, so updated code as you proposed

File: src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt (hunk 9 above)
Comment (dima74) [reply src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt:31]: Thanks, fixed by forcing creating new scope if names for items from prelude are not yet added

File: src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt [hunk 10]
```diff
@@ -8,44 +8,100 @@ package org.rust.ide.console
...
 import org.rust.openapiext.toPsiFile
 
-class RsConsoleCodeFragmentContext {
+class RsConsoleCodeFragmentContext(codeFragment: RsReplCodeFragment?) {
 
-    private val topLevelElements: MutableMap<String, String> = mutableMapOf()
-    private val allCommandsText: StringBuilder = StringBuilder()
+    // concurrent set is needed because accessed both in `addItemsNamesFromPrelude` and `addToContext`
+    private val itemsNames: MutableSet<String> = ContainerUtil.newConcurrentSet()
+    private var hasAddedNamesFromPrelude = false
```
Comment (ortem) [inline src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt:25]: Don't forget about `@Volatile`

**Comment by dima74** [comment]
bors r=ortem
