### PR TITLE
 INT: don't suggest "Put parameters/arguments/fields/variants on separate lines/one line" if comments are present

### LINKED ISSUE #4708: "Put fields on one line" generates invalid code if comments are present
## Environment

* **IntelliJ Rust plugin version:** 0.2.112.SNAPSHOT-193-dev
* **Rust toolchain version:** 1.39.0 (4560ea788 2019-11-04) x86_64-apple-darwin
* **IDE name and version:** CLion 2019.3 (CL-193.5233.103)
* **Operating system:** macOS 10.15

## Problem description

With  #4332 changes in place.
"Put fields on one line" action produces invalid code if fields have comments.

## Steps to reproduce

```rust
struct MyStruct {
    x: u8,
    y: u8,
}

fn main() {
    MyStruct {
        x: 10,  // Some field
        y: 20,  // Another field
    };
}
```

Call "Put fields on one line" on `x` on 9 line:

```rust
struct MyStruct {
    x: u8,
    y: u8,
}

fn main() {
    MyStruct { x: 10,  // Some field y: 20,  // Another field };
}
```

### PR DESCRIPTION
**Pull request by t-kameyama**
Fixes #4708

### CODE REVIEW

File: src/main/kotlin/org/rust/ide/intentions/JoinListIntention.kt [hunk 1]
```diff
@@ -49,6 +52,16 @@ abstract class JoinListIntentionBase<TList : RsElement, TElement : RsElement>(
             document.replaceString(startOffset, endOffset, replaceString)
         }
     }
+
+    private fun RsElement.hasEolComment(): Boolean {
```
Comment (ortem) [inline src/main/kotlin/org/rust/ide/intentions/JoinListIntention.kt]: Maybe replace with 
```Kotlin
private fun RsElement.hasEolComment(): Boolean =
    descendantsOfType<PsiComment>().any { it.elementType == EOL_COMMENT }
```
if it works too (at least it passess all your tests)?

**Comment by ortem** [comment]
Thanks!
bors r+
