### PR TITLE
INT: drop "Remove parentheses from expression" intention

### LINKED ISSUE #4810: "Remove parentheses from expression" results in a broken code
## Environment

* **IntelliJ Rust plugin version:** 0.2.114.2822-193-nightly
* **Rust toolchain version:** 1.39.0 (4560ea788 2019-11-04) x86_64-apple-darwin
* **IDE name and version:** CLion 2019.3.2 (CL-193.5662.56)
* **Operating system:** macOS 10.15

## Problem description

The plugin may suggest removing needless parentheses from expression, unfortunately in case of multiple nested parentheses the wrong parentheses pair may be removed resulting in a broken code.

## Steps to reproduce

```rust
pub fn total() -> u64 {
    ((-1 + (2 as i128).pow(64))) as u64
}
```

Place the caret on `as` and trigger "Remove parentheses from expression". Result

```rust
pub fn total() -> u64 {
    ((-1 + 2 as i128.pow(64))) as u64
}
```

### PR DESCRIPTION
**Pull request by t-kameyama**
Fixes #4810

### CODE REVIEW

**Comment by t-kameyama** [comment]
I think we should drop this intention.

File: src/test/kotlin/org/rust/ide/annotator/fixes/RemoveRedundantParenthesesFixTest.kt [hunk 1]
```diff
@@ -0,0 +1,97 @@
...
+ * Use of this source code is governed by the MIT license that can be
+ * found in the LICENSE file.
+ */
+
+package org.rust.ide.annotator.fixes
+
+import org.rust.ide.annotator.RsAnnotatorTestBase
+import org.rust.ide.annotator.RsExpressionAnnotator
+
+class RemoveRedundantParenthesesFixTest : RsAnnotatorTestBase(RsExpressionAnnotator::class) {
```
Comment (Undin) [inline src/test/kotlin/org/rust/ide/annotator/fixes/RemoveRedundantParenthesesFixTest.kt]: Let's add some tests to ensure we don't provide warning annotation with quick fix for cases like `(1 + 2).pow(3)`

File: src/main/kotlin/org/rust/ide/annotator/RsExpressionAnnotator.kt [hunk 2]
```diff
@@ -92,10 +94,27 @@ private class RedundantParenthesisVisitor(private val holder: RsAnnotationHolder
...
     private fun RsExpr?.warnIfParens(message: String) {
-        if (this !is RsParenExpr) return
-        val fix = RemoveParenthesesFromExprIntention()
-        if (fix.isAvailable(this))
-            holder.createWeakWarningAnnotation(this, message)?.registerFix(RemoveParenthesesFromExprIntention())
+        if (this !is RsParenExpr || !canWarn(this)) return
+        val fix = RemoveRedundantParenthesesFix(this)
+        val descriptor = InspectionManager.getInstance(project)
+            .createProblemDescriptor(this, message, fix, ProblemHighlightType.GENERIC_ERROR_OR_WARNING, true)
+        holder.createWeakWarningAnnotation(this, message)?.registerFix(fix, null, null, descriptor)
```
Comment (Undin) [inline src/main/kotlin/org/rust/ide/annotator/RsExpressionAnnotator.kt]: Oh, sorry - I forget that `Annotation` has more complex API for `LocalQuickFix` than for `IntentionAction`.
Let's revert replacing `LocalQuickFixAndIntentionActionOnPsiElement` with `LocalQuickFixOnPsiElement` and simplify this code in the corresponding way
