### PR TITLE
TY: Improve array expr type inference

### LINKED ISSUE #1790: TY: Introduce array of unknown size
This code is ok, but syntax checker marks array as wrong

```rust
const COUNT: usize = 2;

struct Foo {
    v: [usize; COUNT]
}

fn bar(f: Foo) {}

fn main() {
    bar(Foo{
        v:[10, 20] // E308, expected [usize], found [usize; 2]
    });
}
```

[Mentoring instructions can be found in this comment](https://github.com/intellij-rust/intellij-rust/issues/1790#issuecomment-333066164)

### PR DESCRIPTION
**Pull request by Undin**
* Introduce arrays with unknown size
* ~~Implement rough array size expression calculation~~
* Use long for array size value

Fixes #1790

### CODE REVIEW

File: src/main/kotlin/org/rust/lang/core/psi/ext/RsArrayType.kt [hunk 1]
```diff
@@ -18,9 +17,42 @@ val RsArrayType.arraySize: Int? get() {
...
+
+private fun tryEvaluateExpr(expr: RsExpr?): Int? {
+    return when (expr) {
+        is RsLitExpr -> expr.integerLiteral
+            ?.text
+            ?.removeSuffix(TyInteger.Kind.usize.name)
+            ?.toIntOrNull()
+            ?.notNegativeOrNull()
+        is RsPathExpr -> {
+            val const = expr.path.reference.resolve() as? RsConstant ?: return null
```
Comment (Undin) [inline src/main/kotlin/org/rust/lang/core/psi/ext/RsArrayType.kt]: Call of `resolve` method leads to `IndexNotReadyException` because we save array size in stub and try to calculate it while indexing.
I suggest to drop array size filed from `RsArrayTypeStub` because it's more semantic then syntax part of language. And it'll allow to calculate array size expressions, of course:)

File: src/main/kotlin/org/rust/lang/core/psi/ext/RsArrayType.kt [hunk 2]
```diff
@@ -18,9 +17,42 @@ val RsArrayType.arraySize: Int? get() {
...
+            val integerType = const.typeReference?.type as? TyInteger ?: return null
```
Comment (Undin) [inline src/main/kotlin/org/rust/lang/core/psi/ext/RsArrayType.kt]: Maybe use `TyPrimitive.fromPath` directly instead of full type inference?

File: src/main/kotlin/org/rust/lang/core/psi/ext/RsArrayType.kt (hunk 1 above)
Comment (vlad20012) [reply src/main/kotlin/org/rust/lang/core/psi/ext/RsArrayType.kt]: Hmm, here we need to be very careful. We have an invariant that we looking only at a single file while indexing, so we can't resolve constants (because they can be defined in another files) during it. We need to looking deeply where the indexing need an array size... and is it really need it.

Also we don't want to falling back to AST while resolve (e.g. we resolved a function that return an array with constexpr size, and falled back to AST). Hmm...

And also maybe we want to save the size to stub only when it is trivial (the most case)

File: src/main/kotlin/org/rust/lang/core/psi/ext/RsArrayType.kt (hunk 2 above)
Comment (vlad20012) [reply src/main/kotlin/org/rust/lang/core/psi/ext/RsArrayType.kt]: Umm... maybe =D

File: src/main/kotlin/org/rust/lang/core/psi/ext/RsArrayType.kt (hunk 1 above)
Comment (vlad20012) [reply src/main/kotlin/org/rust/lang/core/psi/ext/RsArrayType.kt]: Also note that `RsConstant` element describes both `const` and `static`!

Comment (Undin) [reply src/main/kotlin/org/rust/lang/core/psi/ext/RsArrayType.kt]: > Hmm, here we need to be very careful. We have an invariant that we looking only at a single file while indexing, so we can't resolve constants during it (because they can be defined in another files).

Yes, I know about this restriction, that's why I've proposed to drop indexing of array size - it becomes useless because of necessity of complex computation.

> Also we don't want to falling back to AST during resolve (e.g. we resolved a function that return an array with constexpr size, and falled back to AST). Hmm...
>
>And also maybe we want to save the size to stub only when it is trivial (the most case)

I think it won't help - we still need to calculate value of integer literal expressions and while it we fall back to AST because we don't create stub for them.
To solve this problem I think we can create stub for literal expressions and save integer value in it. It'll help us not to fall back to AST during type inference but at same time index will contain **all** integers values not only part of array size expr.

Comment (Undin) [reply src/main/kotlin/org/rust/lang/core/psi/ext/RsArrayType.kt]: Although we can save values only for constants and array index expr

**Comment by vlad20012** [comment]
Umm, there is a some unresolved (or at least hard to solve) questions with constexpr evaluation, so maybe we can land a trivial part with unknown size first?

**Comment by Undin** [comment]
Ok, I'll make corresponding changes a bit later:)

**Comment by Undin** [comment]
Done

**Comment by Undin** [comment]
Done

File: src/main/kotlin/org/rust/lang/core/psi/ext/RsArrayType.kt [hunk 3]
```diff
@@ -10,17 +10,19 @@ import org.rust.lang.core.psi.RsExpr
...
 import org.rust.lang.core.types.ty.TyInteger
 
-val RsArrayType.arraySize: Int? get() {
+val RsArrayType.isSlice: Boolean get() = stub?.isSlice ?: (expr == null)
+
+val RsArrayType.arraySize: Long? get() {
     val stub = stub
     if (stub != null) {
-        return if (stub.arraySize == -1) null else stub.arraySize
+        return if (stub.arraySize == -1L) null else stub.arraySize
```
Comment (vlad20012) [inline src/main/kotlin/org/rust/lang/core/psi/ext/RsArrayType.kt]: Hmm, interestring. We can also use `-1` in TyArray too to avoid boxing...

**Comment by vlad20012** [comment]
bors r+

Thanks!

File: src/main/kotlin/org/rust/lang/core/types/ty/TyArray.kt [hunk 4]
```diff
@@ -10,9 +10,10 @@ import org.rust.lang.core.resolve.ImplLookup
 import org.rust.lang.core.types.infer.TypeFolder
 import org.rust.lang.core.types.infer.TypeVisitor
 
-class TyArray(val base: Ty, val size: Int) : Ty {
+class TyArray(val base: Ty, val size: Long?) : Ty {
     override fun unifyWith(other: Ty, lookup: ImplLookup): UnifyResult =
-        if (other is TyArray && size == other.size) base.unifyWith(other.base, lookup) else UnifyResult.fail
+        if (other is TyArray && (size == null || other.size == null || size == other.size))
+            base.unifyWith(other.base, lookup) else UnifyResult.fail
```
Comment (vlad20012) [inline src/main/kotlin/org/rust/lang/core/types/ty/TyArray.kt]: Usually when `if` is multiline we wrap it with `{ }`, but I want to merge it right now and `unifyWith` will be dropped soon :)
