### PR TITLE
INSP: remove spurious unreachable warnings for match exprs with no arms

### LINKED ISSUE #7670: Empty match is considered to be unreachable code
## Environment

* **IntelliJ Rust plugin version:** 0.4.151.3997-212
* **Rust toolchain version:** 1.54.0 (a178d0322 2021-07-26) x86_64-unknown-linux-gnu
* **IDE name and version:** IntelliJ IDEA 2021.2 Ultimate Edition (IU-212.4746.92)
* **Operating system:** Linux 5.13.5-051305-generic
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
An empty match statement is considered to be unreachable code, which seems like a bug.
image

## Steps to reproduce
```rust
enum Foo {
    Bar,
    Baz
}

fn foo(x: Foo) {
    <warning>match x {}</warning>
}
```

CC @ortem

### PR DESCRIPTION
**Pull request by afetisov**
We add a dummy CFG edge from the discriminant of the match to its output in this case, since adding a match arm with basically any return type would make the above CFG path possible. This avoids spurious "unreachable expr/stmt" warnings when the user types a new match block.

If the user adds at least one explicit arm, then the dataflow will be analysed properly (it's possible to add first a noreturn arm, while the other arms would be expected to return a value, but this is an easily understandable rare edge case which I don't think requires any special treatment).

The only case when a match with no arms is valid and indeed signifies unreachability is when the discriminant has the type with no values (e.g. ! or `enum Foo {}`), but this case can only be properly handled after type inference, not at the CFG level. It is also a very rare case which shouldn't cause problems for the common case of simply typing out the match expression.

Fixes #7670.

changelog: remove spurious "unreachable expression" warnings from match expressions with no arms

### CODE REVIEW

**Comment by afetisov** [comment]
@ortem Could you take a look please?

File: src/test/kotlin/org/rust/ide/inspections/lints/RsUnreachableCodeInspectionTest.kt [hunk 1]
```diff
@@ -229,4 +229,62 @@ class RsUnreachableCodeInspectionTest : RsInspectionsTestBase(RsUnreachableCodeI
...
+            let x = match 3 {
+
+            };
+            return;
+        }
+    """)
+
+    fun `test incomplete match stmt reachable`() = checkByText("""
+        fn main() {
+            match Some(true) {
```
Comment (ortem) [inline src/test/kotlin/org/rust/ide/inspections/lints/RsUnreachableCodeInspectionTest.kt:244]: Let's avoid using `Option` type (here and below) because it requires stdlib loading (see tests with `@ProjectDescriptor(WithStdlibRustProjectDescriptor::class)` annotations). It's convenient to use a local enum declaration like this:
```Rust
enum E { A, B }
fn foo(e: E) {
    match e {
        E::A => {}
    }
}
```

File: src/main/kotlin/org/rust/lang/core/dfa/CFGBuilder.kt [hunk 2]
```diff
@@ -603,7 +603,16 @@ class CFGBuilder(
 
         val prevGuards = ArrayDeque<CFGNode>()
 
-        matchExpr.arms.forEach { arm ->
+        val arms = matchExpr.arms
+        if (arms.isEmpty()) {
+            // The only case where a match with no arms is valid is when the discriminant is
+            // an empty type (!, empty enum etc), but the unreachability in this case is handled
```
Comment (ortem) [inline src/main/kotlin/org/rust/lang/core/dfa/CFGBuilder.kt:609]: Good point. Note, IJ Rust does not produce unreachability warnings during type inference (in contrast to rustc). Instead, `CFGBuilder` has access to the already inferred and resolved types for each expression and can construct CFG accordingly. 

Empty enums are quite synthetic objects, but it looks easy to handle them here. Probably something like this will work:
```Kotlin
val discriminantEnum = (matchExpr.expr?.type as? TyAdt)?.item as? RsEnumItem
if (discriminantEnum == null || discriminantEnum.variants.isNotEmpty()) {
    addContainedEdge(discriminantExit, exprExit)
}
```
However, special handling of `!` type is not necessary indeed since such expressions are already covered (see `is TyNever` checks in `CFGBuilder`).

File: src/main/kotlin/org/rust/lang/core/dfa/CFGBuilder.kt [hunk 3]
```diff
@@ -603,7 +603,16 @@ class CFGBuilder(
...
+            // by the type-based CFG analysis/
+            // In all other cases no match arms mean only that the user hasn't typed them yet, so
+            // we add a dummy edge to avoid breaking the CFG (otherwise everything after the match
+            // would be unreachable).
+            addContainedEdge(discriminantExit, exprExit)
+        } else arms.forEach { arm ->
```
Comment (ortem) [inline src/main/kotlin/org/rust/lang/core/dfa/CFGBuilder.kt:615]: [minor]: `else` might be removed to improve readability

**Review by ortem — CHANGES_REQUESTED** [review]
Thank you @afetisov! LGTM except for several comments.
Also, let's add tests to `RsControlFlowGraphTest`. The tests may look like this:
```Kotlin
fun `test empty match`() = testCFG("""
    fn main() {
        match 1 {};
        return;
    }
""", """
    Entry
    1
    MATCH
    MATCH;
    return
    Exit
    Termination
""")
```
Note, the second argument should be a valid depth-first traversal trace. To construct it, you may run the test with an empty second argument at first, and get the real trace from the thrown `ComparisonFailure` (please ensure that it looks correct).

**Comment by Kobzol** [comment]
I suppose that this should fix https://github.com/intellij-rust/intellij-rust/issues/7670?

**Comment by ortem** [comment]
@Kobzol Indeed, thank you! Added to the PR description

File: src/main/kotlin/org/rust/lang/core/dfa/CFGBuilder.kt (hunk 2 above)
Comment (afetisov) [reply src/main/kotlin/org/rust/lang/core/dfa/CFGBuilder.kt:609]: We shouldn't special-case empty enums here since this is not the only case where the type is uninhabited. Other examples include a struct were one of the fields is uninhabited, an array or slice of uninhabited types, or an enum where each variant is uninhabited (these are quite easy to get with generics). Ideally there should be some sort of `isInhabited` query which depends on an early pass checking the structure of all types, and the unreachability lint would check it. Currently nothing like this is available, so empty enums are unhandled. This is a minor problem, since they are indeed quite rare, and false negatives are a much smaller issue than false positives.

Examples  of empty enums which are currently relatively often used are `std::convert::Infallible`, `byteorder::BigEndian/LittleEndian`, or various compile-time tokens. In fact, a seach with regexp `enum \w+ \s*\{\s*\}` in my projects and libraries gives 218 results, including 51 in the stdlib, so while empty enums aren't particularly common, they also aren't that rare.

File: src/main/kotlin/org/rust/lang/core/dfa/CFGBuilder.kt (hunk 3 above)
Comment (afetisov) [reply src/main/kotlin/org/rust/lang/core/dfa/CFGBuilder.kt:615]: Indeed, `forEach` would be a no-op in this case, but imho the current variant is more readable since it's explicit in its special-casing of the empty list.

**Comment by afetisov** [comment]
Those traces look more like a postorder rather than depth-first traversal. E.g. in your example the match discriminant `1` is traversed before the `match` itself, and e.g. in this exmple

```kotlin
    fun `test loop`() = testCFG("""
        fn main() {
            loop {
                x += 1;
            }
            y;
        }
    """, """
        Entry
        Dummy
        x
        1
        x += 1
        x += 1;
        BLOCK
        Termination
    """)
```

the loop block is traversed after all its inner statements, and the subexpressions of an assignment are traversed before the assignment itself.

I suggest either changing the name of the function, or its implementation. I guess the name is wrong, since postorder is indeed the evaluation order of the program.

By the way, shouldn't it be LOOP rather than BLOCK in the example above?

I have found those traces to be very hard to read, since the pattern bindings are usually duplicated, and the structure is confusing. E.g. why is in this example

```kotlin
    fun `test if let else`() = testCFG("""
        fn foo() {
            if let Some(s) = x { 1 } else { 2 };
        }
    """, """
        Entry
        x
        s
        s
        Some(s)
        Dummy
        1
        BLOCK
        IF
        IF;
        BLOCK
        Exit
        Termination
        2
        BLOCK
    """)
```

the IF between two BLOCKs and before Exit and Termination? Is this example correct?

Postorder also discards much of the CFG structure. Shouldn't those tests be in something like DOT format?

**Comment by ortem** [comment]
@afetisov Thank you for your feedback regarding the current implementation. I strongly agree that the traces are hard to read, and we should probably consider replacing them with a DOT-like representation in the tests. In fact, we already have `org.rust.lang.utils.PresentableGraph#createDotDescription` method to generate such representation, so I think this idea fits the current implementation well enough. The pattern bindings are duplicated indeed because they correspond to both  `RsPatIdent` (parent) and `RsPatBinding` (child).

Regarding your questions about the graph traversal, below I provided some examples for the `test if let else` test to make it more clear.

This is the graph in DOT format, built with `org.rust.lang.core.dfa.CFGBuilder`:
```DOT
digraph {
    "0: Entry" -> "3: x";
    "3: x" -> "5: s";
    "5: s" -> "6: s";
    "6: s" -> "7: Some(s)";
    "7: Some(s)" -> "4: Dummy";
    "4: Dummy" -> "8: 1";
    "8: 1" -> "9: BLOCK";
    "3: x" -> "10: 2";
    "10: 2" -> "11: BLOCK";
    "9: BLOCK" -> "12: IF";
    "11: BLOCK" -> "12: IF";
    "12: IF" -> "13: IF;";
    "13: IF;" -> "14: BLOCK";
    "14: BLOCK" -> "1: Exit";
    "1: Exit" -> "2: Termination";
}
```

And the rendered version:


Note, the node `4: Dummy` is a supplementary node used for potential or-patterns in the condition. There are no or-patterns in this case, but the node is still here for consistency.

The expected trace, which effectively corresponds to deep-first (preorder) traversal of that graph:
```
Entry
x
s
s
Some(s)
Dummy
1
BLOCK
IF
IF;
BLOCK
Exit
Termination
2
BLOCK
```

Please let me know if I am missing something or if it is more clear now.

**Review by ortem — APPROVED** [review]
I think we can merge it right now, leaving the potential improvements for the future PRs. Looking forward to continuing the discussion in the comments. Thank you again @afetisov!

bors r+

**Comment by afetisov** [comment]
@ortem Thank you, my misunderstandings are cleared, and now I see that the terminology is indeed correct.

**Comment by ortem** [comment]
@afetisov I'm glad it helped! The control flow graph we use might seem unusual as it is basically built on the top of the syntax tree and don't operate with basic blocks. However, the trace in this graph is different from the trace in the original syntax tree, and using the "preorder"/"postorder" terminology is quite tricky without looking at real examples. I'll try to add some descriptive comments to the corresponding classes to make the implementation easier to understand. We will also consider replacing the traces with DOT descriptions in the tests, as I mentioned.
