### PR TITLE
COMP: fix IndexNotReadyException while completion

### LINKED ISSUE #5123: IndexNotReadyException
<details>
  <summary>Exception</summary>
  
```
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
	at com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:81)
	at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:706)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:656)
	at com.intellij.psi.stubs.StubIndexImpl.getContainingIds(StubIndexImpl.java:525)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:381)
	at com.intellij.psi.stubs.StubIndex.processElements(StubIndex.java:51)
	at org.rust.lang.core.stubs.index.RsIncludeMacroIndex$Companion$makeIndexLookup$1.compute(RsIncludeMacroIndex.kt:60)
	at org.rust.lang.core.stubs.index.RsIncludeMacroIndex$Companion$makeIndexLookup$1.compute(RsIncludeMacroIndex.kt:28)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:117)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:75)
	at org.rust.openapiext.UtilsKt.recursionGuard(utils.kt:67)
	at org.rust.openapiext.UtilsKt.recursionGuard$default(utils.kt:66)
	at org.rust.lang.core.stubs.index.RsIncludeMacroIndex$Companion.makeIndexLookup(RsIncludeMacroIndex.kt:56)
	at org.rust.lang.core.stubs.index.RsIncludeMacroIndex$Companion.getIncludingModInternal(RsIncludeMacroIndex.kt:51)
	at org.rust.lang.core.stubs.index.RsIncludeMacroIndex$Companion.access$getIncludingModInternal(RsIncludeMacroIndex.kt:28)
	at org.rust.lang.core.stubs.index.RsIncludeMacroIndex$Companion$getIncludingMod$1.compute(RsIncludeMacroIndex.kt:44)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:235)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:117)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:75)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:236)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:73)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:154)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:136)
	at org.rust.lang.core.stubs.index.RsIncludeMacroIndex$Companion.getIncludingMod(RsIncludeMacroIndex.kt:42)
	at org.rust.lang.core.macros.RsExpandedElement$Companion.getContextImpl(RsExpandedElement.kt:33)
	at org.rust.lang.core.macros.RsExpandedElement$Companion.getContextImpl$default(RsExpandedElement.kt:28)
	at org.rust.lang.core.psi.ext.RsImplItemImplMixin.getContext(RsImplItem.kt:67)
	at com.intellij.patterns.PsiElementPattern.getParent(PsiElementPattern.java:60)
	at com.intellij.patterns.PsiElementPattern$Capture.getParent(PsiElementPattern.java:399)
	at com.intellij.patterns.TreeElementPattern$5.processValues(TreeElementPattern.java:149)
	at com.intellij.patterns.PatternConditionPlus.accepts(PatternConditionPlus.java:42)
	at com.intellij.patterns.ObjectPattern.accepts(ObjectPattern.java:62)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:153)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:76)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:59)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:132)
	at com.intellij.codeInsight.completion.BaseCompletionService.performCompletion(BaseCompletionService.kt:30)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:826)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:811)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$null$6(CodeCompletionHandlerBase.java:335)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$tryReadOrCancel$5(CompletionThreading.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:170)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$7(CodeCompletionHandlerBase.java:327)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
</details>

## Environment

* **IntelliJ Rust plugin version:** 0.2.118.2157-201
* **Rust toolchain version:** 1.44.0-nightly (7ceebd98c 2020-03-17) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.1 EAP (CL-201.6251.14)
* **Operating system:** macOS 10.14.5

### PR DESCRIPTION
**Pull request by Undin**
There were two problems:
* completion psi patterns use `PsiElement#getContext` method. But our implementation of `getContext` uses indices sometimes that leads to `IndexNotReadyException` because keyword completion may be called in dumb mode. Now we make index lookup only in smart mode
* `await` keyword completion uses type inference, i.e. uses indices sometimes as well => it should be called only in smart mode. The corresponding completion provider was moved from keyword completion contributor to be invoked only in smart mode (CC @mchernyavsky)

Tests improvements:
* `RsKeywordCompletionContributorTest` now check completion in dumb mode
* usages of deprecated `checkSingleCompletion` in `RsKeywordCompletionContributorTest` were replaced with `checkCompletion`

Fixes #5123

### CODE REVIEW

File: src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt [hunk 1]
```diff
@@ -29,7 +30,7 @@ interface RsExpandedElement : RsElement {
             psi.project.macroExpansionManager.getContextOfMacroCallExpandedFrom(psi)?.let { return it }
             psi.getUserData(RS_EXPANSION_CONTEXT)?.let { return it }
             val parent = psi.stubParent
-            if (parent is RsFile && !isIndexAccessForbidden) {
+            if (parent is RsFile && !isIndexAccessForbidden && !DumbService.isDumb(psi.project)) {
```
Comment (vlad20012) [inline src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt:33]: Let's extract `psi.project` to a variable because it's used twice
