### PR TITLE
MACRO: support doc comments in macro calls

### LINKED ISSUE #3710: Macro with {pub mod} not recognized from outer scope
## Environment

* **Intellij-Rust plugin version: v0.2.96.2123-183**
* **Rust toolchain version: 1.34.0**
* **IDE name and version: CLion**
* **Operating system: Ubuntu**

Experimental engine for declarative macros enabled:
obrazek

## Problem description

[This macro usage](https://github.com/daboross/screeps-in-rust-via-wasm/blob/665a7b33936487108901ebe43ec1c0827801dab0/screeps-game-api/src/game.rs#L461-L489) will expand (using [this macro](https://github.com/daboross/screeps-in-rust-via-wasm/blob/665a7b33936487108901ebe43ec1c0827801dab0/screeps-game-api/src/macros.rs#L401-L434)) into the following:
```rust
// game.rs
pub mod spawns {
    ...
}
```
But the Rust plugin doesn't recognize the `spawns` module within the `game` module - example [here](https://github.com/daboross/screeps-starter-rust/blob/019fed609fa8b5cf57b15e3606908b62f59b91b3/src/main.rs#L48):
obrazek

Here the `spawns` isn't recognized by Rust plugin, but `rustc` compiles the program just fine.
Other modules are visible normally by the plugin.

<hr>

This is very annoying as there is neither completion, nor syntax highlighting when inside the for cycle above.

I can hack it so that the IDE knows the `values()` are of `Vec<objects::StructureSpawn>` type, but I think IDE should determine this by itself:
obrazek

## Steps to reproduce

```bash
cd /tmp
git clone https://github.com/daboross/screeps-starter-rust.git
cd screeps-starter-rust
git checkout 019fed609fa8b5cf57b15e3606908b62f59b91b3
cargo install cargo-screeps
cargo install cargo-web
clion . # and see the src/main.rs#48
```

## Related issues
#3383

### PR DESCRIPTION
**Pull request by vlad20012**
See tests

Fixes #3710

### CODE REVIEW

File: src/main/kotlin/org/rust/lang/core/parser/util.kt [hunk 1]
```diff
@@ -26,3 +26,9 @@ inline fun <T> PsiBuilder.probe(action: () -> T): T {
         mark.rollbackTo()
     }
 }
+
+fun PsiBuilder.rawLookupText(steps: Int): CharSequence {
```
Comment (vlad20012) [inline src/main/kotlin/org/rust/lang/core/parser/util.kt]: // copied from TOML plugin

**Comment by vlad20012** [comment]
I've rebased it to the master and took into account range mappings

**Comment by vlad20012** [comment]
bors retry
