### PR TITLE
RES: Don't search std/core crates in workspace in 2018 Edition

### LINKED ISSUE #2877: No autocomplete for std modules and types are highlighted in red
## Environment

* **Intellij-Rust plugin version: v0.2.0.2106-183/-v0.2.0.2106-183-nightly** 
* **Rust toolchain version: cargo 1.31.0-nightly (de314a8b2 2018-09-21) / rustc 1.30.0-nightly (887690686 2018-09-27)**
* **IDE name and version: CLion 2018.2/2018.3**
* **Operating system: OS X High Sierra**

## Problem description

There's no autocomplete for any module inside `std`. Also importing a module, e.g. `std::io::Error` highlights the error in the code in red. Didn't have such problems with the previous version of the plugin. Cargo builds the project fine and in the directory where my toolchain sources should be the files appear to be fine, I also just tried updating with rustup, no changes.

## Steps to reproduce

Just creating a new project within the CLion IDE with a simple hello world fn causes the problem for me:

```rust
use std::io::Error;

fn main() -> Result<(), Error> {
    println!("Hello, world!");
    Ok(())
}
```

https://cl.ly/6757255ff1ef

### PR DESCRIPTION
**Pull request by Undin**
Our implementation already processes std/core crates so with lookup into workspace
it leads to multiple resolution results and prevents from success resolution of all items in std/core crates

Fixes #2877

### CODE REVIEW

File: src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt [hunk 1]
```diff
@@ -7,10 +7,20 @@ package org.rust.lang.core.resolve
...
 import org.rust.WithStdlibRustProjectDescriptor
+import org.rust.cargo.project.model.cargoProjects
+import org.rust.cargo.project.workspace.CargoWorkspace
 import org.rust.lang.core.types.infer.TypeInferenceMarks
 
 @ProjectDescriptor(WithStdlibRustProjectDescriptor::class)
 class RsStdlibResolveTest : RsResolveTestBase() {
+
+    override fun runTest() {
+        for (edition in CargoWorkspace.Edition.values()) {
```
Comment (vlad20012) [inline src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt]: Looks like it isn't works for old rust toolchains

**Comment by Undin** [comment]
bors retry

**Comment by Undin** [comment]
bors r=vlad20012
