### PR TITLE
Support quick-fixes preview

### LINKED ISSUE #9561: Support "Intention preview"
## Environment

* **IntelliJ Rust plugin version:** 0.4.182.4945-222-nightly
* **Rust toolchain version:** 1.66.0-nightly (8ce3204af 2022-09-30) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2022.2.4 (CL-222.4345.21)
* **Operating system:** Linux 6.0.1-zen2-1-zen
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.cargo.emulate.terminal, org.rust.macros.proc

## Problem description
Intention preview will be [enabled by default in 2022.3](https://blog.jetbrains.com/idea/2022/09/intellij-idea-2022-3-eap/#Intention_action_preview_enabled_by_default), so it is worth to check our intentions and fix them if necessary. Currently we may show preview only for quick-fixes, for intentions there will be no preview because of [`RsElementBaseIntentionAction`](https://github.com/intellij-rust/intellij-rust/blob/8c9d70be685f25dfbd6031e37a18f30314478b54/src/main/kotlin/org/rust/ide/intentions/RsElementBaseIntentionAction.kt#L46) specifity. So the plan is:

* [x] Disable preview when it is not needed, e.g. intentions/quick-fixes which create new files and don't modify code #9562
* [x] Find quick-fixes with incorrect preview and fix them #9699
* [x] Fix `RsElementBaseIntentionAction` so that preview will be generated for intentions
* [x] Find intentions with incorrect preview and fix them #9641

Known problems:
* [x] `Create module file` #9560
* [x] `Rename to` #9450
* [x] `Expand dependency specification` (toml) #9431
* [x] `Add definition to trait` #9693

List of intentions/quick-fixes which currently don't have preview, but it can be added:

- [ ] `CreateFunctionIntention`, `CreateStructIntention`, `CreateTupleStructIntention`
- [ ] `AddImportForPatternIntention` when one candidate
- [ ] `AddImportIntention`
- [ ] `IntroduceLocalVariableIntention`
- [ ] `RenameFix`

### LINKED ISSUE #9693: `Add definition to trait` quick-fix throws `IncorrectOperationException`
## Environment

* **IntelliJ Rust plugin version:** 0.4.183.4994-223-nightly
* **Rust toolchain version:** 1.64.0 (a55dd71d5 2022-09-19) x86_64-apple-darwin
* **IDE name and version:** CLion 2022.3 EAP (CL-223.7401.10)
* **Operating system:** macOS 11.1
* **Macro expansion:** enabled

## Problem description
`AddDefinitionToTraitFix` introduced in #7134 tries to modify the PSI without using `WriteCommandAction`, which leads to the exception:
```
com.intellij.util.IncorrectOperationException: Must not change PSI outside command or undo-transparent action. See com.intellij.openapi.command.WriteCommandAction or com.intellij.openapi.command.CommandProcessor
	at com.intellij.pom.core.impl.PomModelImpl.startTransaction(PomModelImpl.java:270)
	at com.intellij.pom.core.impl.PomModelImpl.lambda$runTransaction$2(PomModelImpl.java:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:226)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:666)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:622)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$4(CoreProgressManager.java:234)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:234)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:225)
	at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:93)
	at com.intellij.psi.impl.source.tree.ChangeUtil.prepareAndRunChangeAction(ChangeUtil.java:142)
	at com.intellij.psi.impl.source.tree.CompositeElement.addChild(CompositeElement.java:579)
	at com.intellij.psi.impl.source.tree.CompositeElement.addChildren(CompositeElement.java:673)
	at com.intellij.psi.impl.source.codeStyle.CodeEditUtil.addChildren(CodeEditUtil.java:53)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.addInternal(ASTDelegatePsiElement.java:306)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.addAfter(ASTDelegatePsiElement.java:293)
	at org.rust.ide.inspections.fixes.AddDefinitionToTraitFix.invoke(AddDefinitionToTraitFix.kt:42)
        ...
```

## Steps to reproduce
```Rust
struct MyStruct;

trait MyTrait {
    fn foo() {}
}

impl MyTrait for MyStruct {
    fn foo() {}
    
    fn bar() {} // Invoke `Add definition to trait` quick-fix
}
```

### PR DESCRIPTION
**Pull request by dima74**
Meta: #9561
Fixes #9561
Fixes #9693

This mirrors #9641 for quick-fixes:
- added preview check to quick-fixes tests
- fixed tests for quick-fixes which are not expected to have a preview
- fixed quick-fixes which can have preview

changelog: Support [quick-fixes preview](https://blog.jetbrains.com/idea/2022/09/intellij-idea-2022-3-eap/#Intention_action_preview_enabled_by_default) in 2022.3

### CODE REVIEW

File: src/main/kotlin/org/rust/ide/annotator/fixes/ChangeReturnTypeFix.kt [hunk 1]
```diff
@@ -27,6 +28,7 @@ import org.rust.lang.core.types.ty.TyUnknown
 
 class ChangeReturnTypeFix(
     element: RsElement,
+    @SafeFieldForPreview
```
Comment (Undin) [inline src/main/kotlin/org/rust/ide/annotator/fixes/ChangeReturnTypeFix.kt:31]: Do I understand correctly that `Ty` type is safe even if it may reference a physical PSI just because it's a read only property?

File: src/test/kotlin/org/rust/ide/intentions/RsIntentionTestBase.kt [hunk 2]
```diff
@@ -98,11 +97,9 @@ abstract class RsIntentionTestBase(private val intentionClass: KClass<out Intent
         // Check preview only for intentions from Rust plugin
         if (intentionClass.isSubclassOf(RsElementBaseIntentionAction::class)) {
             if (previewExpected) {
-                checkPreviewAndLaunchAction(intention, preview)
+                checkPreviewAndLaunchAction(myFixture, intention, preview)
```
Comment (Undin) [inline src/test/kotlin/org/rust/ide/intentions/RsIntentionTestBase.kt:100]: Maybe convert it into an extension method of `CodeInsightTestFixture`? not to pollute namespace by top-level functions

File: src/test/kotlin/org/rust/ide/intentions/RsIntentionTestBase.kt [hunk 3]
```diff
@@ -98,11 +97,9 @@ abstract class RsIntentionTestBase(private val intentionClass: KClass<out Intent
...
             } else {
-                val intention = intention
-                val previewInfo = IntentionPreviewPopupUpdateProcessor.getPreviewInfo(project, intention, myFixture.file, myFixture.editor)
-                assertEquals(IntentionPreviewInfo.EMPTY, previewInfo)
+                checkNoPreview(myFixture, intention)
```
Comment (Undin) [inline src/test/kotlin/org/rust/ide/intentions/RsIntentionTestBase.kt:102]: The same suggestion about extension method

File: src/test/kotlin/org/rust/ide/inspections/lints/naming/RsVariableNamingInspectionTest.kt [hunk 4]
```diff
@@ -61,7 +61,7 @@ class RsVariableNamingInspectionTest : RsInspectionsTestBase(RsVariableNamingIns
             let (real, imaginary) = (7.2, 3.5);
             println!("{} + {}i", real, imaginary);
         }
-    """)
+    """, previewExpected = false)
```
Comment (Undin) [inline src/test/kotlin/org/rust/ide/inspections/lints/naming/RsVariableNamingInspectionTest.kt:64]: Are we going to make `RenameFix` work in preview?

File: src/test/kotlin/org/rust/ide/inspections/RsInspectionsTestBase.kt [hunk 5]
```diff
@@ -12,11 +12,17 @@ import org.rust.ide.annotator.RsAnnotationTestFixture
 import kotlin.reflect.KClass
 
 abstract class RsInspectionsTestBase(
-    protected val inspectionClass: KClass<out InspectionProfileEntry>
+    protected val inspectionClass: KClass<out InspectionProfileEntry>,
+    private val previewExpected: Boolean = true,
```
Comment (Undin) [inline src/test/kotlin/org/rust/ide/inspections/RsInspectionsTestBase.kt:16]: The same about `previewExpected` flag here

File: src/test/kotlin/org/rust/ide/annotator/fixes/ConvertToSizedTypeFixTest.kt [hunk 6]
```diff
@@ -51,6 +51,7 @@ class ConvertToSizedTypeFixTest : RsAnnotatorTestBase(RsErrorAnnotator::class) {
             checkWarn = true,
             checkInfo = false,
             checkWeakWarn = false,
+            previewExpected = true,
```
Comment (Undin) [inline src/test/kotlin/org/rust/ide/annotator/fixes/ConvertToSizedTypeFixTest.kt:54]: Why?

File: src/main/kotlin/org/rust/openapiext/utils.kt [hunk 7]
```diff
@@ -176,7 +176,7 @@ val VirtualFile.document: Document?
     get() = FileDocumentManager.getInstance().getDocument(this)
 
 val PsiFile.document: Document?
-    get() = PsiDocumentManager.getInstance(project).getDocument(this)
+    get() = viewProvider.document
```
Comment (Undin) [inline src/main/kotlin/org/rust/openapiext/utils.kt:179]: What does `PsiDocumentManager.getInstance(project).getDocument(this)` return in the case of non physical copy of `PsiFile`?

File: src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt [hunk 8]
```diff
@@ -332,3 +332,20 @@ fun PsiElement.isKeywordLike(): Boolean {
...
+ * Thus, we should call this function on `resolve` result to obtain element in the copy of the original file.
+ */
+fun <T: PsiElement> T.findPreviewCopy(startElement: PsiElement): T? {
+    if (!startElement.isIntentionPreviewElement) return this
+    val copyFile = startElement.containingFile
+    return when (containingFile) {
+        copyFile -> this
+        copyFile.originalFile -> PsiTreeUtil.findSameElementInCopy(this, copyFile)
+        // TODO this is incorrect, intention will fail with "Must not change PSI outside write action"
+        else -> this
```
Comment (Undin) [inline src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt:349]: What if we just return `null` here?

File: src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt [hunk 9]
```diff
@@ -332,3 +332,20 @@ fun PsiElement.isKeywordLike(): Boolean {
...
     }
 }
+
+/**
+ * Consider we do some `resolve` in a quick-fix which is called in preview mode.
+ * Quick-fix is called on copy of the original file, but `resolve` will return original element.
+ * We will have an exception if we try to modify the original element.
+ * Thus, we should call this function on `resolve` result to obtain element in the copy of the original file.
+ */
+fun <T: PsiElement> T.findPreviewCopy(startElement: PsiElement): T? {
```
Comment (Undin) [inline src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt:342]: Maybe
```suggestion
fun <T: PsiElement> T.findPreviewCopyIfNeeded(startElement: PsiElement): T? {
```
?

Actually, we don't do anything for elements outside of preview

Comment (Undin) [inline src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt:342]: What do you think about passing `copyFile` directly instead of `startElement`? Currently, it's not easy to understand what `startElement` is since you use it only to get its `containingFile`. At the same time, in some cases you already have a copy file, for example, in `com.intellij.codeInspection.LocalQuickFixAndIntentionActionOnPsiElement#invoke(com.intellij.openapi.project.Project, com.intellij.psi.PsiFile, com.intellij.openapi.editor.Editor, com.intellij.psi.PsiElement, com.intellij.psi.PsiElement)`

File: src/main/kotlin/org/rust/ide/inspections/fixes/RenameFix.kt [hunk 10]
```diff
@@ -34,4 +36,7 @@ class RenameFix(
         }, {
             RefactoringFactory.getInstance(project).createRename(it, newName).run()
         })
+
+    override fun generatePreview(project: Project, previewDescriptor: ProblemDescriptor): IntentionPreviewInfo =
```
Comment (Undin) [inline src/main/kotlin/org/rust/ide/inspections/fixes/RenameFix.kt:40]: It would be nice to support preview here eventually, at least for local changes like variable renaming

File: src/main/kotlin/org/rust/ide/inspections/fixes/QualifyPathFix.kt [hunk 11]
```diff
@@ -33,4 +37,11 @@ class QualifyPathFix(
         importInfo.insertExternCrateIfNeeded(path)
         path.replace(newPath)
     }
+
+    override fun generatePreview(project: Project, previewDescriptor: ProblemDescriptor): IntentionPreviewInfo {
+        if (importInfo is ImportInfo.ExternCrateImportInfo && importInfo.needInsertExternCrateItem) {
+            return IntentionPreviewInfo.EMPTY
+        }
```
Comment (Undin) [inline src/main/kotlin/org/rust/ide/inspections/fixes/QualifyPathFix.kt:44]: Is it really important? We decided that it's not so important to show imports. Extern crate item looks similar

File: src/main/kotlin/org/rust/ide/inspections/fixes/AddMainFnFix.kt [hunk 12]
```diff
@@ -23,8 +22,7 @@ class AddMainFnFix(file: PsiElement) : LocalQuickFixAndIntentionActionOnPsiEleme
 
     override fun invoke(project: Project, file: PsiFile, editor: Editor?, startElement: PsiElement, endElement: PsiElement) {
         val function = file.add(RsPsiFactory(project).createFunction("fn main() { }")) as RsFunction
-        if (editor == null) return
         val offset = function.block?.lbrace?.textOffset ?: return
-        PsiNavigationSupport.getInstance().createNavigatable(project, file.virtualFile, offset + 1).navigate(true)
+        editor?.caretModel?.moveToOffset(offset + 1)
```
Comment (Undin) [inline src/main/kotlin/org/rust/ide/inspections/fixes/AddMainFnFix.kt:26]: Hm, interesting. Why didn't we do the same at the beginning? 🤔

File: src/main/kotlin/org/rust/ide/annotator/fixes/ChangeReturnTypeFix.kt (hunk 1 above)
Comment (dima74) [reply src/main/kotlin/org/rust/ide/annotator/fixes/ChangeReturnTypeFix.kt:31]: Yes, because we don't modify that physical PSI and use it to generate some `String`

File: src/test/kotlin/org/rust/ide/inspections/lints/naming/RsVariableNamingInspectionTest.kt (hunk 4 above)
Comment (dima74) [reply src/test/kotlin/org/rust/ide/inspections/lints/naming/RsVariableNamingInspectionTest.kt]: It is possible in future PRs, `RenameFix` is listed in corresponding section in #9561

File: src/test/kotlin/org/rust/ide/annotator/fixes/ConvertToSizedTypeFixTest.kt (hunk 6 above)
Comment (dima74) [reply src/test/kotlin/org/rust/ide/annotator/fixes/ConvertToSizedTypeFixTest.kt]: I refactored `ConvertToSizedTypeFixTest` so now default value parameter from super method will be used

File: src/main/kotlin/org/rust/openapiext/utils.kt (hunk 7 above)
Comment (dima74) [reply src/main/kotlin/org/rust/openapiext/utils.kt:179]: It returns `null`. New approach is recommended by [Inspection preview guidelines](https://docs.google.com/document/d/1o-aRu8p_gemOl6O0CuWplsP3lJ2T4gS5zVQ9-cTrXz4/edit#heading=h.t6xf05a5xa09) (point `3e`)

File: src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt (hunk 8 above)
Comment (dima74) [reply src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt:348]: It depends on when `findPreviewCopyIfNeeded` is used. If it is used at the beginning of the quick-fix, the preview will be empty. If it used somewhere in the middle we may end up in partial preview generated

File: src/main/kotlin/org/rust/ide/inspections/fixes/RenameFix.kt (hunk 10 above)
Comment (dima74) [reply src/main/kotlin/org/rust/ide/inspections/fixes/RenameFix.kt:40]: https://github.com/intellij-rust/intellij-rust/pull/9699#discussion_r1018439359

File: src/main/kotlin/org/rust/ide/inspections/fixes/AddMainFnFix.kt (hunk 12 above)
Comment (dima74) [reply src/main/kotlin/org/rust/ide/inspections/fixes/AddMainFnFix.kt:26]: If I understand correctly, `PsiNavigationSupport` is for cases when file is not opened in the editor (and it will open it), for our cases when file is already opened, we can use `editor.caretModel`
