### PR TITLE
INT: Support async function by create function intention

### LINKED ISSUE #6712: Create function intention should create async function if necessary
## Environment

* **IntelliJ Rust plugin version:** 0.3.139.3615-203
* **Rust toolchain version:** 1.51.0-nightly (4253153db 2021-01-17) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2020.3.1 (CL-203.6682.181)
* **Operating system:** Linux 5.10.9-arch1-1
* **Macro expansion engine:** new
* **Name resolution engine:** old

## Problem description
"Create function intention" should create async function if we call `.await` directly on function call result:

Peek 2021-01-24 18-26

## Steps to reproduce
```rust
async fn foo() {
    /*cursor*/bar().await;
}
```

### PR DESCRIPTION
**Pull request by Stzx**
Fixed #6712

### CODE REVIEW

File: src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt [hunk 1]
```diff
@@ -37,16 +38,25 @@ class CreateFunctionIntention : RsElementBaseIntentionAction<CreateFunctionInten
...
 
-        open class Function(val callExpr: RsCallExpr, name: String, val module: RsMod) : Context(name, callExpr) {
+        open class Function(callExpr: RsCallExpr, name: String, val module: RsMod) : Context(name, callExpr) {
             override val visibility: String = when {
                 callExpr.containingCrate != module.containingCrate -> "pub "
                 callExpr.containingMod != module -> "pub(crate) "
                 else -> ""
             }
+            override val isAsync: Boolean = super.isAsync
+                && callExpr.parentOfType<RsDotExpr>()?.fieldLookup?.isAsync == true
```
Comment (Kobzol) [inline src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt:59]: This check should be more precise, to only check the direct parent.
Otherwise e.g. this:
```rust
async fn foo() {
    baz(/*caret*/bar()).await;
}
async fn baz(a: u32) {}
```
will produce
```rust
async fn foo() {
    baz(bar()).await;
}
async fn bar() -> u32 {
    unimplemented!()
}
async fn baz(a: u32) {}
```
Which is probably not what the user wanted.

**Review by Kobzol — CHANGES_REQUESTED** [review]

File: src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt [hunk 2]
```diff
@@ -73,6 +83,8 @@ class CreateFunctionIntention : RsElementBaseIntentionAction<CreateFunctionInten
                         else -> "pub(crate)"
                     }
                 }
+            override val isAsync: Boolean = super.isAsync
+                && methodCall.parentDotExpr.parentOfType<RsDotExpr>()?.fieldLookup?.isAsync == true
```
Comment (Kobzol) [inline src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt:87]: Same things applies to methods:
```rust
struct S;

async fn foo(s: S) {
    baz(s./*caret*/bar()).await;
}
async fn baz(a: u32) {}
```

**Review by Kobzol — CHANGES_REQUESTED** [review]

File: src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt (hunk 2 above)
Comment (Stzx) [reply src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt:87]: Sorry, I forgot this.

**Comment by Stzx** [comment]
@Kobzol This is a question:
```rust
struct S;

impl S {
    async fn foo(&self) {
        self.foz(self./*caret*/bar(1, 2).await);
    }

    fn foz(&self, p0: u32) {
        unimplemented!()
    }
}
```
Actual:
```rust
struct S;

impl S {
    async fn foo(&self) {
        self.foz(self.bar(1, 2).await);
    }

    fn foz(&self, p0: u32) {
        unimplemented!()
    }

    async fn bar(&self, p0: u32, p1: u32) {
        unimplemented!()
    }
}
```

**Comment by Kobzol** [comment]
Hmm, maybe it could ask for the expected type of the parent `await` if it is present, but I think that it's okay.

**Review by Kobzol — APPROVED** [review]

File: src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt [hunk 3]
```diff
@@ -37,16 +38,25 @@ class CreateFunctionIntention : RsElementBaseIntentionAction<CreateFunctionInten
 
     sealed class Context(val name: String, val callElement: PsiElement) {
         abstract val visibility: String
+        open val isAsync: Boolean = callElement.parentsOfType<RsBlock>().firstOrNull().let { block ->
```
Comment (dima74) [inline src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt:41]: Do we really want to check if containing function is `async`? Code like this:
```rust
fn foo() {
    bar().await;
}
```
is invalid, but if user already has `await`, maybe user also will make function `foo` be `async` later?

Comment (Kobzol) [reply src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt:41]: FWIW I was thinking the same, but I didn't feel strongly either way. If there is no check for async, there should probably at least be a check for edition 2018.

Comment (Stzx) [reply src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt:41]: Well, let me modify it to only detect edition 2018.

**Review by dima74 — APPROVED** [review]
Thanks!
bors r+
