### PR TITLE
INSP: Use kotlin-semver to avoid false-positives in version comparison & enable version inspections

### LINKED ISSUE #7600: False-positive `Invalid version requirement` warning in Cargo.toml
## Environment

* **IntelliJ Rust plugin version:** 0.4.153.4014-212-nightly
* **Rust toolchain version:** 1.53.0 (53cb7b09b 2021-06-17) x86_64-apple-darwin
* **IDE name and version:** CLion 2021.3 EAP (CL-213.1557)
* **Operating system:** macOS 11.2.3
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
`CrateVersionInvalidInspection` produces a false-positive warning on a version requirement with `-`, like `"0.4.0-2"`.

## Steps to reproduce
`Cargo.toml`
```Toml
[dependencies]
libbpf-sys = { version = "0.4.0-2" }
```
`Invalid version requirement 0.4.0-2` warning is shown, but the version requirement is actually [correct](https://crates.io/crates/libbpf-sys/versions).

### PR DESCRIPTION
**Pull request by avrong**
This PR replaces `semver4j` with [kotlin-semver](https://github.com/z4kn4fein/kotlin-semver) lib as a more appropriate variant that solves the problems we've had with pre-release sections parsing as we were converting versions into npm ones.

In fact, the replacement fixes #7600, and provides correct order for pre-release versions in completion. So, it also enables version-related inspections by default

Closes #7600
Related to #6463

changelog: Handle correctly pre-release dependencies' versions parsing and enable `Invalid crate version` and `New crate version availaible` inspections for `Cargo.toml` by default

### CODE REVIEW

File: toml/src/test/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyVersionCompletionTest.kt [hunk 1]
```diff
@@ -28,13 +28,31 @@ class LocalCargoTomlDependencyVersionCompletionTest : LocalCargoTomlCompletionTe
...
         "foo" to CargoRegistryCrate.of("0.1.4", "0.4.3", "0.3.0", "0.1.1", "0.4.0", "0.3.5", "0.4.0-rc.1", "0.1.0", "0.4.2", "0.3.3", "0.3.4", "0.2.0", "0.1.3", "0.2.5", "0.3.8", "0.2.6", "0.4.6", "0.1.5", "0.2.11", "0.2.2", "0.4.5", "0.2.1", "0.3.1", "0.3.16", "0.3.6", "0.2.10", "0.4.4", "0.3.12", "0.2.9", "0.3.10", "0.1.6", "0.3.14", "0.2.4", "0.3.2", "0.1.2", "0.3.17", "0.3.9", "0.4.0-rc.2", "0.4.1", "0.3.15", "0.3.7", "0.4.0-rc", "0.2.7", "0.2.3", "0.4.7", "0.3.11", "0.2.8", "0.3.13"),
     )
 
+    fun `test complete sorted order minor, major and patch sections`() = completeBasic("""
+        [dependencies]
+        foo = "<caret>"
+    """,
+        // source: semver spec (https://semver.org/)
+        listOf("2.1.1", "2.1.0", "2.0.0", "1.0.0"),
+        "foo" to CargoRegistryCrate.of("1.0.0", "2.1.0", "2.1.1", "2.0.0")
```
Comment (Kobzol) [inline toml/src/test/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyVersionCompletionTest.kt:44]: This order seems weird, right? From `semver.org`:

```
Precedence is determined by the first difference when comparing each of these identifiers from left to right as follows: Major, minor, and patch versions are always compared numerically.

Example: 1.0.0 < 2.0.0 < 2.1.0 < 2.1.1.
```

**Review by Kobzol — COMMENTED** [review]
Nice! There were some problems with `semver4j` before, I remember these two ones:
```
1.2.*
Cargo does not accept 1.3.0
Semver4J accepts 1.3.0

>=1.2
Cargo does not accept 1.1.2
Semver4J accepts 1.1.2
```
Are these solved with the new library? Also, did you try if we can remove some of the version normalizing hacks?

File: toml/src/test/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyVersionCompletionTest.kt (hunk 1 above)
Comment (Kobzol) [reply toml/src/test/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyVersionCompletionTest.kt:44]: Oh, sorry, that's my bad, I was looking at the bottom row instead of the top row. This ordering is fine.

**Comment by avrong** [comment]
@Kobzol sorry for a long response, finally did try your examples with the new library

```
import io.github.z4kn4fein.semver.constraints.toConstraint
 
"1.2.*".toConstraint()
res0: io.github.z4kn4fein.semver.constraints.Constraint = >=1.2.0 <1.3.0-0

">=1.2".toConstraint()
res1: io.github.z4kn4fein.semver.constraints.Constraint = >=1.2.0
```

It seems to me that it's fine now. Regarding the changes for normalizing, I remember that I was removing some and tested with and without them

**Comment by avrong** [comment]
@Undin I think we did such behaviour from the start as we parse full string, so the error matches the whole, although maybe it would be better to highlight only insides of a string literal. I don't see much of a difference as we are not decoupling string and highlighting parts of it with a mistake anyway

**Review by Undin — APPROVED** [review]
> @Undin I think we did such behaviour from the start as we parse full string, so the error matches the whole, although maybe it would be better to highlight only insides of a string literal. I don't see much of a difference as we are not decoupling string and highlighting parts of it with a mistake anyway

I asked because the similar gradle inspection doesn't highlight quotes. Probably, we want to use similar approaches across all technologies

image

But it doesn't affect the main result of inspections and can be changed in separate PR

bors r+

**Comment by neonaot** [comment]
Hi! 
I have found a couple of problems:
1. For the dependencies with versions `older than ...` an inspection `A newer version is available` appears. 
image.
1. There is no way to suppress this inspection for one line only.  
Usecase:
`rand = "0.7.2"`
Now if the user does not want to upgrade to `0.8.x` and doesn't want to see the inspection, they have to write `rand = "=0.7.2"` (But there is no such quick fix)
But if the user wants to use the latest `0.7.x`, they have no way to suppress this inspection.
