### PR TITLE
QDOC: fix doc urls for proc macros

### LINKED ISSUE #9353: Incorrect doc link for derive macros
## Environment

* **IntelliJ Rust plugin version:** 0.4.179.4874-222-nightly
* **Rust toolchain version:** 1.63.0 (4b91a6ea7 2022-08-08) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2022.2.2 (CL-222.4167.25)
* **Operating system:** Linux 5.4.0-125-generic
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description

The quick doc link generator doesn't recognize derive macros, instead treating them as ordinary functions and producing wrong links. It also mangles capitalization of identifiers, at least in that case.

## Steps to reproduce

```toml
# Cargo.toml
[package]
name = "foo"
version = "0.1.0"
edition = "2021"
[dependencies]
clap = { version = "3.2.21", features = ["derive"] }
```

```rust
// main.rs
use clap::Parser;

#[derive(/*caret*/Parser)]
struct Args {}

fn main() {}
```

Open Quick Documentation. At the bottom click on `'parser' on docs.rs`. The opened link is https://docs.rs/clap_derive/3.2.18/clap_derive/fn.parser.html , which doesn't have the doc page. The correct link should be https://docs.rs/clap_derive/3.2.18/clap_derive/derive.Parser.html . Note `derive` instead of `fn` and capitalization of `Parser`.

### PR DESCRIPTION
**Pull request by afetisov**
Closes #9353

changelog: fix docs.rs documentation hyperlinks for proc macros

### CODE REVIEW

**Comment by afetisov** [comment]
@mchernyavsky Could you take a look at this?

File: src/main/kotlin/org/rust/lang/core/psi/ext/RsQualifiedNamedElement.kt [hunk 1]
```diff
@@ -356,29 +356,37 @@ data class RsQualifiedName private constructor(
...
                 is RsTraitItem -> TRAIT
                 is RsTraitAlias -> TRAITALIAS
                 is RsTypeAlias -> TYPE
-                is RsFunction -> FN
+                is RsFunction -> when {
+                    isCustomDeriveProcMacroDef -> DERIVE
+                    isAttributeProcMacroDef -> ATTR
+                    isBangProcMacroDef -> MACRO
+                    else -> FN
+                }
```
Comment (dima74) [inline src/main/kotlin/org/rust/lang/core/psi/ext/RsQualifiedNamedElement.kt:381]: Lets optimize fast path a bit

```suggestion
                is RsFunction -> when {
                    !isProcMacroDef -> FN
                    isCustomDeriveProcMacroDef -> DERIVE
                    isAttributeProcMacroDef -> ATTR
                    isBangProcMacroDef -> MACRO
                    else -> return null
                }
```

File: src/main/kotlin/org/rust/lang/core/psi/ext/RsQualifiedNamedElement.kt [hunk 2]
```diff
@@ -356,29 +356,37 @@ data class RsQualifiedName private constructor(
         }
 
         private fun RsQualifiedNamedElement.toParentItem(): Item? {
-            val name = ((this as? RsMod)?.modName ?: name) ?: return null
+            val name = when {
+                this is RsFunction && isProcMacroDef -> procMacroName
+                this is RsMod && isCrateRoot -> containingCrate?.normName
+                this is RsMod -> modName
+                else -> name
+            } ?: return null
```
Comment (dima74) [inline src/main/kotlin/org/rust/lang/core/psi/ext/RsQualifiedNamedElement.kt:364]: I would suggest move `name` declaration after `itemType` so that we don't calculate `isProcMacroDef` and `isCrateRoot` twice

```suggestion
            val name = when (itemType) {
                DERIVE -> (this as? RsFunction)?.procMacroName
                CRATE -> containingCrate?.normName
                MOD -> (this as? RsMod)?.modName
                else -> name
            } ?: return null
```

**Comment by dima74** [comment]
Also would be nice to add tests to `RsResolveLinkTest`, like
```kotlin
    fun `test proc macro fqn link`() = doTest("""
        #[proc_macro_attribute]
        pub fn foo(_attr: TokenStream, item: TokenStream) -> TokenStream {
             //X
            item
        }

        struct Bar;
              //^
    """, "test_package/macro.foo.html")
```

**Comment by dima74** [comment]
I rebased on #9068 and applied comments I suggested
@mchernyavsky could you please review?

**Review by mchernyavsky — APPROVED** [review]
👍

bors r+

**Comment by dima74** [comment]
bors retry
