### PR TITLE
Properly change state of optional dependencies in Cargo toml

### LINKED ISSUE #6828: Switching optional dependencies
## Environment

* **IntelliJ Rust plugin version:** 0.3.140.3644-203
* **Rust toolchain version:** stable-x86_64-apple-darwin (rustc 1.49.0 (e1884a8e3 2020-12-29))
* **IDE name and version:** GoLand 2020.3
* **Operating system:** MacOS 11.2

## Problem description
I used to have ability to switch optional dependencies (turn them on/off). Whether optional dependency is turned on/off affects on conditional compilation and hints from IDE. Since the last release I'm able to switch features, but not optional dependencies.

## Steps to reproduce

https://user-images.githubusercontent.com/14890036/107629817-3f213580-6c95-11eb-853f-f60112429029.mov

### PR DESCRIPTION
**Pull request by Undin**
The bug was introduced in #6623.

Also, these changes introduce `LineMarkerTestHelper` to avoid code duplication related to line marker tests

Fixes #6828

### CODE REVIEW

File: toml/src/test/kotlin/org/rust/toml/CargoFeatureLineMarkerProviderTest.kt [hunk 1]
```diff
@@ -5,15 +5,96 @@
...
+        name = "intellij-rust-test"
+        version = "0.1.0"
+        authors = []
+
+        [dependencies.foo] # - Toggle feature `foo`
+        path = "foo"
+        optional = true
+    """)
+
+    fun `test optional dependency inline table`() = doTest("foo","""
```
Comment (vlad20012) [inline toml/src/test/kotlin/org/rust/toml/CargoFeatureLineMarkerProviderTest.kt:54]:
```suggestion
    fun `test optional dependency inline table`() = doTest("foo", """
```

**Review by vlad20012 — APPROVED** [review]

**Comment by Undin** [comment]
bors r=vlad20012
