### PR TITLE
TY&RES: support const arguments that looks like type arguments

### LINKED ISSUE #7420: Incorrect constraints on const generic parameters
## Environment

* **IntelliJ Rust plugin version:** 0.4.149.3939-211
* **Rust toolchain version:** 1.53.0 (53cb7b09b 2021-06-17) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2021.1.2 (CL-211.7442.42)
* **Operating system:** Linux 5.4.0-74-generic
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

The constraints on const generic parameters are incorrectly inferred when only some of the parameters are generic.

## Steps to reproduce

The code:

```rust
struct Foo<const N: u8, const S: bool>(u32);

impl<const N: u8> From<u32> for Foo<N, true> {
                                    // ^^^^ error
    fn from(val: u32) -> Self { Foo(val) }
}
```

_Error_: mismatched types [E0308] expected `u8`, found `bool` .

The constraint applied to `S` is always that of the preceding type. For example: 

```rust
struct Foo<const N: usize, const S: u32>(u32);

impl<const N: usize> From<u32> for Foo<N, 1u32> {
                                       // ^^^^ error
    fn from(val: u32) -> Self { Foo(val) }
}

fn foo<const N: usize>() -> Foo<N, 1u32> {
                                // ^^^^ error
    Foo(0)
}
```

_Error_: mismatched types [E0308] expected `usize`, found `u32`.

No error occurs if an impl block has either no or all specified generic parameters. E.g.:

```rust
impl<const N: usize, const S: u32> From<bool> for Foo<N, S> {
    fn from(_: bool) -> Self {
        Foo(0)
    }
}
```

_No error_.

```rust
impl From<bool> for Foo<0usize, 1u32> {
    fn from(_: bool) -> Self {
        Foo(0)
    }
}
```

_No error_.

# Extra error

The following error is probably related:

```rust
struct Foo<const N: usize, const S: u32>(u32);
fn foo<const S: u32>() -> Foo<1usize, S> {
                                   // ^ error
    Foo(0)
}
```

_Error_: Type arguments must be declared prior to const arguments.

### PR DESCRIPTION
**Pull request by vlad20012**
Related to #3985, fixes (partially, except `Extra error` case) #7420

### CODE REVIEW

File: src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt [hunk 1]
```diff
@@ -185,50 +206,32 @@ fun <T : RsElement> instantiatePathGenerics(
...
-    }
-
     val parent = path.parent
 
     // Generic arguments are optional in expression context, e.g.
     // `let a = Foo::<u8>::bar::<u16>();` can be written as `let a = Foo::bar();`
     // if it is possible to infer `u8` and `u16` during type inference
     val areOptionalArgs = parent is RsExpr || parent is RsPath && parent.parent is RsExpr
 
+    val regionParameters = resolved.lifetimeParameters
```
Comment (Kobzol) [inline src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt:216]: This can also be slightly refactored (unified), not sure if it's worth it though https://github.com/intellij-rust/intellij-rust/pull/7532/files#diff-d5ef21f531e13f82d4a5cf3fa47e81a4decada1cb0dd8b68933509ac4380bce9R261.

Comment (vlad20012) [reply src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt:215]: Looks cool, thanks!

**Review by mchernyavsky — APPROVED** [review]
bors r+

**Comment by mchernyavsky** [comment]
TODO:  Fix `RsPath.typeArguments`, `RsPath.constArguments`, `RsMethodCall.typeArguments` `RsMethodCall.constArguments` and corresponding inspections
