### PR TITLE
(EDT): check offset validity

### LINKED ISSUE #680: Exception in an empty document
The exception is thrown if press "Enter" in an empty document.

WebStorm 2016.2.3
Build #WS-162.1812.21, built on September 4, 2016
Rust plugin: 0.1.0.1011-nightly 
```
Wrong index: 0
java.lang.IndexOutOfBoundsException: Wrong index: 0
	at com.intellij.openapi.editor.ex.util.SegmentArrayWithData.getSegmentData(SegmentArrayWithData.java:103)
	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter$HighlighterIteratorImpl.getTokenType(LexerEditorHighlighter.java:472)
	at org.rust.ide.typing.RustQuoteHandler.isInsideLiteral(RustQuoteHandler.kt:40)
	at org.rust.ide.typing.RustQuoteHandler.isDeepInsideLiteral(RustQuoteHandler.kt:51)
	at org.rust.ide.typing.RustEnterInStringLiteralHandler.preprocessEnter(RustEnterInStringLiteralHandler.kt:35)
	at com.intellij.codeInsight.editorActions.EnterHandler.b(EnterHandler.java:126)
	at com.intellij.codeInsight.editorActions.EnterHandler.a(EnterHandler.java:79)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.a(PostprocessReformattingAspect.java:113)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:121)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:112)
	at com.intellij.codeInsight.editorActions.EnterHandler.executeWriteAction(EnterHandler.java:78)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:57)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:906)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:70)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:222)
	at com.intellij.codeInsight.template.impl.editorActions.EnterHandler.executeWriteAction(EnterHandler.java:49)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:57)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:906)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:70)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$3$1.perform(EditorActionHandler.java:206)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.access$000(EditorActionHandler.java:38)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$3.perform(EditorActionHandler.java:203)
	at com.intellij.openapi.editor.impl.CaretModelImpl.a(CaretModelImpl.java:348)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:437)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:340)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:331)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:200)
	at com.intellij.openapi.editor.actionSystem.EditorAction.lambda$actionPerformed$0(EditorAction.java:100)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:129)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:88)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:213)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:199)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.f(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:643)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

### PR DESCRIPTION
**Pull request by mkaput**
It's important to remember that `HighlighterIterator#getTokenType()` for empty document throws IndexOutOfBounds exception.

fix #680

### CODE REVIEW

**Comment by matklad** [comment]
Thanks!

File: src/main/kotlin/org/rust/ide/typing/RustEnterInStringLiteralHandler.kt [hunk 1]
```diff
@@ -59,4 +60,8 @@ class RustEnterInStringLiteralHandler : EnterHandlerDelegateAdapter() {
             else -> Result.Continue
         }
     }
+
+    private fun isValidOffset(offset: Int, text: CharSequence): Boolean {
+        return offset >= 0 && offset < text.length
```
Comment (matklad) [inline src/main/kotlin/org/rust/ide/typing/RustEnterInStringLiteralHandler.kt]: I like to write similar comparisons as `0 <= offset && offset < text.lenght`, because that way `<` are aligned with the usual direction on the number line. Have I already said this before?

Comment (mkaput) [inline src/main/kotlin/org/rust/ide/typing/RustEnterInStringLiteralHandler.kt]: Nope, but I have just blindly copy-pasted this from IntelliJ's source (I agree with your opinion) :P I'm working on #673 and already did some refactoring of this there
