### PR TITLE
INT: Fix omitting parens in DemorgansLawIntention

### LINKED ISSUE #8014: Demorgan intention may incorrectly omit parens
## Environment

* **IntelliJ Rust plugin version:** 0.4.159.4199-212-nightly
* **Rust toolchain version:** 1.55.0 (c8dfcfe04 2021-09-06) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2021.2.3 (CL-212.5457.51)
* **Operating system:** Linux 5.14.14-zen1-1-zen
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Steps to reproduce
```rust
fn func() -> bool {
    a && !(b /*caret*/&& c)
}
```

Expected after applying Demorgan intention:
```rust
fn func() -> bool {
    a && (!b || !c)
}
```

Actual:
```rust
fn func() -> bool {
    a && !b || !c
}
```

### PR DESCRIPTION
**Pull request by dima74**
Fixes #8014

changelog: Fix omitting parens in DeMorgan's law intention

### CODE REVIEW

File: src/main/kotlin/org/rust/ide/intentions/DemorgansLawIntention.kt [hunk 1]
```diff
@@ -71,18 +71,30 @@ class DemorgansLawIntention : RsElementBaseIntentionAction<DemorgansLawIntention
     private fun applyDemorgan(project: Project, topBinExpr: RsBinaryExpr, opType: BinaryOperator) {
         val converted = convertConjunctionExpression(topBinExpr, opType) ?: return
 
-        var expressionToReplace: RsExpr = topBinExpr
-        var expString = "!($converted)"
         val parent = topBinExpr.parent.parent
```
Comment (ortem) [inline src/main/kotlin/org/rust/ide/intentions/DemorgansLawIntention.kt:74]: Maybe `parent` should be checked for `null` value. Not sure if it's a common situation but it's possible at least when `topBinExpr` is a child of `RsReplCodeFragment` or something like that

**Review by ortem — CHANGES_REQUESTED** [review]

**Review by ortem — APPROVED** [review]
bors r+

**Comment by ortem** [comment]
bors retry
