### PR TITLE
DBG: Update MSVC pretty-printers and type name decorators to Rust 1.67

### LINKED ISSUE #7935: MSVC LLDB pretty-printers for pointer types of string slices does not work since Rust 1.55
## Problem description

MSVC LLDB pretty-printers for pointer types of string slices introduced in https://github.com/intellij-rust/intellij-rust/pull/7065 does not work since Rust 1.55 because of the changes in debug info generation introduced in https://github.com/rust-lang/rust/pull/85269.

Since 1.55, rustc generates `ptr_const$<...>` and `ptr_mut$<...>` type names instead of `const str *` and `mut str *` when targeting MSVC. So pretty-printer should be updated and the corresponding `lldbg-check`s should be added in the tests introduced in https://github.com/intellij-rust/intellij-rust/pull/7399.

### LINKED ISSUE #9769: MSVC LLDB cannot render slices and str since Rust 1.67.0
## Environment

* **IntelliJ Rust plugin version:** 0.4.184.5018-223-nightly
* **Rust toolchain version:** 1.67.0-nightly (83356b78c 2022-11-17) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2022.3 EAP (CL-223.7571.12)
* **Operating system:** Windows 10 10.0

## Problem description

After https://github.com/rust-lang/rust/pull/103691, we should take into account the new type names for slices and str in the LLDB pretty-printers. Currently, the rendering is broken with Rust 1.67.0 nightly, affecting both pretty-printers and MSVC type name decorators.

| Rust 1.65 | Rust 1.67 |
| - | - |
 | 

## Steps to reproduce

```Rust
fn main() {
    let s: &str = "abc";
    let slice: &[i32] = &[1, 2];
    print!(""); // #break
}
```

### PR DESCRIPTION
**Pull request by ortem**
Depends on #9962.

Fixes #7935.
Fixes #9769.

changelog: Update debugger pretty-printers and type name decorators for MSVC to Rust 1.67. Now the debugger renders `str` and slice types properly

### CODE REVIEW

**Review by Undin — CHANGES_REQUESTED** [review]
@ortem since #9962 is already merged, could you rebase changes onto master?

**Comment by ortem** [comment]
@Undin Rebased onto master

File: debugger/src/main/kotlin/org/rust/debugger/lang/RsMSVCTypeNameDecoratorVisitor.kt [hunk 1]
```diff
@@ -31,15 +36,41 @@ class RsMSVCTypeNameDecoratorVisitor : RsTypeNameBaseVisitor<Unit>() {
...
-        ctx.type.accept(this)
+
+        // BACKCOMPAT: Rust 1.66. Get rid of if-else, replace with `ctx.type.accept(this)`
+        @Suppress("DuplicatedCode")
+        if (ctx.type.msvcTypeName()?.msvcStr() != null) {
+            builder.append("str")
+        } else if (ctx.type.msvcTypeName()?.msvcSlice() != null) {
+            builder.append("[")
+            ctx.type.msvcTypeName().msvcSlice().type.accept(this)
+            builder.append("]")
```
Comment (Undin) [inline debugger/src/main/kotlin/org/rust/debugger/lang/RsMSVCTypeNameDecoratorVisitor.kt:51]: Maybe extract `ctx.type.msvcTypeName()` into variable since we use them 3 times?

File: debugger/src/test/kotlin/org/rust/debugger/lang/RsFrameTypeDecoratorTest.kt [hunk 2]
```diff
@@ -18,6 +18,42 @@ class RsFrameTypeDecoratorTest {
         "&str"
     )
 
+    @Test
+    fun `test decorate msvc ptr_const str`() = checkDecorate(
+        "ptr_const$<str>",
```
Comment (Undin) [inline debugger/src/test/kotlin/org/rust/debugger/lang/RsFrameTypeDecoratorTest.kt:23]: Is it possible to get this combination at all?
It seems it was just `str` previously and now it is `ptr_const$<str$>`

**Review by Undin — COMMENTED** [review]
Works for me me but comments

File: debugger/src/test/kotlin/org/rust/debugger/lang/RsFrameTypeDecoratorTest.kt (hunk 2 above)
Comment (Undin) [reply debugger/src/test/kotlin/org/rust/debugger/lang/RsFrameTypeDecoratorTest.kt:23]: It's possible

**Review by Undin — APPROVED** [review]

**Comment by ortem** [comment]
bors r=Undin
