### PR TITLE
RES: Fix resolving macros 2 from prelude

### LINKED ISSUE #7785: `asm!` macro cannot be resolved on nightly
## Environment

* **IntelliJ Rust plugin version:** 0.4.155.4090-212-nightly
* **Rust toolchain version:** 1.56.0-nightly (29ef6cf16 2021-08-31) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2021.2.2 Preview Ultimate Edition (IU-212.5284.19)
* **Operating system:** macOS 10.15.6
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
On nightly, `asm` macro [became](https://github.com/rust-lang/rust/pull/87227) [macro 2.0](https://rust-lang.github.io/rfcs/1584-macros.html) and was moved to another module. As a result, the plugin can't resolve it and doesn't annotate its usage without `unsafe` block as an error

## Steps to reproduce
```rust
#![feature(asm)]

fn main() {
    asm!("nop");
}

```

### PR DESCRIPTION
**Pull request by dima74**
Fixes #7785

changelog: Fix resolving [`asm!`](https://doc.rust-lang.org/beta/unstable-book/library-features/asm.html) macro on nightly rust

### CODE REVIEW

File: src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt [hunk 1]
```diff
@@ -136,23 +136,17 @@ private fun ModData.processMacros(
...
+        val isLegacyMacroDeclaredInSameMod = !isQualified && legacyMacros[name].orEmpty().any {
+            (!isAttrOrDerive || it is ProcMacroDefInfo) && it.path.parent == path
         }
+        // Resolve order for unqualified macros:
+        // - textual macros in same mod
+        // - scoped macros (imported by `use`)
+        // - textual macros
+        !isLegacyMacroDeclaredInSameMod
     }
+    if (stop) return true
```
Comment (Undin) [inline src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt:149]: Is there a case when this line affects the name resolution result or it's only about performance? If yes, can we add the corresponding test?

File: src/main/kotlin/org/rust/lang/core/macros/decl/MacroGraph.kt [hunk 2]
```diff
@@ -42,7 +42,7 @@ sealed class MGNodeData : PresentableNodeData {
 typealias MacroGraph = PresentableGraph<MGNodeData, Unit>
 typealias MacroGraphNode = Node<MGNodeData, Unit>
 
-class MacroGraphBuilder(private val macro: RsMacro) {
+class MacroGraphBuilder(private val macro: RsMacroDefinitionBase) {
```
Comment (Undin) [inline src/main/kotlin/org/rust/lang/core/macros/decl/MacroGraph.kt:45]: As I can see, changes in `MacroGraphBuilder` and `Matcher` are not related to name resolution, It's about completion when macro cannot be expanded properly that @ortem introduced in #4001
It seems that it really makes completion work in calls of macro 2.0 but there are no tests for it.
If I'm right, maybe extract these changes into separate PR and add the corresponding tests (see `org.rust.lang.core.completion.RsPartialMacroArgumentCompletionTest`)?

**Review by Undin — COMMENTED** [review]
Works for me

File: src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt (hunk 1 above)
Comment (dima74) [reply src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt:149]: This is common convention in resolve code to stop processing if `processor` returns true for some `ScopeEntry`. Actually code here hasn't changed, I just extracted `processScopedMacros` function. It can affect name resolution and there are already some tests which check it, e.g. ```RsPackageLibraryResolveTest#`test import wins extern crate import` ```

File: src/main/kotlin/org/rust/lang/core/macros/decl/MacroGraph.kt (hunk 2 above)
Comment (dima74) [reply src/main/kotlin/org/rust/lang/core/macros/decl/MacroGraph.kt]: Thanks, I removed code related to `MacroGraphBuilder`, and will open separate PR for it after this PR will be merged

File: src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt (hunk 1 above)
Comment (Undin) [reply src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt:149]: Or, sorry, I missed `return true` in previous version

**Review by Undin — APPROVED** [review]
bors r+

**Comment by vlad20012** [comment]
Let's also add a test without stdlib dependency
