### PR TITLE
CARGO: fix building local crate index

### LINKED ISSUE #10060: `Failed to resolve remote branch in the cargo registry index repository` with `sparse-registry`
## Environment

* **IntelliJ Rust plugin version:** 0.4.188.5173-223-nightly
* **Rust toolchain version:** null
* **IDE name and version:** IntelliJ IDEA 2022.3.1 Ultimate Edition (IU-223.8214.52)
* **Operating system:** macOS 12.5.1
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.cargo.emulate.terminal

## Problem description
See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#sparse-registry

```
java.lang.Throwable: Failed to resolve remote branch in the cargo registry index repository
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
```
	
<details>

```
java.lang.Throwable: Failed to resolve remote branch in the cargo registry index repository
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at org.rust.toml.crates.local.CratesLocalIndexUpdateTask.readRegistryHeadCommitHash(CratesLocalIndexServiceImpl.kt:545)
	at org.rust.toml.crates.local.CratesLocalIndexUpdateTask.run(CratesLocalIndexServiceImpl.kt:498)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:423)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:474)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:589)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:664)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:620)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:588)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

</details>

## Steps to reproduce
1. Add this part in `.cargo/config.toml` in chosen project A:
```
[registries.crates-io]
protocol = 'sparse'
```
2. Close ALL IDEs with rust projects 
3. Delete `registry` folder in .cargo
4. Delete caches in  `/Users/%username$/Library/Caches/JetBrains/%IDEVERSION%` folder. Check path [here](https://www.jetbrains.com/help/idea/directories-used-by-the-ide-to-store-settings-caches-plugins-and-logs.html#system-directory)
5. Open project A

____
Related issues:
- [ ] https://github.com/intellij-rust/intellij-rust/issues/10267
- [x] https://github.com/intellij-rust/intellij-rust/issues/10199

### LINKED ISSUE #10199: Plugin does not know about latest crate versions
## Environment

* **IntelliJ Rust plugin version:** 0.4.179.4903-221
* **Rust toolchain version:** 1.69.0-nightly
* **IDE name and version:** CLion 2022.1.3
* **Operating system:** Windows 7

## Problem description
When I activate the autocompletion for the crate version, the latest versions don't show up:
image

`reqwest`'s latest version at this point is [0.11.14](https://docs.rs/reqwest/0.11.14/reqwest/).

If I type that manually, it shows the inspection warning "No version matching 0.11.14 found for crate reqwest":

image

After disabling `org.rust.crates.local.index` I get the latest versions, but I don't get the autocompletion in long form `<crate> = { version = "...", features = [...] }` items.

This affected almost every dependency in my project.

### PR DESCRIPTION
**Pull request by Undin**
Starting with 1.68, cargo stabilized [sparse](https://doc.rust-lang.org/cargo/reference/registries.html#registry-protocols) protocol to reduce the duration of fetching info about external dependencies.

Unfortunately, the new API doesn't allow getting the whole index. As a result, the plugin may fail to build crates index for crates completion/annotation in Cargo.toml configs

These changes introduce `CratesLocalIndexUpdater` service that is supposed to force cargo to update old git crate index periodically and eventually, update plugin's crate index

Under the hood, the service just creates the simplest Cargo project and forces cargo to update crates registry it using `git` protocol

Fixes #10199
Fixes #10060

This is a workaround (not sure if it is temporary) for #10267

changelog: Provide proper completion/annotation for crate names and versions in `Cargo.toml` when [sparse](https://doc.rust-lang.org/cargo/reference/registries.html#registry-protocols) protocol is used

### CODE REVIEW

File: toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexUpdater.kt [hunk 1]
```diff
@@ -0,0 +1,210 @@
...
+
+@Service
+class CratesLocalIndexUpdater : Disposable {
+
+    private val alarm: Alarm = Alarm(this)
+
+    private var isUpdating: Boolean = false
+
+    @Synchronized
+    fun updateCratesIoGitIndex() {
```
Comment (vlad20012) [inline toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexUpdater.kt:45]: Since `updateCratesIoGitIndex` can only be safely invoked from EDT, let's add an assert and remove `@Synchronized` annotation.

Also, there are several different functions called `updateCratesIoGitIndex` that is a bit confusing.

**Review by vlad20012 — COMMENTED** [review]
LGTM in general

File: toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexUpdater.kt [hunk 2]
```diff
@@ -0,0 +1,210 @@
...
+                serde = "1.0"
+            """.trimIndent()),
+            FileTemplate("src/lib.rs", "")
+        )
+
+        private val hasOpenRustProject: Boolean
+            get() {
+                // Read action is needed not to get disposed projects
+                // from `com.intellij.openapi.project.ProjectManager.getOpenProjects`
+                return runReadAction {
```
Comment (vlad20012) [inline toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexUpdater.kt:135]: It seems like the read action is not needed because you call `hasOpenRustProject` only from EDT where you always have the read lock acquired.

**Comment by mili-l** [comment]
needs extra verification for Win
