### PR TITLE
COMP: Fix function self ref and double colon

### LINKED ISSUE #1639: self:: autocompletion in function signatures
[Imgur](http://i.imgur.com/w0AJFIE.png)

Notice the colons.

This happens even outside impl blocks. I don't think any other paths trigger it; only `self::`.

edit:
PyCharm Pro 2017.2.1
intellij-rust 0.1.0.2065
rustc 1.19.0 (0ade33941 2017-07-17)

### PR DESCRIPTION
**Pull request by farodin91**
Fixes #1639 
@matklad @Undin r?

### CODE REVIEW

File: src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt [hunk 1]
```diff
@@ -238,6 +242,15 @@ fun processPathResolveVariants(lookup: ImplLookup, path: RsPath, isCompletion: B
     return processNestedScopesUpwards(path, processor, ns)
 }
 
+private inline fun <reified T : PsiElement> PsiElement.contextOfType(strict: Boolean = true): T? {
```
Comment (Undin) [inline src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt]: Looks like we already have this method [here](https://github.com/intellij-rust/intellij-rust/blob/1a1ea675f6c72db2358845518c85986b879aa394/src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt#L35-L36)

File: src/main/kotlin/org/rust/lang/core/resolve/Processors.kt [hunk 2]
```diff
@@ -8,6 +8,7 @@ package org.rust.lang.core.resolve
 import com.intellij.codeInsight.lookup.LookupElement
 import org.rust.lang.core.completion.createLookupElement
 import org.rust.lang.core.psi.RsFunction
+import org.rust.lang.core.psi.RsValueParameter
```
Comment (Undin) [inline src/main/kotlin/org/rust/lang/core/resolve/Processors.kt]: Unused import

**Comment by farodin91** [comment]
Resolved

File: src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt [hunk 3]
```diff
@@ -219,11 +219,15 @@ fun processPathResolveVariants(lookup: ImplLookup, path: RsPath, isCompletion: B
     val crateRoot = path.crateRoot
     if (!path.hasColonColon) {
         if (Namespace.Types in ns) {
-            if (processor("self", containingMod)) return true
-            val superMod = containingMod.`super`
-            if (superMod != null) {
-                if (processor("super", superMod)) return true
+            val context = parent?.contextOfType<RsValueParameter>()
```
Comment (matklad) [inline src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt]: Hm, I think `contextOfType` will overshoot here. What if we are completing something like

```
struct Foo;

fn foo(foo: se/*caret*/lf::Foo) {
}
```

Comment (farodin91) [inline src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt]: What should i do here?

Comment (matklad) [reply src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt]: Hm, it seems to me that perhaps we should fix this at the level of insertion handler?

Reference completion for `self` parameter does not make much sense anyway, because it's more like a named element, and not a reference.

Comment (farodin91) [reply src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt]: I don't have time to look in depth until end of next week.

Comment (farodin91) [reply src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt]: I added both self and self:: to resolve this issue. I have no idea to fix it at the insertion handler.

**Comment by farodin91** [comment]
@matklad any suggestions?

**Comment by matklad** [comment]
Yeah, I still think that it's valid to suggest modules here, because the following is a valid Rust code:

```Rust
fn main() {
    println!("Hello, World");
}

struct S(u32);

impl S {
    fn foo(self::S(x): S) {

    }
}
```

So I still think that the insertion handle should be fixed here: https://github.com/intellij-rust/intellij-rust/blob/cbba4d044c37fe466ed409a871faf33363491e55/src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt#L27


Also care must be taken to disable `::` only on top level in self parameter, so that it is autoinserted in, for example, this case:

```
fn foo(xs: Vec<self::S>) { }
```

**Comment by farodin91** [comment]
Resolved but a bit different

File: src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt [hunk 4]
```diff
@@ -220,11 +220,13 @@ fun processPathResolveVariants(lookup: ImplLookup, path: RsPath, isCompletion: B
...
+            if (context is RsValueParameter) {
+                if (processor("self", context)) return true
+            } else if (processor("self", containingMod)) return true
+
             val superMod = containingMod.`super`
-            if (superMod != null) {
-                if (processor("super", superMod)) return true
-            }
+            if (superMod != null && processor("super", superMod)) return true
```
Comment (matklad) [inline src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt]: It still seems to me that it is wrong to modify name resolution hear, because semantically resolving a self parameter to itself does not make sense.

I think that modifying insertion handler to handle self parameters simlarly to use globs should be enough:


```Rust
private fun doubleColonLookup(base: LookupElementBuilder): LookupElementBuilder =
    base.withTailText("::")
        .withInsertHandler({ ctx, _ ->
            val offset = ctx.tailOffset - 1
            val inUse = PsiTreeUtil.findElementOfClassAtOffset(ctx.file, offset, RsUseGlobList::class.java, false) != null
            val inSelfParam = PsiTreeUtil.findElementOfClassAtOffset(ctx.file, offset, RsSelfParameter::class.java, false) != null
            if (!(inUse || inSelfParam)) {
                ctx.addSuffix("::")
            }
        })
```

Comment (farodin91) [reply src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt]: For me, it was unclear, how lookup builder work.

**Comment by farodin91** [comment]
Resolved

**Comment by matklad** [comment]
bors r+

Thanks!
