### PR TITLE
MACRO: Use `rust-analyzer-proc-macro-srv` from toolchain if available

### LINKED ISSUE #9159: Macro expansion broken on nightly unknown-linux-gnu since 2022-05-16
## Environment

* **IntelliJ Rust plugin version:** 0.4.175.4772-222 and intellij-rust-0.4.172.4687-222
* **Rust toolchain version:** 1.63.0-nightly (42e1761c7 2022-05-15) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2022.2 (CL-222.3345.126)
* **Operating system:** Linux 5.17.15-76051715-generic
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description
Macro  exapnsion broken since `nightly-2022-05-16-x86_64-unknown-linux-gnu` and beyond. I've tested a few dozens of nightly versions and found exact version numbers:

`nightly-2022-05-15-x86_64-unknown-linux-gnu` (also 2022-05-10, 2022-05-05) - macro expansion works
image

`nightly-2022-05-16-x86_64-unknown-linux-gnu` (also 2022-05-20, 2022-05-30, 2022-06-20, 2022-07-10) - macro expansion **broken**
image

If you try to expand macros by hand using single step or recursive expansion, you will see this message
image

## Steps to reproduce
1. Clone this repo - https://github.com/chamoretto/function-like-macro-expansion-problem, `git clone https://github.com/chamoretto/function-like-macro-expansion-problem`
2. Checkout the branch `git checkout issue-coloring-examples` , there are some proc macro written by hand which could illustrate the problem
3. Watch the lines 40-41, there are good macros which **should be** expaneded well (macros at 42-45 will fail, you can comment them out)
4. `rustup toolchain install nightly-2022-05-15-x86_64-unknown-linux-gnu --component rust-src --component rust-std`
5. `rustup toolchain install nightly-2022-06-15-x86_64-unknown-linux-gnu --component rust-src --component rust-std`
6. `rustup override set nightly-2022-05-15-x86_64-unknown-linux-gnu`
7. Reload cargo project, expansion works
8. `rustup override set nightly-2022-05-16-x86_64-unknown-linux-gnu`
9. Reload cargo project, aaaand expansion is broken
10. Try to use single step or recursive macro expansion in order to see error message

My Idea.log file, written during test session.
[idea.log](https://github.com/intellij-rust/intellij-rust/files/9269413/idea.log)

### LINKED ISSUE #9172: Use `rust-analyzer-proc-macro-srv` from the toolchain to expand proc macros
The latest nightly toolchains now include an executable to expand proc macros, which will always match the current compiler in `{toolchain}/libexec/rust-analyzer-proc-macro-srv`.

It should be possible to use this instead of the native helper that's shipped with `intellij-rust`.

For reference:
https://fasterthanli.me/articles/proc-macro-support-in-rust-analyzer-for-nightly-rustc-versions

### PR DESCRIPTION
**Pull request by vlad20012**
Fixes #9172
Fixes #9159

You can read the full story [here](https://fasterthanli.me/articles/proc-macro-support-in-rust-analyzer-for-nightly-rustc-versions). Long story short, since 01.08.2022 there is a binary `$sysroot/libexec/rust-analyzer-proc-macro-srv` shipped within `rustc` rustup component in the nightly channel. This binary can be used as a drop-in replacement for our own `intellij-rust-native-helper` in the case of macro expansion. Of course it is always compatible with rustc version it shipped with, so now macro expansion will work fine on every nightly version.

In this PR I use `rust-analyzer-proc-macro-srv` instead of `intellij-rust-native-helper` if it is available (exist). This likely obsoletes #8930.
Note that `intellij-rust-native-helper` is still used as a rustc wrapper on all toolchains and as a proc macro expander on stable toolchains

### CODE REVIEW

**Review by mchernyavsky — APPROVED** [review]
LGTM

File: src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroExpander.kt [hunk 1]
```diff
@@ -206,5 +207,25 @@ class ProcMacroExpander(
...
+            val procMacroExpanderPath =  crate.cargoProject?.procMacroExpanderPath
+            val server = if (toolchain != null && procMacroExpanderPath != null) {
+                ProcMacroApplicationService.getInstance().getServer(toolchain, procMacroExpanderPath)
+            } else {
+                null
+            }
+            return new(project, toolchain, server)
+        }
+
+        fun new(project: Project, toolchain: RsToolchainBase?, server: ProcMacroServerPool?): ProcMacroExpander {
```
Comment (dima74) [inline src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroExpander.kt:223]: Maybe inline this function, it is used only once

File: src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroServerPool.kt [hunk 2]
```diff
@@ -65,18 +66,35 @@ class ProcMacroServerPool private constructor(
...
-            return createUnchecked(toolchain, expanderExecutable, parentDisposable)
+            return expanderPath
         }
 
-        @VisibleForTesting
-        fun createUnchecked(toolchain: RsToolchainBase, expanderExecutable: Path, parentDisposable: Disposable): ProcMacroServerPool {
-            return ProcMacroServerPool(toolchain, expanderExecutable)
-                .also { Disposer.register(parentDisposable, it) }
+        private fun findEmbeddedExpander(toolchain: RsToolchainBase): Path? {
+            return RsPathManager.nativeHelper(toolchain is RsWslToolchain)
```
Comment (dima74) [inline src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroServerPool.kt:97]: Should we check executable here as before?
```suggestion
            return RsPathManager.nativeHelper(toolchain is RsWslToolchain)
                ?.takeIf { it.isExecutable() }
```

Comment (vlad20012) [reply src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroServerPool.kt:97]: It's now checked inside `RsPathManager.nativeHelper()`

**Comment by vlad20012** [comment]
bors r=mchernyavsky

**Comment by ForsakenHarmony** [comment]
🎉🎉🎉
