### PR TITLE
RUN: Fix MSVC toolchain detection on debug

### LINKED ISSUE #2630: Debugging is not possible - More than one binary produced. Please specify `--bin`, `--lib`, `--test` or `--example` flag explicitly.
I've seen others with this same error, but none of their solutions seem to work for me.

This occurs when I try to debug tests in CLion. I can run the tests fine, but debugging causes this error.

rust toolchain: nightly-2018-05-16-x86_64-unknown-linux-gnu

I have tried with both LLDB and GDB.

screenshot from 2018-07-02 16-42-44

### PR DESCRIPTION
**Pull request by ortem**
Fixes #2630

### CODE REVIEW

File: src/main/kotlin/org/rust/cargo/runconfig/RsAsyncRunner.kt [hunk 1]
```diff
@@ -135,8 +135,11 @@ abstract class RsAsyncRunner(private val executorId: String, private val errorMe
             }
     }
 
-    open fun checkToolchain(project: Project): Boolean = true
+    open fun checkToolchainConfigured(project: Project): Boolean = true
 
+    open fun checkToolchainIsMSVC(state: CargoRunStateBase): Boolean = false
+
+    open val isMSVCToolchainSupported: Boolean = true
```
Comment (mchernyavsky) [inline src/main/kotlin/org/rust/cargo/runconfig/RsAsyncRunner.kt]: ???

File: src/main/kotlin/org/rust/cargo/runconfig/RsAsyncRunner.kt [hunk 2]
```diff
@@ -135,8 +135,9 @@ abstract class RsAsyncRunner(private val executorId: String, private val errorMe
             }
     }
 
-    open fun checkToolchain(project: Project): Boolean = true
+    open fun checkToolchainConfigured(project: Project): Boolean = true
 
+    open fun isUnsupportedMSVCToolchain(state: CargoRunStateBase): Boolean = false
```
Comment (mchernyavsky) [inline src/main/kotlin/org/rust/cargo/runconfig/RsAsyncRunner.kt]: ??????
