### PR TITLE
MACRO: fix `format` macro expansion when param name is keyword (`self`) or there is a syntax error in param name

### LINKED ISSUE #9282: `println!("{t+5}")` totally breaks IDE
## Environment

* **IntelliJ Rust plugin version:** 0.4.178.4849-222-nightly
* **Rust toolchain version:** 1.65.0-nightly (015a824f2 2022-08-22) x86_64-apple-darwin
* **IDE name and version:** CLion 2022.2.1 (CL-222.3739.54)
* **Operating system:** macOS 12.5.1
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description
It seems that some endless calculation starts.
1. increasing CPU usage
2. IDE functions stop working (completion, higlighting)

https://user-images.githubusercontent.com/49211026/187917322-0906f6cc-8be5-4e35-8e5b-4b40908c984c.mov

## Steps to reproduce
```rust
fn main() {
    let t = 8;
    println!("{t}");
}
```
1. add `+ 8` in {}
1. remove `}` and  type it back 
1. try to type something 

and play with code in other ways : )

### PR DESCRIPTION
**Pull request by vlad20012**
Fixes #9282

### CODE REVIEW

File: src/main/kotlin/org/rust/lang/core/macros/builtin/BuiltinMacroExpander.kt [hunk 1]
```diff
@@ -73,9 +71,9 @@ private fun handleFormatMacro(macroName: String, macroText: String, format: RsFo
 
     val namedArguments = mutableSetOf<String>()
     for (argument in format.formatMacroArgList) {
-        val identifier = argument.identifier
-        if (identifier != null) {
-            namedArguments.add(identifier.text)
+        val name = argument.name()
```
Comment (Kobzol) [inline src/main/kotlin/org/rust/lang/core/macros/builtin/BuiltinMacroExpander.kt:74]: Hmm, I wanted to write that we should also check here that `argument.eq` isn't `null`, otherwise this could also find things like
`print!("{}", a);` <- here `a` will be returned by `name()`, but it's not a named format argument.

But I checked it and `name()` returns `null` for `a` here, even though it is an identifier, I did not expect that. Well, in that case it's ok I guess :)

**Review by Kobzol — APPROVED** [review]
LGTM

File: src/main/kotlin/org/rust/lang/core/macros/builtin/BuiltinMacroExpander.kt (hunk 1 above)
Comment (vlad20012) [reply src/main/kotlin/org/rust/lang/core/macros/builtin/BuiltinMacroExpander.kt:74]: In the `print!("{}", a);` it's not an identifier but `RsPathExpr`, but I've added an additional check (just in case)

**Comment by vlad20012** [comment]
bors r=Kobzol
