### PR TITLE
INT: Fix and enable "Extract enum variant" intention

### LINKED ISSUE #5024: Extract enum variant to struct
It would be cool if there were an intention (or better refactoring) to extract enum variant to separate struct.

Example:
```rust 
enum A {
    Variant1 { name: String, id: usize, }
}
```
extract into something like:
```rust
enum A {
     Variant1(Variant1)
}

struct Variant1 { 
    name: String, 
    id: usize, 
}
```
As a refactoring it could also replace usages, but intention is already great.

### PR DESCRIPTION
**Pull request by mchernyavsky**
Bunch of fixes:
* Enable the intention.
* Get rid of `extractVisibility` and related staff since visibility qualifiers for enum variant's fields are not permitted ([E0449](https://doc.rust-lang.org/error-index.html#E0449)).
* Now generated struct has the same visibility qualifier as parent enum has.
* Since enum's fields have public visibility by default, add `pub` qualifier to all fields in generated struct if the corresponding field in the enum variant has no visibility qualifier.
* After replacing usages of the original enum variant, import the generated struct if needed.
* Fix struct renaming if an element with the same name already exists in the scope.

There is one more problem. `RsInPlaceVariableIntroducer` doesn't work if the element to rename has non-local use scope.

Closes #5024

### CODE REVIEW

**Comment by Kobzol** [comment]
Oh wow, I can't believe that I didn't actually test whether the visibility make sense :D Good job :+1:

File: src/main/kotlin/org/rust/ide/intentions/ExtractEnumVariantIntention.kt [hunk 1]
```diff
@@ -314,7 +369,7 @@ private data class CollectLifetimesVisitor(
     }
 }
 
-fun gatherLifetimes(
+private fun gatherLifetimes(
```
Comment (Undin) [inline src/main/kotlin/org/rust/ide/intentions/ExtractEnumVariantIntention.kt:372]: Let's make the same with `gatherTypeParameters`

File: src/main/kotlin/org/rust/ide/intentions/ExtractEnumVariantIntention.kt [hunk 2]
```diff
@@ -179,92 +197,129 @@ class ExtractEnumVariantIntention : RsElementBaseIntentionAction<ExtractEnumVari
...
 
-        for (pat in parent.patList) {
-            val comma = pat.nextSibling
-            pat.delete()
-            if (comma.text == ",") {
-                comma.delete()
+    override fun createStruct(vis: String?, name: String, typeParameters: String, whereClause: String): RsStructItem {
+        val formattedVis = if (vis == null) "" else "$vis "
+        val fields = formatFields()
+        return factory.createStruct("${formattedVis}struct $name$typeParameters$fields$whereClause;")
```
Comment (Undin) [inline src/main/kotlin/org/rust/ide/intentions/ExtractEnumVariantIntention.kt:246]: `org.rust.ide.intentions.TupleVariant#createStruct` and `org.rust.ide.intentions.StructVariant#createStruct` looks very similar
Maybe it's better not to override it in each inheritor, move all code in base class and make `when` for struct text?

**Comment by mchernyavsky** [comment]
@Undin

> Some examples when the current implementation doesn't work properly:

Fixed, except [2](https://github.com/intellij-rust/intellij-rust/issues/5265) and 3.

**Comment by mchernyavsky** [comment]
@Undin Fixed

**Comment by Undin** [comment]
@mchernyavsky don't hesitate to merge it yourself after approve of PR
bors r+
