### PR TITLE
RES: resolve qualified attribute proc macro paths

### LINKED ISSUE #4481: Goto Definition doesn't work for path attribute macros
## Environment

* **IntelliJ Rust plugin:**
0.2.106.2135-192 (Sep 30, 2019)
* **Rust toolchain:**
beta-x86_64-pc-windows-gnu (default)
rustc 1.39.0-beta.1 (968967007 2019-09-24)
* **IDE:**
IntelliJ IDEA 2019.2.2 (Ultimate Edition)
Build #IU-192.6603.28, built on September 6, 2019
Runtime version: 11.0.3+12-b304.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1971M
Cores: 8
Registry: 
Non-Bundled Plugins: [...], org.toml.lang, org.rust.lang

## Problem description

Attribute macros using a path (e.g. `#[lib::foo]`) do not work with Goto Definition. Goto Definition works fine when the macro is imported and used without qualification (e.g. `#[foo]`).

## Steps to reproduce

```rust
// name = "foo"
// lib.proc-macro = true
extern crate proc_macro;
use proc_macro::TokenStream;
#[proc_macro_attribute]
pub fn foo(attr: TokenStream, item: TokenStream) -> TokenStream { item }
```
```rust
// name = "consumer"
// dependencies.foo.path = "path/to/foo"
use lib; use lib::foo;
#[lib::foo] fn does_not_work() {}
#[foo] fn this_does_work() {}
```

### PR DESCRIPTION
**Pull request by vlad20012**
Now the plugin should correctly resolve this:

```rust
#[foo::bar] // Resolve `foo::bar`
fn baz() {}
```

Fixes #4481

changelog: correctly resolve qualified attribute proc macro paths (like `#[foo::bar]`)

### CODE REVIEW

**Review by Undin — COMMENTED** [review]
Note, this change breaks name resolution for `foo` item in the following code:
```rust
#[lib::bar] // Resolve `lib::bar`
fn baz() {}
```

Note, `lib` is resolved in master currently

**UPD**:
Name resolution works only if library has `foo` name for some reason (at least, for me)

```rust
#[foo::bar]
fn baz() {}
```
Moreover, it works with `foo` even if the library is not called `foo`

**Comment by Undin** [comment]
@vlad20012 looks like it's a cache invalidation problem
Steps to reproduce:
- create the following project:

`Cargo.toml`
```toml
[package]
name = "rust_project"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "lib"
proc-macro = true
```

`lib.rs`
```rust
extern crate proc_macro;
use proc_macro::TokenStream;
#[proc_macro_attribute]
pub fn foo(attr: TokenStream, item: TokenStream) -> TokenStream { item }
```

`src/main.rs`
```rust
use lib::foo;

#[lib::foo]
fn baz() {}

fn main() {}
```

* change library name in `Cargo.toml` from `lib` to `libb`, for example, and invoke `Refresh Cargo projects` actions. After that, `Goto definition` for all references in `use lib::foo`  and `lib` in `#[lib::foo]` works as previously. Only structured change (for example, the addition of new function) helps to drop old resolve info.

* make revert change, i.e. change `libb` from `Cargo.toml` to `lib` again and launch `Refresh Cargo projects`. `Goto definition` action works only for `foo` reference in `#[lib::foo]`.


It seems the described bug is not related to your changes but it would be great to fix it as well

File: src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroResolveTest.kt [hunk 1]
```diff
@@ -112,19 +112,33 @@ class RsProcMacroResolveTest : RsResolveTestBase() {
...
             pub fn example_proc_macro(attr: TokenStream, item: TokenStream) -> TokenStream { item }
         //- lib.rs
-            use dep_proc_macro
             #[dep_proc_macro::example_proc_macro]
                                 //^ dep-proc-macro/lib.rs
             struct S;
     """)
-    }
+
+    @MockEdition(Edition.EDITION_2018)
```
Comment (dima74) [inline src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroResolveTest.kt:126]: Lets remove `@MockEdition` from individual methods since we have `@MockEdition` on the whole class

**Review by dima74 — APPROVED** [review]

**Comment by vlad20012** [comment]
@Undin's case is unrelated to the PR, let's fix it deparately

bors r=dima74

**Comment by Undin** [comment]
I've created a separate issue #7143
