### PR TITLE
(INTENTION) fix ExpandModule isAvaiable predicate

### LINKED ISSUE #269: ExpandModule should not be applicable to directory owning modules
This intention is available for crate roots like `src/lib.rs`, which is wrong. 

This line must be fix: https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/ide/intentions/ExpandModule.kt#L20

### PR DESCRIPTION
**Pull request by zjhmale**
Fix #269 

for now `mod.rs` and `src/lib.rs` will not have ExpandModule Intention.

### CODE REVIEW

**Comment by matklad** [comment]
Could you use [ownsDirectory](https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/lang/core/psi/util/RustModExtensions.kt#L65) function here? It is more general and will handle non-conventional project layouts

**Comment by zjhmale** [comment]
:ok: i will try it out.

**Comment by zjhmale** [comment]
hi @matklad , can you explain where can i use `RustModItem.ownsDirectory` function? cause can not cast PsiFIle to RustModItem.

File: src/main/kotlin/org/rust/ide/intentions/ExpandModule.kt [hunk 1]
```diff
@@ -17,7 +20,7 @@ class ExpandModule : IntentionAction {
     override fun startInWriteAction()   = true
 
     override fun isAvailable(project: Project, editor: Editor?, file: PsiFile?) =
-        file is RustFile && file.name != RustModules.MOD_RS
+        file is RustFile && (!(file.rustMod as RustModItem).ownsDirectory && !(file.name.equals(RustModules.LIB_RS) && file.containingDirectory?.name.equals("src")))
```
Comment (matklad) [inline src/main/kotlin/org/rust/ide/intentions/ExpandModule.kt]: If you use `ownsDirectory`, then you don't need to check file name or parent directory name. 

Also this `as` casts away nullability and is effectively just `!!`. You can use something like `file.rustMod?.ownsDirectory ?: false`

Comment (zjhmale) [inline src/main/kotlin/org/rust/ide/intentions/ExpandModule.kt]: ok i will make it more null safety, but in `mod.rs` file `owsDirectory` returns true and in `src/lib.rs` this func returns false, it's impossible to handle this two condition use this single function, maybe i should add more check in `owsDirectory`?

Comment (matklad) [inline src/main/kotlin/org/rust/ide/intentions/ExpandModule.kt]: The `|| isCrateRoot` condition in `ownsDirecotry` should handle `src/lib.rs`, `src/bin/my_executable.rs`, `examples/hello_world.rs` and all other possible locations of crate roots. 

It only works if you `import` project via cargo though, but this is a necessary limitation.

Comment (zjhmale) [inline src/main/kotlin/org/rust/ide/intentions/ExpandModule.kt]: ok i will try to reimport the project.

**Comment by zjhmale** [comment]
done @matklad it works only if `import` via cargo just like you mentioned.

**Comment by matklad** [comment]
Thanks! Could you please squash this down to one commit?

**Comment by zjhmale** [comment]
no problem :)
