### PR TITLE
RES: Fix injecting prelude in 2021 edition

### LINKED ISSUE #7796: Additions to the prelude in 2021 edition
Requires changes inside [name resolution code](https://github.com/intellij-rust/intellij-rust/blob/cd9189d535573f296421f5322fd9fad4502ac03e/src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt#L1713) because currently, we add all items from `prelude/v1.rs` but recent changes in stdlib introduced `std::prelude::rust_%edition%` modules for each edition. 
And now compiler implicitly adds `use std::prelude::rust_%edition%:*;` instead of `use std::prelude::v1::*;`.
As a result, the following code
```rust
fn main() {
    let result = char::try_from(123u32);
    println!("{:?}", result);
}
```
is compiled successfully with 2021 edition but the plugin shows the error

image

### PR DESCRIPTION
**Pull request by dima74**
Fixes #7796

Related: https://github.com/rust-analyzer/rust-analyzer/pull/9097

changelog: Use correct prelude for 2021 edition

### CODE REVIEW

File: src/main/kotlin/org/rust/lang/core/resolve2/FacadeMetaInfo.kt [hunk 1]
```diff
@@ -43,3 +44,9 @@ fun RsMod.getDirectoryContainedAllChildFiles(): VirtualFile? {
     val (_, _, modData) = getModInfo(this) as? RsModInfo ?: return null
     return PersistentFS.getInstance().findFileById(modData.directoryContainedAllChildFiles)
 }
+
+fun findPreludeUsingNewResolve(element: RsElement): RsMod? {
```
Comment (Undin) [inline src/main/kotlin/org/rust/lang/core/resolve2/FacadeMetaInfo.kt:48]: nit: Do we actually need this public function here?
Maybe move it into `NameResolution.kt` and make private?

File: src/main/kotlin/org/rust/lang/core/resolve2/FacadeBuildDefMap.kt [hunk 2]
```diff
@@ -123,41 +124,46 @@ private fun getDirectAndAllDependencies(
...
-        .mapNotNull { allDependenciesDefMaps[it]?.prelude }
-        .firstOrNull()
+private fun injectPrelude(defMap: CrateDefMap) {
+    val preludeCrate = when (defMap.stdlibAttributes) {
+        RsFile.Attributes.NONE -> AutoInjectedCrates.STD
+        RsFile.Attributes.NO_STD -> AutoInjectedCrates.CORE
+        RsFile.Attributes.NO_CORE -> return
+    }
+    val preludeName = when (val edition = defMap.metaData.edition) {
+        // We don't use "rust_2015" and "rust_2018" in order to be compatible with old rustc
```
Comment (Undin) [inline src/main/kotlin/org/rust/lang/core/resolve2/FacadeBuildDefMap.kt:140]: Let's add `// BACKCOMPAT: Rust %insert_necessary_version_here%` to mark this code as compatibility one

File: src/test/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspectionTest.kt [hunk 3]
```diff
@@ -212,6 +212,15 @@ class RsUnresolvedReferenceInspectionTest : RsInspectionsTestBase(RsUnresolvedRe
         extern crate unknown_crate2;
     """)
 
+    @MinRustcVersion("1.56.0")
```
Comment (Undin) [inline src/test/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspectionTest.kt:215]:
```suggestion
    @MinRustcVersion("1.56.0-nightly")
```
since `1.56.0-nightly` < `1.56.0`

File: src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTestEdition2021.kt [hunk 4]
```diff
@@ -0,0 +1,24 @@
...
+
+package org.rust.lang.core.resolve
+
+import org.rust.MinRustcVersion
+import org.rust.MockEdition
+import org.rust.ProjectDescriptor
+import org.rust.WithStdlibRustProjectDescriptor
+import org.rust.cargo.project.workspace.CargoWorkspace
+
+@MinRustcVersion("1.56.0")
```
Comment (Undin) [inline src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTestEdition2021.kt:14]:
```suggestion
@MinRustcVersion("1.56.0-nightly")
```
since `1.56.0-nightly` < `1.56.0`

**Review by Undin — APPROVED** [review]
LGTM except minor comments

**Comment by dima74** [comment]
bors r=Undin
