### PR TITLE
(GRAM): fix the grammar for types

### LINKED ISSUE #303: (PSI): Poor PSI structure for types
Grammar rule for types does not yield a wrapper PSI element for a `type`. This means that a sequence of PSI elements which denote particular type is not wrapped inside specialised PSI type:

java_2016-03-27_22-07-52

That guy from the screenshot should be wrapped inside something like `RustType`, or even better `RustSliceType` or `RustArrayType` which would inherit (as PSI element interface) from `RustType` ("abstract" element interface).

Because of this, it's almost impossible to write some stuff related to types specifically. Also, expand selection doesn't work well.

### PR DESCRIPTION
**Pull request by matklad**
This prettifies the grammar for types. The main change is that we get rid of `type` vs `type_sum` dichotomy.

`type_sum` is a prime example of bad naming =) It is not a sum of types, but rather a single type. Its difference from a simple `type` is that the latter forbids bounded types (T: B1 + B2). Both `type` and `type_sum` were needed due to original parser idiosyncrasy (because of bounded types, `type_sum` production is left recursive). However, Grammar Kit handles left recursion. 

@jajakobyly please review

closes #303

### CODE REVIEW

File: src/main/java/org/rust/lang/core/psi/RustTokenElementTypes.java [hunk 1]
```diff
@@ -54,7 +54,7 @@
     RustTokenType SUPER = new RustKeywordTokenType("super");
     RustTokenType TRAIT = new RustKeywordTokenType("trait");
     RustTokenType TRUE = new RustKeywordTokenType("true");
-    RustTokenType TYPE = new RustKeywordTokenType("type");
+    RustTokenType TYPE_KW = new RustKeywordTokenType("type");
```
Comment (jajakobyly) [inline src/main/java/org/rust/lang/core/psi/RustTokenElementTypes.java]: What do you think about prefixing all keyword token types with `KW_`, e.g. `KW_TYPE`, `KW_UNSIZED`? This will save us from getting imho awful name collisions like this one.

The same idea might be applied to operators - `OP_xxx`. Thought, unfortunately, this would be breaking change.

File: src/main/kotlin/org/rust/lang/core/grammar/rust.bnf [hunk 2]
```diff
@@ -366,7 +367,7 @@ private fn_header ::= CONST? UNSAFE? [ EXTERN abi? ] FN IDENTIFIER
 
 fn_params ::= LPAREN !COMMA params COMMA? RPAREN { pin(".*") = 1 }
 private params ::= [ param (COMMA param)* ]
-param ::= pat COLON type_sum
+param ::= pat COLON type
 
 ret_type  ::= ARROW (type | EXCL) { pin = 1 }
```
Comment (jajakobyly) [inline src/main/kotlin/org/rust/lang/core/grammar/rust.bnf]: This guy has pretty unfortunate name. Maybe `ret_type_spec`? Rust Reference calls this *output type* which is even worse in out case.

**Comment by jajakobyly** [comment]
I only have some doubts about the naming, but generally looks ok (as for now). :+1:

File: src/main/java/org/rust/lang/core/psi/RustTokenElementTypes.java (hunk 1 above)
Comment (matklad) [inline src/main/java/org/rust/lang/core/psi/RustTokenElementTypes.java]: >Though, unfortunately, this would be breaking change.

No, this would be just refactoring =) We have a solid test suite and a nice Kotlin type system, so even huge refactorings are not a problem. 

>What do you think about prefixing all keyword token types with KW_, e.g. KW_TYPE, KW_UNSIZED? 

I think that while `TYPE` is a single exceptional case it is fine to deal with it specially. I personally prefer `WHILE` to `KW_WHILE` in parser code, so while we don't have at least `n` collisions, I think we can live without `KW_`. 

>The same idea might be applied to operators - OP_xxx.

I've been thinking recently about changing `LPAREN` and friends to `'('` alternatives which are more readable.

File: src/main/kotlin/org/rust/lang/core/grammar/rust.bnf (hunk 2 above)
Comment (matklad) [inline src/main/kotlin/org/rust/lang/core/grammar/rust.bnf]: I agree that this is indeed unfortunate, but `ret_type_spec` does not feel better. It trades API implemeter convenience (I don't have to single it out in the `extends` regexp) for API consumer convenience (I have to add `spec` to code working with functions, although it doesn't add any information to `ret_type` part)
