### PR TITLE
Don't remove unused imports marked with `#[allow(unused_imports)]`

### LINKED ISSUE #9857: "Optimize Imports" removes `#[allow(unused_imports)]` imports
## Environment

* **IntelliJ Rust plugin version:** 0.4.184.5057-222
* **Rust toolchain version:** 1.67.0-nightly (77e57db38 2022-10-30) x86_64-pc-windows-msvc
* **IDE name and version:** PyCharm 2022.2.4 Community Edition (PC-222.4459.20)
* **Operating system:** Windows 10 10.0
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.macros.proc

## Problem description
In the embedded space it is common to import a panic handler crate. 
This import is "unused" but required for the `#[panic_handler]` to be registered. 

It would be nice if "Optimize Imports" could ignore imports marked with `#[allow(unused_imports)]`

## Steps to reproduce
```rust
#[allow(unused_imports)]
use panic_halt as _;
```
"Code | Optimize Imports"

### PR DESCRIPTION
**Pull request by dima74**
Fixes #9857

changelog: Don't remove unused imports marked with `#[allow(unused_imports)]`

### CODE REVIEW

File: src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt [hunk 1]
```diff
@@ -46,7 +46,7 @@ enum class RsLint(
      */
     fun levelFor(el: PsiElement): RsLintLevel = explicitLevel(el) ?: superModsLevel(el) ?: defaultLevel
 
-    private fun explicitLevel(el: PsiElement): RsLintLevel? = el.ancestors
+    fun explicitLevel(el: PsiElement): RsLintLevel? = el.ancestors
```
Comment (vlad20012) [inline src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt:49]: Hmm, `el.contexts` does not properly work for items expanded from macros, but can't suggest `el.contexts` here because attributes on a macro itself should also be accounted

**Review by vlad20012 — APPROVED** [review]
Let's fix issues with macros and add tests with them in a separate PR.

bors r+
