### PR TITLE
INSP&COMP: Use exceptions to check whether index is updating

### LINKED ISSUE #6812: "Crate not found" false positive in Cargo.toml after enabling "Local Crates Index"
## Environment

* **IntelliJ Rust plugin version:** 0.3.141.3655-203-nightly
* **Rust toolchain version:** 1.49.0 (e1884a8e3 2020-12-29) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.3.2 (CL-203.7148.70)
* **Operating system:** macOS 10.15.6
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

While testing #6439 I enabled `org.rust.crates.local.index` experimental feature. It triggers "Crate not found" false positive (the crate is installed and compilation / running works OK). Cache invalidation doesn't help to resolve the problem

not_found

## Steps to reproduce

```toml
[dependencies]
xml-rs = "*"
```

My log: [idea.log](https://github.com/intellij-rust/intellij-rust/files/5938924/idea.log).

### PR DESCRIPTION
**Pull request by avrong**
Part of #6463
Fixes #6812

Check for the readiness of the crates local index before performing completions and inspections. This should reduce the number of false-positives happening while the index is not ready yet.

### CODE REVIEW

File: toml/src/main/kotlin/org/rust/toml/inspections/CrateNotFoundInspection.kt [hunk 1]
```diff
@@ -55,7 +55,10 @@ class CrateNotFoundInspection : TomlLocalInspectionToolBase() {
             if (property in dependency.properties) return
         }
 
-        if (CratesLocalIndexService.getInstance().getCrate(dependency.crateName) == null) {
+        val cratesService = CratesLocalIndexService.getInstance()
+        if (cratesService.isUpdating) return
```
Comment (ortem) [inline toml/src/main/kotlin/org/rust/toml/inspections/CrateNotFoundInspection.kt:59]: Discussed in person that it might be better to throw an exception in case of the service update

**Review by ortem — CHANGES_REQUESTED** [review]

File: toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt [hunk 2]
```diff
@@ -26,8 +27,12 @@ class LocalCargoTomlDependencyCompletionProvider : TomlKeyValueCompletionProvide
         val prefix = CompletionUtil.getOriginalElement(keyValue.key)?.text ?: return
 
         val indexService = CratesLocalIndexService.getInstance()
+        val crateNames = try {
+             indexService.getAllCrateNames()
```
Comment (ortem) [inline toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt:31]: Formatting

File: toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt [hunk 3]
```diff
@@ -58,7 +63,12 @@ class LocalCargoTomlDependencyCompletionProvider : TomlKeyValueCompletionProvide
 
         val indexService = CratesLocalIndexService.getInstance()
 
-        val versions = indexService.getCrate(name)?.sortedVersions ?: return
+        val versions = try {
```
Comment (ortem) [inline toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt:66]: Let's extract `sortedVersions` from the try-catch
```Kotlin
val crate = try {
    cratesService.getCrate(name)
} catch (e: CratesIndexNotReadyException) {
    return
}
val versions = crate?.sortedVersions ?: return
```
and drop whitespace before this line for consistency with `completeKey`

File: toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt [hunk 4]
```diff
@@ -125,24 +125,32 @@ class CratesLocalIndexServiceImpl
         this.state = state
     }
 
+    @Throws(CratesLocalIndexException::class)
```
Comment (ortem) [inline toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt:128]: Let's annotate the interface method instead.

Also, I'd recommend adding a descriptive doc comment like
```Kotlin
/**
 * @throws CratesLocalIndexException if ...
 * @return CargoRegistryCrate ...
 * @return `null` ...
 */
```

File: toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt [hunk 5]
```diff
@@ -125,24 +125,32 @@ class CratesLocalIndexServiceImpl
...
         return try {
-            crates.get(crateName)
+            crates?.get(crateName)
         } catch (e: IOException) {
             LOG.error("Failed to get crate $crateName", e)
             null
         }
     }
 
+    @Throws(CratesLocalIndexException::class)
```
Comment (ortem) [inline toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt:143]: See comment on `getCrate`

File: toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt [hunk 6]
```diff
@@ -125,24 +125,32 @@ class CratesLocalIndexServiceImpl
         this.state = state
     }
 
+    @Throws(CratesLocalIndexException::class)
     override fun getCrate(crateName: String): CargoRegistryCrate? {
-        if (isUpdating.get() || crates == null) return null
+        when {
```
Comment (ortem) [inline toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt:130]: Let's replace `when` with two `if`s. This allows Kotlin compiler to infer that `crates` is  not null

File: toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt [hunk 7]
```diff
@@ -125,24 +125,32 @@ class CratesLocalIndexServiceImpl
...
         } catch (e: IOException) {
             LOG.error("Failed to get crate $crateName", e)
             null
         }
     }
 
+    @Throws(CratesLocalIndexException::class)
     override fun getAllCrateNames(): List<String> {
-        if (isUpdating.get() || crates == null) return emptyList()
+        when {
```
Comment (ortem) [inline toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt:145]: See comment on `getCrate`

File: toml/src/main/kotlin/org/rust/toml/inspections/CrateNotFoundInspection.kt [hunk 8]
```diff
@@ -55,9 +56,11 @@ class CrateNotFoundInspection : TomlLocalInspectionToolBase() {
             if (property in dependency.properties) return
         }
 
-        if (CratesLocalIndexService.getInstance().getCrate(dependency.crateName) == null) {
-            holder.registerProblem(dependency.crateNameElement, "Crate ${dependency.crateName} not found")
-        }
+        try {
```
Comment (ortem) [inline toml/src/main/kotlin/org/rust/toml/inspections/CrateNotFoundInspection.kt:59]: Let's put safe code outside try-catch, e.g.
```Kotlin
val crate = try {
    CratesLocalIndexService.getInstance().getCrate(dependency.crateName)
} catch (e: CratesLocalIndexException) {
    return
}
if (crate == null) {
    holder.registerProblem(dependency.crateNameElement, "Crate ${dependency.crateName} not found")
}
```

File: toml/src/main/kotlin/org/rust/toml/inspections/CrateNotFoundInspection.kt [hunk 9]
```diff
@@ -55,9 +56,11 @@ class CrateNotFoundInspection : TomlLocalInspectionToolBase() {
...
+            if (CratesLocalIndexService.getInstance().getCrate(dependency.crateName) == null) {
```
Comment (ortem) [inline toml/src/main/kotlin/org/rust/toml/inspections/CrateNotFoundInspection.kt:60]: BTW I notice that you use two different styles of accessing to the index:
```Kotlin
val cratesService = CratesLocalIndexService.getInstance()
cratesService.getCrate(crateName)
```
and
```Kotlin
CratesLocalIndexService.getInstance().getCrate(crateName)
```

Please choose only one of them for the code style consistency. I'd recommend the second one since the instance variable is accessed only once.

**Review by ortem — CHANGES_REQUESTED** [review]

File: toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt [hunk 10]
```diff
@@ -295,6 +297,8 @@ class CratesLocalIndexServiceImpl
     }
 }
 
+class CratesLocalIndexException(message: String) : Exception(message)
```
Comment (ortem) [inline toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt:300]: Let's move this class to `CratesLocalIndexService.kt`

File: toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt [hunk 11]
```diff
@@ -126,7 +126,8 @@ class CratesLocalIndexServiceImpl
     }
 
     override fun getCrate(crateName: String): CargoRegistryCrate? {
-        if (isUpdating.get() || crates == null) return null
+        if (isUpdating.get()) throw CratesLocalIndexException("Index is being updated")
+        else if (crates == null) throw CratesLocalIndexException("PersistentHashMap is not available")
```
Comment (ortem) [inline toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt:130]: `else` is redundant, the same in `getAllCrateNames`

**Review by ortem — APPROVED** [review]
LGTM except for minor comments

**Comment by ortem** [comment]
bors retry

**Comment by ortem** [comment]
bors retry
