### PR TITLE
MACRO: refresh `MacroExpansionFileSystem` after project reopening

### LINKED ISSUE #9592: Can't find expanded impls after invalidating caches
## Environment

* **IntelliJ Rust plugin version:** 0.4.180.4932-222
* **Rust toolchain version:** 1.64.0 (a55dd71d5 2022-09-19) x86_64-pc-windows-msvc
* **IDE name and version:** IntelliJ IDEA 2022.2.3 Ultimate Edition (IU-222.4345.14)
* **Operating system:** Windows 10 10.0
* **Macro expansion:** enabled

## Problem description

I'm getting a lot of false positives because the analysis fails to recognize traits like Copy (but also Display, ...), even on primitive types like `u64` or `f64`.

image

Sometimes the errors disappear after 2-3 minutes, sometimes not. Sometimes they disappear after an Invalidate, sometimes not.

I didn't have so many problems with earlier versions of the plugin, something must have changed, is there a separate, slower process that examines the code in background?

## Steps to reproduce

The example is taken from this crate (I'm also joining the project since I modified it - it's WIP so my version doesn't compile). It frequently happens in all projects though, which makes the plugin _very_ hard to use at the moment.

- https://github.com/dtolnay/dragonbox
- revision 830d0483bdb048d83b270dd4228e8cf4a31cefbf of master (the last one, the project is not maintained anymore)
- file src/to_chars.rs
- lines 27-29 in function `to_chars`

This particular file has 51 similar errors, mostly on native types.

[idea-logs-20221021-1105434832648817802330266.zip](https://github.com/intellij-rust/intellij-rust/files/9837493/idea-logs-20221021-1105434832648817802330266.zip)

[dragonbox-master.zip](https://github.com/intellij-rust/intellij-rust/files/9837508/dragonbox-master.zip)

### PR DESCRIPTION
**Pull request by vlad20012**
This leads to properly removal of stale macro expansion after for performing "Invalidate Caches and Restart" without checking any checkbox

Fixes #9592

### CODE REVIEW

**Comment by dima74** [comment]
Looks like it fixes #9592 👍

File: src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt [hunk 1]
```diff
@@ -87,6 +88,15 @@ class MacroExpansionTask(
 
     private fun updateMacrosFiles(allDefMaps: List<CrateDefMap>) {
         val contentRoot = "/$MACRO_EXPANSION_VFS_ROOT/$projectDirectoryName"
+
+        if (lastUpdatedMacrosAt.isEmpty()) {
```
Comment (dima74) [inline src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt:92]: Is it ok that refresh can happen several times if `allDefMaps` are empty for some reason?

Comment (vlad20012) [reply src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt]: Ok, I've changed it to `if (lastUpdatedMacrosAt.isEmpty() && allDefMaps.isNotEmpty())`, in this case it seems impossible to execute it twice. And in the case when `allDefMaps.isEmpty()` there isn't a macro expansion anyway

**Review by dima74 — APPROVED** [review]
bors r+
