### PR TITLE
MACRO&RES: support arbitrary items expanded from custom derive

### LINKED ISSUE #7365: Support items generated by snafu derive macro
Here is the use-case:

Cargo.toml:

```toml
[package]
name = "snafu-jetbrains"
version = "0.1.0"
edition = "2018"

[dependencies]
snafu = "0.6"
```

main.rs

```rust
use snafu::Snafu;

/// The error type for this library.
#[derive(Debug, Snafu)]
enum Error {
    #[snafu(display("This is always an error:: {}", message))]
    AlwaysError { message: String },
}

fn hello_world() -> Result<(), Error> {
    AlwaysError {
        message: "this is a struct created by snafu",
    }
    .fail()
}

fn main() {
    hello_world().unwrap()
}
```

Problem:

image

Desired behavior: code completion should be available for the struct `AlwaysError`:

image

Desired behavior: context actions should provide the ability to fill in missing struct fields for the `AlwaysError` struct.

image

Thank you! 🚀

_Originally posted by @webern in https://github.com/intellij-rust/intellij-rust/issues/6908#issuecomment-860922178_

### PR DESCRIPTION
**Pull request by vlad20012**
Depends on #7194

changelog: Take into account all kinds of items generated by custom derive procedural macros. Previously only `impl` blocks were accounted. Please, note that procedural macro expansion is experimental. If you want to try it, enable `org.rust.cargo.evaluate.build.scripts` and `org.rust.macros.proc` experimental features

### CODE REVIEW

**Comment by webern** [comment]
Best feature ever!!! 🎉 🍾 🍰 🍺  😄 😎

**Comment by webern** [comment]
I wanted to try using this. I'm on macOS using Intellij Ultimate 2021.2.1. I don't know anything about Gradle and Kotlin. It seems like the RunCLion run configuration got pretty far before it encountered some compilation errors such as:
- Unresolved reference: openapiext 
- Unresolved reference: isUnitTestMode

I downloaded the JDK 11 via File->Project Structure->Project Settings->Project SDK which now says corretto-11 and got the same result.

Is there a common mistake that I'm making or step that I'm overlooking?

Thanks.

image

**Comment by vlad20012** [comment]
@webern It looks like something went very wrong :D
I can't figure out what's happened. I can suggest clearing the build cache using `./gradlew clean` and then try to run `RunCLion` configuration again

**Comment by Undin** [comment]
`./gradlew :plugin:buildPlugin -PplatformVersion=212` is enough to build the plugin for all compatible IDE including IDEA and CLion

**Comment by webern** [comment]
> @webern You can build the plugin with `./gradlew :plugin:buildPlugin -PplatformVersion=212 -PbaseIDE=clion` (change `clion` to `idea` if you're going to install it into IDEA and `212` to `211` if you're going to install it into 2021.1.* IDEs) and then install it into your IDE from `plugin/build/distributions` via `Install plugin from disk...` action found in `Settings > Plugins`.

I have done this and am using this successfully in CLion. It's a game-changer, thank you!

**Review by webern — APPROVED** [review]
Tested by installing the plugin in CLion. It works great. Not an expert on the codebase though so I haven't reviewed the code.

**Comment by webern** [comment]
One thing I've noticed is the code inside of some functions or blocks no longer gets analyzed. For example an 'async_trait' impl block is not analyzed.

```
[async_trait]
impl MyTrait {
    fn foo() {
        // no syntax highlighting, code completion, jump to definition, etc is available here
    }
}
```

I think most users will consider this a regression.

**Comment by vlad20012** [comment]
@webern it's because in your case the macro is not expanded successfully:

image

Analysis works fine if a macro is used correctly and expanded successfully:

image

**Comment by webern** [comment]
I've taken a closer look at this. Only certain expansions are not working. For example:
- Automatic expansion of a `match`
- Struct field expansion.

Here is a complete example:

Cargo.toml

```toml
[package]
name = "untitled18"
version = "0.1.0"
edition = "2018"

[dependencies]
async-trait = "=0.1.51"
tokio = { version = "=1.11.0", default-features = false, features = [ "macros", "rt-multi-thread" ] }
```

main.rs

```rust
struct SomeStruct {
    field_number_1: u32,
    field_number_2: u64,
}

enum SomeEnum {
    VariantA,
    VariantB,
    VariantC,
}

#[async_trait::async_trait]
trait SomeTrait {
    async fn foo(&self, some_enum: SomeEnum) -> SomeStruct;
}

struct TraitImpl {}

#[async_trait::async_trait]
impl SomeTrait for TraitImpl {
    async fn foo(&self, some_enum: SomeEnum) -> SomeStruct {
        let mut some_struct = SomeStruct {
            field_number_1: 0,
            field_number_2: 1,
        };

        match some_enum {
            SomeEnum::VariantA => some_struct.field_number_1 = 1,
            SomeEnum::VariantB => some_struct.field_number_1 = 2,
            SomeEnum::VariantC => some_struct.field_number_1 = 3,
        }

        some_struct
    }
}

const x: SomeEnum = SomeEnum::VariantC;

#[tokio::main]
async fn main() {
    let trait_impl = TraitImpl {};

    let _ = match x {
        SomeEnum::VariantB => trait_impl.foo(x).await,
        _ => panic!("boo"),
    };
}
```

Notice that if you delete the fields in the struct instantiation, there is no red underline and no context action to fill in the missing struct fields:

image

Also, if you delete the match arms in either the async main function, or the trait implementation, there is no context action to fill in the missing match arms:

image

**Comment by webern** [comment]
Is this still on track for testing and release? I'm having even more trouble with async_trait blocks than before, where syntax highlighting and code completion is not working for many things. But I wouldn't want that to block this PR because the Rust Plugin experience is definitely better with this PR than without it!

File: src/main/kotlin/org/rust/lang/core/resolve2/ModCollectorBase.kt [hunk 1]
```diff
@@ -627,10 +680,36 @@ private fun DataOutput.writePath(path: Array<String>) {
...
+    if (this !is RsAttrProcMacroOwner) return false
+    val attr = ProcMacroAttribute.getProcMacroAttributeWithoutResolve(
+        this,
+        explicitCrate = crate,
+        withDerives = true
+    )
+    return when (attr) {
+        ProcMacroAttribute.None -> false
+        is ProcMacroAttribute.Attr -> true
+        is ProcMacroAttribute.Derive -> !attr.derives.none()
```
Comment (dima74) [inline src/main/kotlin/org/rust/lang/core/resolve2/ModCollectorBase.kt:713]:
```suggestion
        is ProcMacroAttribute.Derive -> attr.derives.any()
```

**Review by dima74 — APPROVED** [review]
🔥

**Comment by vlad20012** [comment]
bors r=dima74

**Comment by vlad20012** [comment]
bors r=dima74

**Comment by lz1998** [comment]
Yesterday, this feature works well. Today I update CLion to 2021.3 and this problem occurs again.
