### PR TITLE
TYPE: Add type hints to type placeholders

### LINKED ISSUE #5126: Type hints for type placeholders
## Environment

* **IntelliJ Rust plugin version:** 0.2.119.3022-201-nightly
* **Rust toolchain version:** 1.44.0-nightly (1057dc97a 2020-03-20) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.1 EAP (CL-201.6487.17)
* **Operating system:** macOS 10.15.3

## Problem description

image

## Steps to reproduce
```rust
fn main() {
    let nums: Vec<_> = vec![1, 2, 3];
    let nums = nums;
}

```

### PR DESCRIPTION
**Pull request by avrong**
Closes #5126.

Added support of the cases I can predict. Implemented it simultaneously iterating over calculated types and written ones. If there is a better way, happy to know :)

image_2020-04-05_09-38-32

### CODE REVIEW

**Comment by Stzx** [comment]
Can a test unit be provided?

**Comment by Undin** [comment]
@avrong Thanks for contribution!
The current tests for inlay type hints are located in `org.rust.ide.hints.RsInlayTypeHintsProviderTestBase`

File: src/main/kotlin/org/rust/ide/hints/RsInlayTypeHintsProvider.kt [hunk 1]
```diff
@@ -126,6 +130,20 @@ class RsInlayTypeHintsProvider : InlayHintsProvider<RsInlayTypeHintsProvider.Set
                 }
             }
 
+            private fun presentTypeArguments(declaration: RsLetDecl) {
+                val fullType = declaration.pat?.childOfType<RsPatBinding>()?.type ?: return
```
Comment (ortem) [inline src/main/kotlin/org/rust/ide/hints/RsInlayTypeHintsProvider.kt:134]: This code does not work in case of complex patterns like these:
```Rust
let (xs, ys): (Vec<_>, Vec<_>) = (vec![1,2,3], vec![true, false]);
let S { x, y }: S<_> = S { x: 1, y: 2 };
```

Probably, all you have to do to support such cases is replace this line with
```Kotlin
val fullType = declaration.pat?.type ?: return
```

And please don't forget to add such tests

File: src/main/kotlin/org/rust/ide/hints/RsInlayTypeHintsProvider.kt [hunk 2]
```diff
@@ -126,6 +130,20 @@ class RsInlayTypeHintsProvider : InlayHintsProvider<RsInlayTypeHintsProvider.Set
                 }
             }
 
+            private fun presentTypeArguments(declaration: RsLetDecl) {
```
Comment (ortem) [inline src/main/kotlin/org/rust/ide/hints/RsInlayTypeHintsProvider.kt:133]: Maybe `presentTypePlaceholders`?

Comment (ortem) [reply src/main/kotlin/org/rust/ide/hints/RsInlayTypeHintsProvider.kt:133]: Also, please add a setting enabled by default for this hint kind (see `org.rust.ide.hints.RsInlayTypeHintsProvider.Settings`). It allows the user to disable some kinds of hints.

File: src/test/kotlin/org/rust/ide/hints/RsInlayTypeHintsProviderTestBase.kt [hunk 3]
```diff
@@ -71,6 +71,29 @@ abstract class RsInlayTypeHintsProviderTestBase : RsTestBase() {
         }
     """)
 
+    fun `test type placeholder`() = checkByText("""
+    fn main() {
```
Comment (ortem) [inline src/test/kotlin/org/rust/ide/hints/RsInlayTypeHintsProviderTestBase.kt:75]: Please add indents to the code inside your tests, like inside other our tests

File: src/main/kotlin/org/rust/ide/hints/RsInlayTypeHintsProvider.kt (hunk 1 above)
Comment (guslen) [reply src/main/kotlin/org/rust/ide/hints/RsInlayTypeHintsProvider.kt:134]: Hi, just as a note on the side. This statement:
```Rust
val fullType = declaration.pat?.type ?: return
```
does not fully solve the issue.
the above stated example doesn't seem to resolve the types correctly.

the statement:
```Rust
let (xs, ys): (Vec<_>, Vec<_>) = (vec![1,2,3], vec![true, false]);
```
evaluates to:
Screenshot 2020-04-18 at 12 22 02

File: src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt [hunk 4]
```diff
@@ -123,26 +127,31 @@ fun Ty.walkShallow(): Iterator<Ty> {
...
         is TyTraitObject ->
-            stack.addAll(parentTy.trait.subst.types)
+            parentTy.trait.subst.types.reversed().forEach(stack::push)
         is TyTuple ->
-            stack.addAll(parentTy.types)
+            parentTy.types.asReversed().forEach(stack::push)
         is TyFunction -> {
-            stack.addAll(parentTy.paramTypes)
-            stack.add(parentTy.retType)
+            parentTy.paramTypes.asReversed().forEach(stack::push)
```
Comment (ortem) [inline src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt:153]: Return type should be pushed before parameters' types

File: src/test/kotlin/org/rust/ide/hints/RsInlayTypeHintsProviderTestBase.kt [hunk 5]
```diff
@@ -71,6 +71,45 @@ abstract class RsInlayTypeHintsProviderTestBase : RsTestBase() {
         }
     """)
 
+    fun `test type placeholder`() = checkByText("""
+        fn main() {
+                let a: _/*hint text="[:  i32]"*/ = 42;
```
Comment (ortem) [inline src/test/kotlin/org/rust/ide/hints/RsInlayTypeHintsProviderTestBase.kt:76]:
```suggestion
            let a: _/*hint text="[:  i32]"*/ = 42;
```

**Comment by ortem** [comment]
@avrong Welcome to IJ Rust contributors!

bors r+
