### PR TITLE
Properly check spelling in lifetimes

### LINKED ISSUE #5551: CLion Spell Checker incorrectly reports 'static as a typo.
## Environment

* **IntelliJ Rust plugin version:** 0.2.123.3132-201
* **Rust toolchain version:** 1.46.0-nightly (feb3536eb 2020-06-09) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2020.2 EAP (CL-202.5103.16)
* **Operating system:** Windows 10 10.0

## Problem description
'static is incorrectly reported as a typo.

## Steps to reproduce
```rust
impl<A, F> Future for Task<A, F>
where
    F: Future<Output = A> + Send + Sync + 'static,
{
}
```

The spell checker highlights 'static as having a typo. The ' is required by the Rust language.

### PR DESCRIPTION
**Pull request by Undin**
These changes fix text extraction from lifetime identifiers for spell checking and fix false-positive typo annotations in lifetimes like `'static`

Fixes #5551

### CODE REVIEW

File: src/main/kotlin/org/rust/ide/spelling/RsNameIdentifierOwnerTokenizer.kt [hunk 1]
```diff
@@ -32,10 +34,13 @@ object RsNameIdentifierOwnerTokenizer : Tokenizer<RsNameIdentifierOwner>() {
...
         val text = identifier.text
-        val unescapedText = text.unescapeIdentifier()
-        if (text.startsWith(RS_RAW_PREFIX)) {
-            offset += 2
+        val (unescapedText, offsetShift) = if (identifier.elementType == RsElementTypes.QUOTE_IDENTIFIER) {
+            text.removePrefix("'") to 1
+        } else {
+            val offsetShift = if (text.startsWith(RS_RAW_PREFIX)) 2 else 0
+            text.unescapeIdentifier() to offsetShift
         }
```
Comment (mchernyavsky) [inline src/main/kotlin/org/rust/ide/spelling/RsNameIdentifierOwnerTokenizer.kt:42]: Minor:

```suggestion
        val (unescapedText, offsetShift) = when {
            identifier.elementType == RsElementTypes.QUOTE_IDENTIFIER -> text.removePrefix("'") to 1
            text.startsWith(RS_RAW_PREFIX) -> text.unescapeIdentifier() to 2
            else -> text to 0
        }
```

**Comment by Undin** [comment]
bors r=mchernyavsky
