### PR TITLE
Fix memory categorization of rvalue expressions

### LINKED ISSUE #2696: "Cannot borrow immutable as mutable" when the code is correct
## Environment

* **Intellij-Rust plugin version:** 0.2.0.2372-181-nightly
* **IDE name and version:** IntelliJ IDEA 2018.1.6 (Ultimate Edition), Build #IU-181.5540.7
* **Operating system:** Linux

## Problem description
The IDE reports a "Cannot borrow immutable as mutable" error (indicated by a red underline) when there are no real errors in the code.

## Steps to reproduce

Create a new binary project with the following code:
```rust
fn main() {
  let x = vec![1];
  if x.iter().any(|c| *c == 2) {

  }
}
```
The IDE highlights `x.iter()`. The popup message says:

> Cannot borrow immutable local variable `x.iter()` as mutable less... (Ctrl+F1) 
Implements simple cases of borrow checking.

### PR DESCRIPTION
**Pull request by ortem**
Fixes #2696

### CODE REVIEW

File: src/main/kotlin/org/rust/lang/core/types/infer/MemoryCategorization.kt [hunk 1]
```diff
@@ -123,14 +126,22 @@ private fun processDeref(baseCmt: Cmt): Cmt {
     }
 }
 
+private fun processRvalue(expr: RsExpr): Cmt =
+    Cmt(expr.type, MutabilityCategory.Declared)
+
+private fun isRvalue(expr: RsExpr): Boolean =
```
Comment (Undin) [inline src/main/kotlin/org/rust/lang/core/types/infer/MemoryCategorization.kt]: Maybe create some marker interface for this expression types to use `expr is RsSomeInterfaceName` instead of this function?

Comment (ortem) [reply src/main/kotlin/org/rust/lang/core/types/infer/MemoryCategorization.kt]: Actually this code is redundant.
