### PR TITLE
INT: Support intention preview

### LINKED ISSUE #9431: Exception occurred while .toml file editing
## Environment

* **IntelliJ Rust plugin version:** 0.4.180.4908-223-nightly
* **Rust toolchain version:** 1.64.0 (a55dd71d5 2022-09-19) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2022.3 EAP Ultimate Edition (IU-223.4884.69)
* **Operating system:** macOS 12.6
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.cargo.emulate.terminal, org.rust.cargo.evaluate.build.scripts

## Problem description

Exception occurred while files was editing 

<details>

```
Exceptions occurred on invoking the intention 'Expand dependency specification' on a copy of the file.

java.lang.IllegalStateException: Needs write action
	at org.rust.openapiext.UtilsKt.checkWriteAccessAllowed(utils.kt:98)
	at org.rust.ide.intentions.RsElementBaseIntentionAction.invoke(RsElementBaseIntentionAction.kt:46)
	at com.intellij.codeInsight.intention.BaseElementAtCaretIntentionAction.invoke(BaseElementAtCaretIntentionAction.java:76)
	at com.intellij.codeInsight.intention.IntentionAction.generatePreview(IntentionAction.java:145)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.generatePreview(IntentionActionWrapper.java:96)
	at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching$MyIntentionAction.generatePreview(IntentionActionWithTextCaching.java:241)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.invokePreview$lambda-3$lambda-2(IntentionPreviewComputable.kt:137)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.lambda$postponeFormattingInside$2(PostprocessReformattingAspect.java:140)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.postponeFormattingInside(PostprocessReformattingAspect.java:148)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.postponeFormattingInside(PostprocessReformattingAspect.java:139)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.invokePreview$lambda-3(IntentionPreviewComputable.kt:137)
	at com.intellij.codeInsight.intention.preview.IntentionPreviewUtils.previewSession(IntentionPreviewUtils.java:94)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.invokePreview(IntentionPreviewComputable.kt:135)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.generatePreview(IntentionPreviewComputable.kt:95)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.tryCreateDiffContent$lambda-1(IntentionPreviewComputable.kt:61)
	at com.intellij.model.SideEffectGuard.computeWithAllowedSideEffects(SideEffectGuard.java:25)
	at com.intellij.model.SideEffectGuard.computeWithoutSideEffects(SideEffectGuard.java:18)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.tryCreateDiffContent(IntentionPreviewComputable.kt:61)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.call(IntentionPreviewComputable.kt:39)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.call(IntentionPreviewComputable.kt:34)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:536)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:501)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:71)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:130)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:111)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:67)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:190)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:592)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:667)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:177)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:67)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:108)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:71)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:501)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:408)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>

### LINKED ISSUE #9450: Exception after renaming variable by quick fix in 2022.3
## Environment

* **IntelliJ Rust plugin version:** 0.4.180.4910-223-nightly
* **Rust toolchain version:** 1.64.0 (a55dd71d5 2022-09-19) x86_64-apple-darwin
* **IDE name and version:** CLion 2022.3 EAP (CL-223.4884.72)
* **Operating system:** macOS 12.5.1
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description

<details>

```
Access is allowed from event dispatch thread only

com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false
Current thread: Thread[ApplicationImpl pooled thread 2665,4,main] 1729723718
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 2040388664
	at com.intellij.openapi.application.impl.ApplicationImpl.throwThreadAccessException(ApplicationImpl.java:1042)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1025)
	at com.intellij.openapi.application.impl.LaterInvocator.getCurrentModalityState(LaterInvocator.java:278)
	at com.intellij.openapi.application.impl.ApplicationImpl.getCurrentModalityState(ApplicationImpl.java:446)
	at com.intellij.openapi.application.ModalityState.current(ModalityState.java:70)
	at org.rust.ide.inspections.fixes.RenameFix.invoke(RenameFix.kt:48)
	at com.intellij.codeInspection.LocalQuickFixOnPsiElement.applyFix(LocalQuickFixOnPsiElement.java:100)
	at com.intellij.codeInspection.LocalQuickFixOnPsiElement.applyFix(LocalQuickFixOnPsiElement.java:90)
	at com.intellij.codeInspection.LocalQuickFixOnPsiElement.applyFix(LocalQuickFixOnPsiElement.java:22)
	at com.intellij.codeInspection.LocalQuickFix.generatePreview(LocalQuickFix.java:99)
	at com.intellij.codeInspection.ex.QuickFixWrapper.generatePreview(QuickFixWrapper.java:131)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.invokePreview$lambda-3$lambda-2(IntentionPreviewComputable.kt:137)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.lambda$postponeFormattingInside$2(PostprocessReformattingAspect.java:140)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.postponeFormattingInside(PostprocessReformattingAspect.java:148)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.postponeFormattingInside(PostprocessReformattingAspect.java:139)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.invokePreview$lambda-3(IntentionPreviewComputable.kt:137)
	at com.intellij.codeInsight.intention.preview.IntentionPreviewUtils.previewSession(IntentionPreviewUtils.java:94)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.invokePreview(IntentionPreviewComputable.kt:135)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.generatePreview(IntentionPreviewComputable.kt:95)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.tryCreateDiffContent$lambda-1(IntentionPreviewComputable.kt:61)
	at com.intellij.model.SideEffectGuard.computeWithAllowedSideEffects(SideEffectGuard.java:25)
	at com.intellij.model.SideEffectGuard.computeWithoutSideEffects(SideEffectGuard.java:18)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.tryCreateDiffContent(IntentionPreviewComputable.kt:61)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.call(IntentionPreviewComputable.kt:39)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.call(IntentionPreviewComputable.kt:34)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:536)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:501)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:71)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:130)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:111)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:67)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:190)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:592)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:667)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:177)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:67)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:108)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:71)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:501)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:408)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

</details>

## Steps to reproduce

```rust
fn main() {
    let t = 8;
    let try = 7;
}
```
Use quick fix with renaming:
image
This exception occurs not only after use but after this quick fix becomes focused like on screenshot ^.

### PR DESCRIPTION
**Pull request by dima74**
I removed `checkWriteAccessAllowed` in `RsElementBaseIntentionAction` when intention is running in preview mode, so the preview can be generated correctly, and then checked all our intentions and disabled preview generation for intentions which are not intended to have a preview or are hard to support (so they should be handled in separate PRs).

Fixes #9431
Fixes #9450
Meta: #9561

---

Intentions which are not intended to have a preview:
- AddImplTraitIntention - user has to choose trait manually
- ConvertToStructIntention, ConvertToTupleIntention - shows dialog
- AddFmtStringArgumentIntention - shows popup

Intentions for which preview may be added in future:
- CreateFunctionIntention, CreateStructIntention, CreateTupleStructIntention
- AddImportForPatternIntention when one candidate
- AddImportIntention
- IntroduceLocalVariableIntention

changelog: Support [Intention preview](https://blog.jetbrains.com/idea/2022/09/intellij-idea-2022-3-eap/#Intention_action_preview_enabled_by_default) in 2022.3

### CODE REVIEW

File: src/main/kotlin/org/rust/ide/intentions/ExtractInlineModuleIntention.kt [hunk 1]
```diff
@@ -23,9 +23,6 @@ class ExtractInlineModuleIntention : RsElementBaseIntentionAction<RsModItem>() {
     override fun getFamilyName() = "Extract inline module structure"
     override fun getText() = "Extract inline module"
 
-    // No intention preview because it creates new file
-    override fun getFileModifierForPreview(target: PsiFile): FileModifier? = null
```
Comment (dima74) [inline src/main/kotlin/org/rust/ide/intentions/ExtractInlineModuleIntention.kt:27]: I changed it because disabling preview via `getFileModifierForPreview` only works for `LocalQuickFix` and not for `IntentionAction`

**Review by Undin — COMMENTED** [review]
@dima74 I've looked at preview support recently and cherry-picked a code to check preview for all our intentions. It should find **all** intentions where preview doesn't work. But I didn't adjust tests for concrete intentions. 

Also, it would be nice to have a list with all intentions where preview is disabled, but we want to make it work in the future in meta issue

File: src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt [hunk 2]
```diff
@@ -332,3 +332,6 @@ fun PsiElement.isKeywordLike(): Boolean {
         else -> false
     }
 }
+
+// BACKCOMPAT: 2022.2. Replace `!isPhysical` with `IntentionPreviewUtils.isPreviewElement(this)`
+val PsiElement.isIntentionPreviewElement: Boolean get() = !isPhysical
```
Comment (Undin) [inline src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt:337]: If it's important, you can create a platform-specific version of this property

**Comment by dima74** [comment]
> @dima74 I've looked at preview support recently and cherry-picked a code to check preview for all our intentions. It should find **all** intentions where preview doesn't work. But I didn't adjust tests for concrete intentions.

Thanks! It finds some more intentions which I also fixed

File: src/test/kotlin/org/rust/IgnoreIntentionPreview.kt [hunk 3]
```diff
@@ -0,0 +1,10 @@
+/*
+ * Use of this source code is governed by the MIT license that can be
+ * found in the LICENSE file.
+ */
+
+package org.rust
+
+@Target(AnnotationTarget.FUNCTION)
+@Retention(AnnotationRetention.RUNTIME)
+annotation class IgnoreIntentionPreview
```
Comment (dima74) [inline src/test/kotlin/org/rust/IgnoreIntentionPreview.kt:10]: I added this annotation for intentions which generate code and add some imports. It is quite difficult to support import insertion in the preview, and imports are not so important part of the preview, so I think for now it is ok to not show imports in the preview

File: src/main/kotlin/org/rust/ide/intentions/addFmtStringArgument/AddFmtStringArgumentIntention.kt [hunk 4]
```diff
@@ -25,6 +26,9 @@ class AddFmtStringArgumentIntention : RsElementBaseIntentionAction<AddFmtStringA
     override fun getText(): String = "Add format string argument"
     override fun getFamilyName(): String = text
 
+    override fun startInWriteAction(): Boolean = false
```
Comment (Undin) [inline src/main/kotlin/org/rust/ide/intentions/addFmtStringArgument/AddFmtStringArgumentIntention.kt:29]: 👍

Comment (Undin) [inline src/main/kotlin/org/rust/ide/intentions/addFmtStringArgument/AddFmtStringArgumentIntention.kt:29]: But it seems our tests think that this intention should have a preview but actually it won't be shown and even doesn't have a lot of sense since result heavily depends on user input. Maybe disable it manually and adjust tests?

File: src/main/kotlin/org/rust/ide/utils/import/importUtils.kt [hunk 5]
```diff
@@ -25,6 +25,9 @@ import org.rust.stdext.isSortedWith
 fun ImportCandidate.import(context: RsElement) = info.import(context)
 
 fun ImportInfo.import(context: RsElement) {
+    // Imports are not very important for intention preview
```
Comment (Undin) [inline src/main/kotlin/org/rust/ide/utils/import/importUtils.kt:28]: Actually, it's not true in all cases, at least from my point of view.
For example, in the case of `Import` quick-fix it's only one meaningful change of the quick-fix. Taking into account complex structure of Ruse `use` items and sorting, it may be quite useful.

But I don't insist on fixing it in this PR, just want to change the comment to emphasise that it's temporarily state, and we want to change it in the future

File: src/main/kotlin/org/rust/ide/utils/template/EditorExt.kt [hunk 6]
```diff
@@ -13,14 +13,15 @@ import com.intellij.openapi.editor.Editor
...
+import org.rust.lang.core.psi.ext.isIntentionPreviewElement
 import org.rust.openapiext.checkWriteAccessAllowed
 
 fun Editor.buildAndRunTemplate(
     owner: PsiElement,
     elementsToReplace: List<SmartPsiElementPointer<out PsiElement>>,
     listener: TemplateEditingListener? = null,
 ) {
-    checkWriteAccessAllowed()
+    if (!owner.isIntentionPreviewElement) checkWriteAccessAllowed()
```
Comment (vlad20012) [inline src/main/kotlin/org/rust/ide/utils/template/EditorExt.kt:24]:
```suggestion
    if (!owner.isIntentionPreviewElement) {
        checkWriteAccessAllowed()
    }
```

File: src/main/kotlin/org/rust/ide/intentions/AddImplTraitIntention.kt [hunk 7]
```diff
@@ -105,4 +107,8 @@ class AddImplTraitIntention : RsElementBaseIntentionAction<AddImplTraitIntention
             tmp.runInline()
         }
     }
+
+    // No intention preview because user has to choose trait manually
+    override fun generatePreview(project: Project, editor: Editor, file: PsiFile): IntentionPreviewInfo =
+        IntentionPreviewInfo.EMPTY
```
[the remark this answers is not in the document]
Comment (Undin) [reply src/main/kotlin/org/rust/ide/intentions/AddImplTraitIntention.kt:113]: Why? `IntentionPreviewInfo.Html` requires providing some text from our side, `IntentionPreviewInfo.EMPTY` leads to intention description as a preview

File: src/test/kotlin/org/rust/IgnoreIntentionPreview.kt (hunk 3 above)
Comment (Undin) [reply src/test/kotlin/org/rust/IgnoreIntentionPreview.kt:10]: As I can see, you use this annotation in cases when preview differs from intention result. Maybe it's better introducing a test API to check custom previews instead of skipping them? Otherwise, it's quite easy to miss something

File: src/222/main/kotlin/org/rust/lang/core/psi/ext/IntentionPreview.kt [hunk 8]
```diff
@@ -0,0 +1,10 @@
+/*
+ * Use of this source code is governed by the MIT license that can be
+ * found in the LICENSE file.
+ */
+
+package org.rust.lang.core.psi.ext
+
+import com.intellij.psi.PsiElement
+
+val PsiElement.isIntentionPreviewElement: Boolean get() = false
```
Comment (Undin) [inline src/222/main/kotlin/org/rust/lang/core/psi/ext/IntentionPreview.kt:10]:
```suggestion
val PsiElement.isIntentionPreviewElement: Boolean get() = !isPhysical
```

File: src/main/kotlin/org/rust/ide/intentions/AddImplTraitIntention.kt (hunk 7 above)
[the remark this answers is not in the document]
Comment (vlad20012) [reply src/main/kotlin/org/rust/ide/intentions/AddImplTraitIntention.kt:113]: Oh, indeed. Fine then

File: src/main/kotlin/org/rust/ide/intentions/addFmtStringArgument/AddFmtStringArgumentIntention.kt (hunk 4 above)
Comment (dima74) [reply src/main/kotlin/org/rust/ide/intentions/addFmtStringArgument/AddFmtStringArgumentIntention.kt:29]: I added

```kotlin
protected open val previewExpected: Boolean get() = intention.startInWriteAction()
```

to the tests, so intention will not have preview and tests know it

File: src/test/kotlin/org/rust/IgnoreIntentionPreview.kt (hunk 3 above)
Comment (dima74) [reply src/test/kotlin/org/rust/IgnoreIntentionPreview.kt:10]: Added `afterPreview` parameter to `RsIntentionTestBase#doAvailableTest` to check preview result. Also I have to inline `RsIntentionTestPlatformBase#checkPreviewAndLaunchAction`, so `RsIntentionTestPlatformBase` is now unused. I will remove it if review is ok

File: src/222/main/kotlin/org/rust/lang/core/psi/ext/IntentionPreview.kt (hunk 8 above)
Comment (dima74) [reply src/222/main/kotlin/org/rust/lang/core/psi/ext/IntentionPreview.kt:10]: I think it should be `false` not to break something. The intention preview will not work in 2022.2, but it is anyway disabled there by default. E.g. we have `RsImplTraitMemberCompletionProvider` which calls `import` on non-physical `PsiElement` (from copy created in completion). This particular case is probably a bug and should be fixed, but potentially there are other cases not covered by tests

File: src/main/kotlin/org/rust/ide/intentions/addFmtStringArgument/AddFmtStringArgumentIntention.kt (hunk 4 above)
Comment (Undin) [reply src/main/kotlin/org/rust/ide/intentions/addFmtStringArgument/AddFmtStringArgumentIntention.kt:29]: I still think it's a good idea to provide `IntentionPreviewInfo.EMPTY` manually because otherwise we will depend on some implementation details which can lead to broken tests/unexpected behaviour in the future

File: src/test/kotlin/org/rust/ide/intentions/RsIntentionTestBase.kt [hunk 9]
```diff
@@ -89,9 +95,22 @@ abstract class RsIntentionTestBase(private val intentionClass: KClass<out Intent
         fileTreeFromText(replaceCaretMarker(fileStructureAfter)).check(myFixture)
     }
 
-    protected fun launchAction() {
+    protected fun launchAction(@Language("Rust") afterPreview: String? = null) {
```
Comment (Undin) [inline src/test/kotlin/org/rust/ide/intentions/RsIntentionTestBase.kt:98]:
```suggestion
    protected fun launchAction(@Language("Rust") preview: String? = null) {
```

File: src/test/kotlin/org/rust/ide/intentions/SpecifyTypeExplicitlyIntentionTest.kt [hunk 10]
```diff
@@ -132,6 +140,7 @@ class SpecifyTypeExplicitlyIntentionTest : RsIntentionTestBase(SpecifyTypeExplic
             fn main() { let var: S = foo(); }
     """)
 
+    @IgnoreIntentionPreview
```
Comment (Undin) [inline src/test/kotlin/org/rust/ide/intentions/SpecifyTypeExplicitlyIntentionTest.kt:143]: Do we still need it in these tests?

File: src/test/kotlin/org/rust/IgnoreIntentionPreview.kt (hunk 3 above)
Comment (Undin) [reply src/test/kotlin/org/rust/IgnoreIntentionPreview.kt:10]: Great!
But do we still need this annotation after the latest changes at all? it seems in such cases, you can just provide custom preview and drop `IgnoreIntentionPreview`
If we still need it, could you add some short doc comment why someone may need it?

File: src/222/main/kotlin/org/rust/lang/core/psi/ext/IntentionPreview.kt (hunk 8 above)
Comment (Undin) [reply src/222/main/kotlin/org/rust/lang/core/psi/ext/IntentionPreview.kt:10]: Ok

File: src/223/test/kotlin/org/rust/ide/intentions/RsIntentionTestPlatformBase.kt [hunk 11]
```diff
@@ -0,0 +1,19 @@
...
+import com.intellij.codeInsight.intention.IntentionAction
+import org.rust.RsTestBase
+
+// BACKCOMPAT: 2022.2. Merge into `RsIntentionTestBase`
+abstract class RsIntentionTestPlatformBase : RsTestBase() {
+    protected fun checkPreviewAndLaunchAction(intention: IntentionAction, preview: String?) {
+        val text = myFixture.getIntentionPreviewText(intention)
+        check(text != null) { "No preview for intention ${intention.text}" }
+        myFixture.launchAction(intention)
+        assertEquals(intention.text, preview ?: myFixture.file.text, text)
```
Comment (Undin) [inline src/223/test/kotlin/org/rust/ide/intentions/RsIntentionTestPlatformBase.kt:17]: Let's add some message to `assertEquals`  to explain a developer what happened. Intention preview is quite a new feature, so a developer can just not know about it

**Review by Undin — APPROVED** [review]

**Comment by dima74** [comment]
bors r=Undin
