### PR TITLE
MACRO: fixed expansions of a macro with empty group (cfg_if! case)

### LINKED ISSUE #2601: cfg_if macro expansion
Macros like `cfg_if` don't seem to be expanding, even with macro expansion option enabled.

It's most noticeable in `std::os` and crates like `libc` or other FFI crates that make heavy use of `cfg_if` and similar macros.

### PR DESCRIPTION
**Pull request by vlad20012**
FIxes #2601

### CODE REVIEW

File: src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt [hunk 1]
```diff
@@ -164,10 +168,17 @@ class MacroExpander(val project: Project) {
                     child.macroExpansionContents?.let { contents ->
```
Comment (fedochet) [inline src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt]: I guess this needs some refactorings :sweat_smile:

File: src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt [hunk 2]
```diff
@@ -380,6 +395,45 @@ private fun PsiBuilder.isSameToken(psi: PsiElement): Boolean {
...
+        CachedValueProvider.Result.create(
+            collectAvailableVars(this),
+            PsiModificationTracker.MODIFICATION_COUNT // TODO use modtracker attached to the macro
+        )
+    }
+
+private fun collectAvailableVars(groupDefinition: RsMacroBindingGroup): Set<String> {
+    val vars = groupDefinition.descendantsOfType<RsMacroBinding>().toMutableList()
+
+    fun go(psi: PsiElement): Unit = when (psi) {
```
Comment (ortem) [inline src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt]: Move `when (psi) {` to a new line
