### PR TITLE
INSP: Fixed wrong trait import suggestion for trait objects

### LINKED ISSUE #2822: Good Code Red: Type aliased trait wants to be imported
## Environment

* **Intellij-Rust plugin version:** Version: 0.2.0.2104-182
* **Rust toolchain version:** Any
* **IDE name and version:** CLion 2018.2
* **Operating system:** Mac OS X

## Problem description

Good code red:

If I use a type alias for a trait, intellij-rust marks it red and offers to import the original trait.

If I import the original trait, the code is green, but rustc will warn about the unecessary import.

## Steps to reproduce

```rust
type XX = ::std::io::Write;

struct YY {}

impl ::std::io::Write for YY {
    fn write(&mut self, _buf: &[u8]) -> Result<usize, ::std::io::Error> { Ok(0) }

    fn flush(&mut self) -> Result<(), ::std::io::Error> { Ok(()) }
}

pub fn main() {
    let mut x: Box<XX> = Box::new(YY {});
    x.write(&[]); // write is red but compiles fine
}
```
screen shot 2018-09-04 at 09 14 27

### PR DESCRIPTION
**Pull request by vlad20012**
FIxes #2822

### CODE REVIEW

File: src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt [hunk 1]
```diff
@@ -643,35 +643,35 @@ private fun processAssociatedItems(
 ): Boolean {
     val traitBounds = (type as? TyTypeParameter)?.getTraitBoundsTransitively()
     val visitedInherent = mutableSetOf<String>()
-    fun processTraitOrImpl(traitOrImpl: RsTraitOrImpl, inherent: Boolean): Boolean {
+    fun processTraitOrImpl(traitOrImpl: TraitImplKind, inherent: Boolean): Boolean {
```
Comment (Undin) [inline src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt]: Let's rename `traitOrImpl` to be consistent with new type name

File: src/main/kotlin/org/rust/lang/core/resolve/Processors.kt [hunk 2]
```diff
@@ -101,7 +100,7 @@ data class AssocItemScopeEntry(
     override val name: String,
     override val element: RsElement,
     override val subst: Substitution = emptySubstitution,
-    val impl: RsImplItem?
+    val Source: TraitImplKind
```
Comment (Undin) [inline src/main/kotlin/org/rust/lang/core/resolve/Processors.kt]: `Source` -> `source`

File: src/main/kotlin/org/rust/lang/core/resolve/ref/RsMethodCallReferenceImpl.kt [hunk 3]
```diff
@@ -105,9 +105,10 @@ data class MethodResolveVariant(
     override val element: RsFunction,
     /**
      * If the method defined in impl, this is the impl. If the method inherited from
-     * trait definition, this is the impl of the actual trait for the receiver type
+     * trait definition, this is the impl of the actual trait for the receiver type.
+     * Otherwise it's just a trait the method defined in
```
Comment (Undin) [inline src/main/kotlin/org/rust/lang/core/resolve/ref/RsMethodCallReferenceImpl.kt]: I'd replace "this is the impl/trait" by "this contains impl/trait" because now `source` is container for `RsTraitOrImpl`
