### PR TITLE
ANN: Fix union pattern match error

### LINKED ISSUE #5071: Confusing an union for a struct when using `match`
## Environment

* **IntelliJ Rust plugin version:**
0.2.117.2170-193

* **Rust toolchain version:**
rustc 1.41.1 (f3e1a954d 2020-02-24)
binary: rustc
commit-hash: f3e1a954d2ead4e2fc197c7da7d71e6c61bad196
commit-date: 2020-02-24
host: x86_64-pc-windows-msvc
release: 1.41.1
LLVM version: 9.0

* **IDE name and version:**
Build #IC-193.6494.35 (IntelliJ IDEA 2019.3.3 Community Edition)

* **Operating system:**
Windows 10

## Problem description
The plugin seem to confuse an union for a struct when using `match`, thus
presenting the error "Struct pattern does not match field 'f'" where f is not supposed to be matched at the same line.

## Steps to reproduce
Defining the next union:
```rust
union TestUnion {
    i: i32,
    f: f32
}
```

and matching with the next code:
```rust
fn test_function(tu: TestUnion) {
 unsafe {
   match tu {
            TestUnion { i: 42 } => { println!(" The meaning of.. la la la la la "); }
            TestUnion { f } = > { println!("Farewell and thanks for the fish, {} ", f); }
   } // match
 } // unsafe
} // fn
```

The code however compiles without issues.

### PR DESCRIPTION
**Pull request by Stzx**
Fixes #5071 

During the fix process, the following problems were found:

- Enter `u`, `union` keyword without prompt
- ~There are still problems with `union` automatic fix~
- `Union` does not detect if it exists in an `unsafe` block

### CODE REVIEW

**Comment by ortem** [comment]
Hi @Stzx, thank you for PR and for exploring other problems related to unions. I've opened a separate issue #5138 for the first problem you described, but I didn't quite understand the second and third problems. Could you please describe them in more detail?

**Comment by Stzx** [comment]
> * There are still problems with `union` automatic fix

See here: [unions - pattern-matching-on-unions](https://doc.rust-lang.org/reference/items/unions.html#pattern-matching-on-unions)

When the following code appears:
```rust
union TestUnion { i: i32, f: f32 }

fn main() {
    let tu = TestUnion { i: 1 };

    unsafe {
        match tu {
            <error descr="Struct pattern does not mention field `f` [E0027]">TestUnion { i }</error> => {}
            // after: TestUnion { i, f } => {}
            // This fix is wrong
        }
    }
}

```

----

> * `Union` does not detect if it exists in an `unsafe` block

See here: [unions - reading-and-writing-union-fields](https://doc.rust-lang.org/reference/items/unions.html#reading-and-writing-union-fields)
```rust
union TestUnion {  i: i32, }

fn main() {
    let tu = TestUnion { i: 1 };

    if tu.i == 1 {
        println!("Hello!");
    }
}
```
The read for `union` is not in the `unsafe` block, but the IDE does not prompt an error. Write operation has the same problem.

**Comment by ortem** [comment]
@Stzx thanks for noticing, I've updated our issue on unsafe #3013.

File: src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt [hunk 1]
```diff
@@ -1185,6 +1185,26 @@ sealed class RsDiagnostic(
             )
         }
     }
+
+    class MissingFieldsInUnionPattern(pat: RsPat) : RsDiagnostic(pat) {
+        override fun prepare(): PreparedAnnotation {
+            return PreparedAnnotation(
+                ERROR,
+                NONE,
```
Comment (ortem) [inline src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt]: JFYI: I think it's strange that there is no error code for this case. So I've opened the corresponding [issue](https://github.com/rust-lang/rust/issues/70620)

File: src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt [hunk 2]
```diff
@@ -1195,7 +1215,8 @@ enum class RsErrorCode {
     E0403, E0404, E0407, E0415, E0424, E0426, E0428, E0433, E0449, E0451, E0463,
     E0518, E0562, E0569, E0583, E0586, E0594,
     E0603, E0614, E0616, E0618, E0624, E0658, E0666, E0667, E0688, E0695,
-    E0704, E0732;
+    E0704, E0732,
+    NONE;
```
Comment (ortem) [inline src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt]: Let's use `null` instead of `RsErrorCode.NONE`

File: src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt [hunk 3]
```diff
@@ -115,13 +115,27 @@ class RsErrorAnnotator : AnnotatorBase(), HighlightRangeExtension {
...
-            RsDiagnostic.ExtraFieldInStructPattern(it).addToHolder(holder)
-        }
-        if (missingFields.isNotEmpty() && patStruct.patRest == null) {
-            RsDiagnostic.MissingFieldsInStructPattern(patStruct, declaration, missingFields).addToHolder(holder)
+
+        if (declaration is RsStructItem && declaration.kind == RsStructKind.UNION) {
+            extraFields.forEach { RsDiagnostic.ExtraFieldInStructPattern(it, "union").addToHolder(holder) }
+
+            val extraFieldNames = extraFields.map { it.kind.fieldName }
+            val bodyFieldNames = bodyFields.filter { it.kind.fieldName !in extraFieldNames }
```
Comment (ortem) [inline src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt]: Consider this case from your tests:
```Rust
union TestUnion { i: i32, f: f32 }

fn test_fun(tu: TestUnion) {
    unsafe {
        match tu {
            TestUnion { x } => {}
        }
    }
}
```

Rustc omits only one error: `union U does not have a field named a`.
I think it's enough and we should not omit two errors in this case, and then you can just use `bodyFields` instead of `bodyFieldNames`. What do you think?

**Comment by ortem** [comment]
@Stzx Thank you!

bors r+
