### PR TITLE
INT: fix nesting of renamed imports

### LINKED ISSUE #9284: Nest use statements is incorrect for renamed imports
## Environment

* **IntelliJ Rust plugin version:** 0.4.178.4845-222-nightly
* **Rust toolchain version:** 1.65.0-nightly (addacb587 2022-08-24) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2022.2.1 (CL-222.3739.54)
* **Operating system:** Linux 5.4.0-124-generic
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description

The refactoring "Nest use statements produces invalid code when the nesting module  is renamed in the import.

## Steps to reproduce

```rust
mod one {
    pub fn two() {}
}
use /*caret*/one as ein;
use one::two;
```

Apply "Nest use statements":

```rust
mod one {
    pub fn two() {}
}

use one::{
    /*caret*/one as ein,
    two
};
```

### PR DESCRIPTION
**Pull request by afetisov**
Closes #9284

The intention code is quite hacky, parsing and replacing strings instead of working with proper PSI elements and respecting the code style & formatting. I'm considering reworking it in a different PR, but here I'm following the already used hacks,

changelog: fix nesting of renamed imports

### CODE REVIEW

**Comment by afetisov** [comment]
@dima74 Hey, how's it going? It's been two weeks.

File: src/test/kotlin/org/rust/ide/intentions/NestUseStatementsIntentionTest.kt [hunk 1]
```diff
@@ -335,4 +335,129 @@ class NestUseStatementsIntentionTest : RsIntentionTestBase(NestUseStatementsInte
         };
 
     """)
+
+    fun `test renamed import 1`() = doAvailableTest("""
+        pub mod foo {
+            pub fn bar() {}
+            pub fn quux() {}
+        }
```
Comment (dima74) [inline src/test/kotlin/org/rust/ide/intentions/NestUseStatementsIntentionTest.kt:343]: Existing tests don't contain declarations and the intention is purely syntactic, so probably we can remove it

File: src/main/kotlin/org/rust/ide/intentions/NestUseStatementsIntention.kt [hunk 2]
```diff
@@ -78,13 +78,16 @@ class NestUseStatementsIntention : RsElementBaseIntentionAction<NestUseStatement
...
-            if (useSpeck.path?.referenceName == basePath && useGroup != null) {
-                useGroup.useSpeckList.map { it.text }
-            } else {
-                listOf(deleteBasePath(useSpeck.text, basePath))
+            if (useSpeck.path?.referenceName == basePath) {
+                // Remove first group
+                useSpeck.useGroup?.let { useGroup ->
+                    return@flatMap useGroup.useSpeckList.map { it.text }
+                }
+                useSpeck.alias?.let { alias ->
```
Comment (dima74) [inline src/main/kotlin/org/rust/ide/intentions/NestUseStatementsIntention.kt:86]: This case works incorrect:
```rust
fn main() {
    x();
}

mod a {
    pub fn a() {}
    pub fn b() {}
}

use a::a as x;
use a::b;
```

**Review by dima74 — COMMENTED** [review]
Actually I am very interested about the use case of this intention. I thought it is low level and rarely used. Could you please describe a bit when you use it? Probably we should improve import optimizer somehow

File: src/main/kotlin/org/rust/ide/intentions/NestUseStatementsIntention.kt (hunk 2 above)
Comment (afetisov) [reply src/main/kotlin/org/rust/ide/intentions/NestUseStatementsIntention.kt:86]: Fixed and added to tests.

**Comment by afetisov** [comment]
> I thought it is low level and rarely used. 

I don't think there is anything wrong with low-level intentions. Yes, they may be more work to apply, but they are super reliable, predictable and easy to use. The high-level code transformations may depend on AST, semantics analysis, project data and who knows what else, with a myriad of options and subtle bugs. The low-level transformation does a simple obvious thing and does it well, so it's useful when the high-level analysis fails, when you need to do something tricky and unanticipated, or just when you feel like applying a simple code transformation.

On the "rarely used" part I obviously don't have any statistics, but personally I use it a lot. 

In principle, there are many knobs which could be added to the automatic import formatter & optimizer to make it more usable. It should break long imports over several lines. It should allow merging several short imports from submodules into a single use group automatically. It should allow one-click shift between "every import is its own `use` item" and "imports are maximally grouped" styles. But all of that is a rather complex algorithm, which is hard to implement, fickle to configure, and may be just unusable under some weird style requirements. It should certainly be added in principle, but there is no reason to not improve the simple intentions.

**Review by dima74 — APPROVED** [review]
bors r+

**Comment by dima74** [comment]
bors retry
