### PR TITLE
Up/Down mover: add a trailing comma even when there are multiple elements in the last line

### LINKED ISSUE #7522: Move vec macro arguments not working when missing a comma
## Environment

* **IntelliJ Rust plugin version:** 0.4.152.3985-211-nightly
* **Rust toolchain version:** null
* **IDE name and version:** CLion 2021.1.3 (CL-211.7628.27)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

Moving `vec!` macro arguments down and then up when some arguments are in a single line and missing a comma, fails.

### Fails
```rust
fn main() {
   let v = vec![
      "a",
      "b",/*caret. Move statement down*/
      "c", "d"
   ];
}
```
```rust
fn main() {
   let v = vec![
      "a",
      "c", "d"
      "b",/*caret. Try to move statement up. Doesn't work.*/
   ];
}
```
### Works
A
```rust
fn main() {
   let v = vec![
      "a",
      "b",/*caret. Move statement down*/
      "c", "d",
   ];
}
```
```rust
fn main() {
   let v = vec![
      "a",
      "c", "d",
      "b",/*caret. Try to move statement up. Works.*/
   ];
}
```
B
```rust
fn main() {
   let v = vec![
      "a",
      "b",
      "c", /*caret. Move statement down*/
      "d"
   ];
}
```
```rust
fn main() {
   let v = vec![
      "a",
      "b",
      "d",
      "c",/*caret. Try to move statement up. Works.*/
   ];
}
```

### PR DESCRIPTION
**Pull request by t-kameyama**
Fixes #7522

### CODE REVIEW

File: src/main/kotlin/org/rust/ide/formatter/processors/RsTrailingCommaFormatProcessor.kt [hunk 1]
```diff
@@ -97,10 +96,11 @@ fun CommaList.addTrailingCommaForElement(list: PsiElement): Boolean {
     return true
 }
 
-fun CommaList.isLastElement(list: PsiElement, element: PsiElement): Boolean {
+fun CommaList.isOnSameLineAsLastElement(list: PsiElement, element: PsiElement, document: Document): Boolean {
```
Comment (ortem) [inline src/main/kotlin/org/rust/ide/formatter/processors/RsTrailingCommaFormatProcessor.kt:99]: Let's make it `private`

Comment (ortem) [reply src/main/kotlin/org/rust/ide/formatter/processors/RsTrailingCommaFormatProcessor.kt:99]: Looks like passing `document` is redundant since it can be accessed via `element.containingFile.document`

File: src/main/kotlin/org/rust/ide/formatter/processors/RsTrailingCommaFormatProcessor.kt [hunk 2]
```diff
@@ -97,10 +96,11 @@ fun CommaList.addTrailingCommaForElement(list: PsiElement): Boolean {
...
     check(list.elementType == this.list && isElement(element))
     val rbrace = list.lastChild
     if (rbrace.elementType != closingBrace) return false
-    val lastElement = rbrace.getPrevNonCommentSibling() ?: return false
-    return lastElement == element
+    val lastElement = rbrace.getPrevNonCommentSibling()?.takeIf(isElement) ?: return false
+    return lastElement == element ||
+        document.getLineNumber(lastElement.endOffset) == document.getLineNumber(element.startOffset)
```
Comment (ortem) [inline src/main/kotlin/org/rust/ide/formatter/processors/RsTrailingCommaFormatProcessor.kt:105]:
```suggestion
        document.getLineNumber(lastElement.endOffset) == document.getLineNumber(element.endOffset)
```
Not sure but it looks more reasonable to use `endOffset`. For example, it will work when `element` is multi-line (e.g. a struct initialization) and the last element is located on the same line. WDYT?

**Review by ortem — CHANGES_REQUESTED** [review]

File: src/main/kotlin/org/rust/ide/formatter/processors/RsTrailingCommaFormatProcessor.kt (hunk 1 above)
Comment (t-kameyama) [reply src/main/kotlin/org/rust/ide/formatter/processors/RsTrailingCommaFormatProcessor.kt:99]: Cannot be private.

File: src/main/kotlin/org/rust/ide/formatter/processors/RsTrailingCommaFormatProcessor.kt (hunk 2 above)
Comment (t-kameyama) [reply src/main/kotlin/org/rust/ide/formatter/processors/RsTrailingCommaFormatProcessor.kt]: Fixed it and added a [test](https://github.com/t-kameyama/intellij-rust/blob/25121a99efafc2d9a9171d1b3c0af73d5d64f706/src/test/kotlin/org/rust/ide/actions/mover/RsCommaListElementUpDownMoverTest.kt#L372-L392).

File: src/main/kotlin/org/rust/ide/formatter/processors/RsTrailingCommaFormatProcessor.kt (hunk 1 above)
Comment (ortem) [reply src/main/kotlin/org/rust/ide/formatter/processors/RsTrailingCommaFormatProcessor.kt]: Oh, right. I didn't notice it's a different file

**Review by ortem — APPROVED** [review]
@t-kameyama Thank you!
bors r+
