### PR TITLE
(MISC) Source code links in panics and stacktraces

### LINKED ISSUE #720: Make backtrace frames clickable from test runner window
It should be possible to format backtraces such that IntelliJ automatically links them to the corresponding source. 

FILENAME:LINE, with no leading whitespace, appears to work in CLion.

### PR DESCRIPTION
**Pull request by alygin**
I've added source code links for panics and stack backtraces output the same way they are added to the compiler messages now.

In this outuput:

    thread 'main' panicked at 'something went wrong', src/main.rs:24
    stack backtrace:
       1:        0x10df17d88 - std::sys::backtrace::tracing::imp::write::hb03a0f85d9cccd1b
       2:        0x10df1983f - std::panicking::default_hook::{{closure}}::h945d25329ef3fdd6
       3:        0x10df18dd5 - std::panicking::default_hook::hc98de28314f7e4d1
       4:        0x10df19326 - std::panicking::rust_panic_with_hook::hf47d6a84575c96f5
       5:        0x10df11f33 - std::panicking::begin_panic::hc373b7d24bec0770
       6:        0x10df121e9 - ptest::main::h2cd7a4ff8d266cce
                            at src/main.rs:24
       7:        0x10df19dfa - __rust_maybe_catch_panic
       8:        0x10df18916 - std::rt::lang_start::h95854775e4ac8b95
       9:        0x10df12219 - main

two source code locations will be wrapped into hyperlinks: the one in the very first line and another one between stack positions 6 and 7.

Since `rustc` only emits source code locations in the backtraces on Linux, the PR at least partially fixes #720 on this platform.

I've also extracted the common code from `RustConsoleFilter` to `RegexpFileLinkFilter` and from `RustConsoleFilterTest` to `HighlightFilterTestBase`.

### CODE REVIEW

File: src/main/kotlin/org/rust/cargo/runconfig/RustBacktraceFilter.kt [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+/**
+ * Detects messages about panics and adds source code links to them.
+ */
+class RustBacktraceFilter(
+    project: Project,
+    cargoProjectDir: VirtualFile
+) : RegexpFileLinkFilter(
+    project,
+    cargoProjectDir,
+    "^\\s+at ${RegexpFilter.FILE_PATH_MACROS}:${RegexpFilter.LINE_MACROS}$") {
```
Comment (matklad) [inline src/main/kotlin/org/rust/cargo/runconfig/RustBacktraceFilter.kt]: Empty `{}` could be omitted.

**Comment by matklad** [comment]
Thanks!

**Comment by matklad** [comment]
`createOpenFileHyperlink` currently does not handle absolute paths, I'll fix it.

**Comment by matklad** [comment]
Abs paths fixed in https://github.com/intellij-rust/intellij-rust/commit/c92313d92a14cb7cbfa07f42944a524ea9238577
