### PR TITLE
ANN: don't try to annotate non project files

### LINKED ISSUE #1497: RsCargoCheckAnnotator exception
<details><summary>stacktrace</summary>
<p>

```
Invalid range specified: (1518,1493); 
java.lang.Throwable
        at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:222)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:217)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:213)
	at com.intellij.openapi.util.TextRange.<init>(TextRange.java:43)
	at com.intellij.openapi.util.TextRange.<init>(TextRange.java:32)
	at org.rust.ide.annotator.RsCargoCheckAnnotatorKt.filterMessage(RsCargoCheckAnnotator.kt:158)
	at org.rust.ide.annotator.RsCargoCheckAnnotatorKt.access$filterMessage(RsCargoCheckAnnotator.kt:1)
	at org.rust.ide.annotator.RsCargoCheckAnnotator.apply(RsCargoCheckAnnotator.kt:86)
	at org.rust.ide.annotator.RsCargoCheckAnnotator.apply(RsCargoCheckAnnotator.kt:60)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.a(ExternalToolPass.java:190)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$700(ExternalToolPass.java:47)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.a(ExternalToolPass.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:160)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:277)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:291)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:246)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:246)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:417)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:344)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:384)
	at com.intellij.util.Alarm$Request.run(Alarm.java:395)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

</p>
</details>

### PR DESCRIPTION
**Pull request by Undin**
Closes #1497 

In `RsCargoCheckAnnotator` we check that message belongs to file by [equality of path suffix](https://github.com/intellij-rust/intellij-rust/blob/78754355e3cc823d75292f596d5c4ca1c17b26ad/src/main/kotlin/org/rust/ide/annotator/RsCargoCheckAnnotator.kt#L147-L148) with path from the message. But if the current file is not project file (from stdlib or dependency) and it has path with the same suffix, we calculate offsets for incorrect file and sometimes it can lead to invalid range.

### CODE REVIEW

**Comment by Undin** [comment]
I don't really know how to create test(s) in this case.

File: src/main/kotlin/org/rust/ide/annotator/RsCargoCheckAnnotator.kt [hunk 1]
```diff
@@ -79,6 +82,10 @@ class RsCargoCheckAnnotator : ExternalAnnotator<CargoCheckAnnotationInfo, CargoC
     override fun apply(file: PsiFile, annotationResult: CargoCheckAnnotationResult?, holder: AnnotationHolder) {
         if (annotationResult == null) return
 
+        val fileOrigin = (holder.currentAnnotationSession.file as? RsCompositeElement)
```
Comment (Undin) [inline src/main/kotlin/org/rust/ide/annotator/RsCargoCheckAnnotator.kt]: Can we use `file` from function arguments instead of `holder.currentAnnotationSession.file`?

Comment (matklad) [inline src/main/kotlin/org/rust/ide/annotator/RsCargoCheckAnnotator.kt]: Yeah, I think they are the same. Not 100% sure though!

**Comment by Undin** [comment]
I'll rebase it ASAP

**Comment by Undin** [comment]
Done
