### PR TITLE
REF: fix Extract Variable interaction with closures

### LINKED ISSUE #8229: Extract variable in closure chooses the binding scope incorrectly
## Environment

* **IntelliJ Rust plugin version:** 0.4.162.4282-213-nightly
* **Rust toolchain version:** 1.56.1 (59eed8a2a 2021-11-01) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2021.3 (CL-213.5744.254)
* **Operating system:** Linux 5.4.0-91-generic
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description

If we have a closure whose body is just an expression (with no explicit block), then running "Extract variable" inside the body automatically places the new variable binding within a newly created block body of the closure. This happens even if some occurrences of the extracted expression happen outside of the closure, in which case they will refer to a variable binding which is inaccessible at their scope.

## Steps to reproduce

```rust
fn foo() {
    let _ = false;
    || false/*cursor*/;
    let _ = false;
}
```

Run "Extract variable" at the cursor, selecting expression "false" (or use the `let` postfix template). Choose "Replace all 2 occurences":

```rust
fn foo() {
    let _ = x;
    || {
        let x = false;
        x
    };
    let _ = x;
}
```

### PR DESCRIPTION
**Pull request by afetisov**
Closes #8229 

Previously refactoring didn't consider whether the extracted subexpression of a closure is also used somewhere outside of the closure. This lead to the binding created within the scope of the closure, while the occurrences were replaced regardless of the scope. We move the binding inside of the closure body only if all extracted expressions are within its scope.

changelog: "Introduce local variable" no longer moves the new binding into closure bodies if it is used outside of them

### CODE REVIEW

File: src/main/kotlin/org/rust/ide/refactoring/introduceVariable/impl.kt [hunk 1]
```diff
@@ -70,9 +71,12 @@ private class ExpressionReplacer(
                 binding
             } else {
                 val parentLambda = chosenExpr.ancestorStrict<RsLambdaExpr>()
+                val lambdaMayBeAnchor = parentLambda != null && sortedExprs.all { parentLambda.isAncestorOf(it) }
                 val binding = introduceLet(anchor, let)
                 sortedExprs.forEach { it.replace(name) }
-                binding?.moveIntoLambdaBlockIfNeeded(parentLambda)
+                if (lambdaMayBeAnchor) {
+                    binding.moveIntoLambdaBlockIfNeeded(parentLambda)
+                } else binding
```
Comment (dima74) [inline src/main/kotlin/org/rust/ide/refactoring/introduceVariable/impl.kt:79]: [minor] we use code style where `if/else` braces should presence/absence both simultenuously

```suggestion
                } else {
                    binding
                }
```

**Review by dima74 — APPROVED** [review]
