### PR TITLE
MACRO: support `include!` macro calls generated by another macro call

### LINKED ISSUE #5036: Support include! macro call generated by another macro
## Environment

* **IntelliJ Rust plugin version:** 0.2.117.3001-201-nightly
* **Rust toolchain version:** 1.43.0-nightly (6d69caba1 2020-02-27) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2020.1 EAP Ultimate Edition (IU-201.5616.10)
* **Operating system:** macOS 10.13.6

## Problem description
If `include!` macro call is generated by another macro, the plugin doesn't process such calls and as a result all items from included file cannot be resolved or completed.

See https://github.com/intellij-rust/intellij-rust/issues/1908#issuecomment-593026377 for real world case

## Steps to reproduce
`hello.rs`

```rust
pub fn hello() -> &'static str {
    "Hello!"
}
```

`main.rs`

```rust
macro_rules! generate_include {
    ($package: tt) => {
        include!($package);
    };
}

generate_include!("hello.rs");

fn main() {
    println!("{}", hello());
}

```

### PR DESCRIPTION
**Pull request by Undin**
Note, full support (name resolution and completion for code from including file in included one and correct module hierarchy recognition, i.e. absence of false positive "File is not included in module tree" editor notification), is available only when new macro expansion engine is enabled (#3628)

See https://github.com/intellij-rust/intellij-rust/issues/1908#issuecomment-593026377 for real world use case

Closes #5036

### CODE REVIEW

File: src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt [hunk 1]
```diff
@@ -113,8 +113,7 @@ private val RsExpr.value: String? get() {
 fun RsMacroCall.findIncludingFile(): RsFile? {
     if (macroName != "include") return null
     val path = includeMacroArgument?.expr?.value ?: return null
-    // TODO: it doesn't work if `include!()` macro call comes from other macro
-    val file = containingFile?.originalFile?.virtualFile ?: return null
+    val file = (expandedFrom ?: this).containingFile?.originalFile?.virtualFile ?: return null
```
Comment (Undin) [inline src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt:116]:
```suggestion
    val file = (expandedFromRecursively ?: this).containingFile?.originalFile?.virtualFile ?: return null
```

And need to add the corresponding tests

File: src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt [hunk 2]
```diff
@@ -113,8 +113,7 @@ private val RsExpr.value: String? get() {
 fun RsMacroCall.findIncludingFile(): RsFile? {
     if (macroName != "include") return null
     val path = includeMacroArgument?.expr?.value ?: return null
-    // TODO: it doesn't work if `include!()` macro call comes from other macro
-    val file = containingFile?.originalFile?.virtualFile ?: return null
+    val file = (expandedFromRecursively ?: this).containingFile?.originalFile?.virtualFile ?: return null
```
Comment (Undin) [inline src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt:116]:
```suggestion
    val file = (findMacroCallExpandedFrom() ?: this).containingFile?.originalFile?.virtualFile ?: return null
```

**Comment by Undin** [comment]
@vlad20012 it's ready for review
