### PR TITLE
REF: Use existing impl block in "Extract function" refactoring

### LINKED ISSUE #4520: Extracting method ignores existing impl block
## Environment

* **IntelliJ Rust plugin version:** 0.2.107.2137-192
* **Rust toolchain version:** 1.40 nightly
* **IDE name and version:** CLion 2019.2.4
* **Operating system:** Windows 10

## Problem description

When trying to extract a block of code from a method to a new method, a new impl block for given struct is created even when there's an existing one already.

## Steps to reproduce

```Rust
struct Foo;

trait Bar {
    fn foo();
}

impl Bar for Foo {
   fn foo() {
       // extract some code from here
   }
}

impl Foo {
}

mod tests {
}

// new impl Foo {} block gets created here
```

### PR DESCRIPTION
**Pull request by dima74**
Fixes #4520

changelog: Use existing impl block if possible in "Extract function" refactoring

### CODE REVIEW

File: src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt [hunk 1]
```diff
@@ -75,6 +71,27 @@ class RsExtractFunctionHandler : RefactoringActionHandler {
...
     }
 
+    private fun findExistingInherentImpl(traitImpl: RsImplItem): RsImplItem? {
+        check(traitImpl.traitRef != null)
+        val traitCachedImpl = RsCachedImplItem.forImpl(traitImpl)
+        return (traitImpl.parent as? RsItemsOwner)
+            ?.childrenOfType<RsImplItem>()
+            ?.firstOrNull {
+                it.traitRef == null
+                    && RsCachedImplItem.forImpl(it).typeAndGenerics == traitCachedImpl.typeAndGenerics
```
Comment (ortem) [inline src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt:81]: I'm not sure but maybe `org.rust.lang.core.resolve.RsCachedImplItem#isValid` needs to be checked.
For example, consider the situation when there are several `impl` blocks with `cfg` attributes:
```Rust
impl Bar for S {
    fn foo(&self) {
        // I'd expect the code to be extracted into cfg-enabled impl for `unix`
    }
}

#[cfg(windows)] // disabled
impl S {}

#[cfg(unix)] // enabled
impl S {}
```

File: src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt [hunk 2]
```diff
@@ -75,6 +71,27 @@ class RsExtractFunctionHandler : RefactoringActionHandler {
         }
     }
 
+    private fun findExistingInherentImpl(traitImpl: RsImplItem): RsImplItem? {
+        check(traitImpl.traitRef != null)
+        val traitCachedImpl = RsCachedImplItem.forImpl(traitImpl)
+        return (traitImpl.parent as? RsItemsOwner)
+            ?.childrenOfType<RsImplItem>()
+            ?.firstOrNull {
+                it.traitRef == null
```
Comment (ortem) [inline src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt:80]: [minor] Using `org.rust.lang.core.resolve.RsCachedImplItem#isInherent` might be more consistent with the next check which also operates `RsCachedImplItem`

File: src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt [hunk 3]
```diff
@@ -75,6 +71,27 @@ class RsExtractFunctionHandler : RefactoringActionHandler {
         }
     }
 
+    private fun findExistingInherentImpl(traitImpl: RsImplItem): RsImplItem? {
```
Comment (ortem) [inline src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt:74]: I'd add a descriptive comment about what this method does. For example, it might be not obvious whether it looks into `impl` blocks inside other items or only checks top-level `impl` blocks

**Review by ortem — APPROVED** [review]
LGTM from my perspective, @vlad20012 WDYT?

File: src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt [hunk 4]
```diff
@@ -75,6 +71,32 @@ class RsExtractFunctionHandler : RefactoringActionHandler {
...
+     */
+    private fun findExistingInherentImpl(traitImpl: RsImplItem): RsImplItem? {
+        check(traitImpl.traitRef != null)
+        val traitCachedImpl = RsCachedImplItem.forImpl(traitImpl)
+        return (traitImpl.parent as? RsItemsOwner)
+            ?.childrenOfType<RsImplItem>()
+            ?.firstOrNull { impl ->
+                val cachedImpl = RsCachedImplItem.forImpl(impl)
+                cachedImpl.isInherent && cachedImpl.isValid
+                    && cachedImpl.typeAndGenerics == traitCachedImpl.typeAndGenerics
```
Comment (vlad20012) [inline src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt:86]: This won't work with generic impls, is it intended? If yes, maybe we could express it more explicitly, i.e. skip impls with generics in this condition?

Comment (dima74) [reply src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt]: Generics are currently not supported when new inherent impl is created (#7801), so yes, it is expected. I added explicit check

**Comment by dima74** [comment]
bors r=ortem
