### PR TITLE
DBG: Use RsCodeFragment for gdb/lldb console injection

### LINKED ISSUE #3713: GDB prompt has wrong autocompletion
## Environment

* **Intellij-Rust plugin version:**
master (60ce8a2d813f6d7e818313ebd142b384ad318772)
* **Rust toolchain version:**
1.34
* **IDE name and version:**
CLion 2019.1
Build #CL-191.6183.77, built on March 25, 2019
JRE: 1.8.0_202-release-1483-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-20-generic
* **Operating system:**
Linux Mint 19.1

## Problem description
When I write `p` in the GDB console while debugging, it starts to offer weird suggestions.
For example:
`p b` (I want to print a variable `b`)
the console suggests `pub` and `bfn`, the latter of which triggers the following internal IDE error when selected.
```
java.lang.NullPointerException
	at com.intellij.codeInsight.template.impl.TemplateState.lambda$processAllExpressions$1(TemplateState.java:426)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1054)
	at com.intellij.codeInsight.template.impl.TemplateState.processAllExpressions(TemplateState.java:417)
	at com.intellij.codeInsight.template.impl.TemplateState.start(TemplateState.java:388)
	at com.intellij.codeInsight.template.impl.TemplateManagerImpl.lambda$startTemplate$2(TemplateManagerImpl.java:170)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:212)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:168)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:154)
	at com.intellij.codeInsight.template.impl.TemplateManagerImpl.startTemplate(TemplateManagerImpl.java:174)
	at com.intellij.codeInsight.template.impl.TemplateManagerImpl.startTemplate(TemplateManagerImpl.java:191)
	at com.intellij.codeInsight.template.impl.TemplateManagerImpl.startTemplate(TemplateManagerImpl.java:132)
	at com.intellij.codeInsight.template.impl.LiveTemplateLookupElementImpl.startTemplate(LiveTemplateLookupElementImpl.java:42)
	at com.intellij.codeInsight.template.impl.LiveTemplateLookupElementImpl.handleInsert(LiveTemplateLookupElementImpl.java:36)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$insertItem$8(CodeCompletionHandlerBase.java:596)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1054)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.insertItem(CodeCompletionHandlerBase.java:580)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$insertItemHonorBlockSelection$5(CodeCompletionHandlerBase.java:496)
	at com.intellij.openapi.editor.impl.CaretModelImpl.lambda$runForEachCaret$3(CaretModelImpl.java:354)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:453)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:346)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:336)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.insertItemHonorBlockSelection(CodeCompletionHandlerBase.java:487)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lookupItemSelected(CodeCompletionHandlerBase.java:446)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.itemSelected(CompletionProgressIndicator.java:174)
	at com.intellij.codeInsight.completion.CompletionLookupArrangerImpl.itemSelected(CompletionLookupArrangerImpl.java:189)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.fireItemSelected(LookupImpl.java:967)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.finishLookupInWritableFile(LookupImpl.java:588)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.lambda$finishLookup$13(LookupImpl.java:540)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:212)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:168)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:154)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.finishLookup(LookupImpl.java:540)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.finishLookup(LookupImpl.java:525)
	at com.intellij.codeInsight.lookup.impl.actions.ChooseItemAction$Handler.execute(ChooseItemAction.java:69)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doExecute(EditorActionHandler.java:178)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:216)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:103)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:215)
	at com.intellij.openapi.editor.actionSystem.EditorAction.lambda$actionPerformed$0(EditorAction.java:102)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:111)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:86)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:260)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:277)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:624)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:673)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:672)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:520)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:475)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:217)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:671)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

I think that either the autocomplete in GDB console should be turned off or it should only offer suggestions containing local variable names and similar things. The suggestions are the same for LLDB.

If you can point me to the place where the debugger suggestions are generated, I could try to fix/improve it (if you consider this an issue).

### PR DESCRIPTION
**Pull request by ortem**
Fixes #3713

dbg_console_comp

### CODE REVIEW

File: debugger/src/main/kotlin/org/rust/debugger/RsBackendConsoleInjectionHelper.kt [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+
+class RsBackendConsoleInjectionHelper : BackendConsoleInjectionHelper {
+    override fun subscribeToInjection(session: XDebugSession) {
+        val connection = session.project.messageBus.connect()
+
+        val listener = object : RsDebugInjectionListener, XDebugSessionListener {
+            @Volatile
+            private var document: Document? = null
+
+            override fun evalDebugContext(host: PsiLanguageInjectionHost, context: RsDebugInjectionListener.DebugContext) {
```
Comment (mchernyavsky) [inline debugger/src/main/kotlin/org/rust/debugger/RsBackendConsoleInjectionHelper.kt]: This method doesn't use state of listener at all, so it can be moved into `RustParserDefinition`. In this case you can make `DebugContext.element` final.

File: debugger/src/main/kotlin/org/rust/debugger/RsBackendConsoleInjectionHelper.kt [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+            override fun didInject(host: PsiLanguageInjectionHost) {
+                if (host is GDBExpressionPlaceholder) {
+                    val document = host.getContainingFile().originalFile.viewProvider.document ?: return
+                    this.document = document
+                }
+            }
+
+            override fun stackFrameChanged() {
+                val document = document ?: return
+                val file = FileDocumentManager.getInstance().getFile(document) ?: return
```
Comment (mchernyavsky) [inline debugger/src/main/kotlin/org/rust/debugger/RsBackendConsoleInjectionHelper.kt]: We have `Document.virtualFile` property in `openapiext/utils.kt`.

File: debugger/src/main/kotlin/org/rust/debugger/RsBackendConsoleInjectionHelper.kt (hunk 1 above)
Comment (ortem) [reply debugger/src/main/kotlin/org/rust/debugger/RsBackendConsoleInjectionHelper.kt]: It cannot be moved because of using `CidrDebugProcess.DEBUG_PROCESS_KEY`

File: debugger/src/main/kotlin/org/rust/debugger/RsBackendConsoleInjectionHelper.kt [hunk 3]
```diff
@@ -0,0 +1,62 @@
...
+            override fun didInject(host: PsiLanguageInjectionHost) {
+                if (host is GDBExpressionPlaceholder) {
+                    val document = host.originalDocument ?: return
+                    this.document = document
+                }
+            }
+
+            override fun stackFrameChanged() {
+                val document = document ?: return
+                val file = document.virtualFile ?: return
```
Comment (mchernyavsky) [inline debugger/src/main/kotlin/org/rust/debugger/RsBackendConsoleInjectionHelper.kt]:
```kotlin
val document = document ?: return
val file = document.virtualFile ?: return
```
to
```kotlin
val file = document?.virtualFile ?: return
```

File: debugger/src/main/kotlin/org/rust/debugger/RsBackendConsoleInjectionHelper.kt [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+            override fun evalDebugContext(host: PsiLanguageInjectionHost, context: RsDebugInjectionListener.DebugContext) {
+                val document = host.originalDocument ?: return
+                val process = document.getUserData(CidrDebugProcess.DEBUG_PROCESS_KEY) ?: return
+                context.element = process.debuggerContext?.ancestorOrSelf()
+            }
+
+            override fun didInject(host: PsiLanguageInjectionHost) {
+                if (host is GDBExpressionPlaceholder) {
+                    val document = host.originalDocument ?: return
+                    this.document = document
```
Comment (mchernyavsky) [inline debugger/src/main/kotlin/org/rust/debugger/RsBackendConsoleInjectionHelper.kt]:
```kotlin
val document = host.originalDocument ?: return
this.document = document
```
to
```kotlin
document = host.originalDocument ?: return
```
