### PR TITLE
(GRAM): parse tuple expressions faster

### LINKED ISSUE #251: Indexing rustc sources takes infinite amount of time
Steps to reproduce:

* download and unpack https://static.rust-lang.org/dist/rustc-1.6.0-src.tar.gz
* open `rustc-1.6.0` in IDEA
* wait forever until indexing is done.

Quick profiling again points to error related functions in `ParserUtils`, so it may be the same issue as https://github.com/intellij-rust/intellij-rust/issues/230.

@alexeykudinkin can this be fixed in https://github.com/intellij-rust/intellij-rust/tree/recovering ?

### PR DESCRIPTION
**Pull request by matklad**
Fixes #251 

@alexeykudinkin please review. I've tried to use existing `injectInto` custom rule here, but it didn't generate `getLparen` accessor.

### CODE REVIEW

File: src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt [hunk 1]
```diff
@@ -60,6 +61,31 @@ object RustParserUtil : GeneratedParserUtilBase() {
         return false;
     }
 
+    // Parses either a paren_expr (92) or a tuple_expr (92, ) by postponing the decision of
+    // what exactly is parsed util `,` is (not) seen.
```
Comment (alexeykudinkin) [inline src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt]: `until`

Comment (matklad) [inline src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt]: fixed

File: src/test/resources/org/rust/lang/core/parser/fixtures/well-formed/way_too_many_parens.rs [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))
+;
+
+static k: (i32,) =
+(((((((((((((((((((((((((((((((((((((((((((((((((((((((((((
+1,
+)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))
+;
+
+fn main() {}
```
Comment (alexeykudinkin) [inline src/test/resources/org/rust/lang/core/parser/fixtures/well-formed/way_too_many_parens.rs]: Please, add the test for the reciprocal case:

```
static i: () =
(((((((((((((((((((((((((((((((((((((((((((((((((((((((((((
1,
),),),),),),),),),),),),),),),),),),),),),),),),),),),),),),),),),),),),),),),),),),),),),),),),),),),),),),),),),),)
;
```

Comment (matklad) [inline src/test/resources/org/rust/lang/core/parser/fixtures/well-formed/way_too_many_parens.rs]: Nice idea! Especially because it requires to tests the same thing in the types part of grammar. We don't have this problem there though, because we don't distinguish parenthesized and tuple types. 

fixed
