### PR TITLE
REF: Fix inlining async function

### LINKED ISSUE #10333: Fails to inline functions like async fn foo() -> Result<()>
## Environment

* **IntelliJ Rust plugin version:** 0.4.191.5293-231
* **Rust toolchain version:** 1.70.0-nightly (22f247c6f 2023-03-13) aarch64-apple-darwin
* **IDE name and version:** CLion 2023.1.1 (CL-231.8109.222)
* **Operating system:** macOS 13.2.1
* **Macro expansion:** enabled

## Problem description
```rust
use eyre::Result;
async fn test_inline() -> Result<()> {
    let x = foo().await?;
    Ok(())
}
async fn foo() -> Result<()> {
    let a = 1;
    Ok(a)
}
```
after inlining foo(), I got
```rust
use eyre::Result;

async fn test_inline() -> Result<()> {
    let a = 1;
    let x = Ok(a).await?;
    Ok(())
}
```

It has two problems.

1. Ok(a)? is unnecessary
2. usage of await is incorrect and it doesn't compile anymore

### PR DESCRIPTION
**Pull request by dima74**
Fixes #10333

changelog: Fix handling async function in `Inline function` refactoring

### CODE REVIEW

File: src/main/kotlin/org/rust/ide/refactoring/inlineFunction/RsInlineFunctionProcessor.kt [hunk 1]
```diff
@@ -409,6 +405,23 @@ private class InlineSingleUsage(
...
+            is FunctionCallUsage -> usage.functionCall
+            is MethodCallUsage -> usage.methodCall.parent as RsDotExpr
+        }
+        return functionCall.unwrapAwait() ?: functionCall
+    }
+
+    // `foo().await` -> `foo()`
+    //  ~~~~~ [this]
+    private fun RsExpr.unwrapAwait(): RsExpr? {
+        if (!originalFunction.isAsync) return null
```
Comment (vlad20012) [inline src/main/kotlin/org/rust/ide/refactoring/inlineFunction/RsInlineFunctionProcessor.kt:419]: Maybe it worth it to add a test with awaited non-async function (which returns `impl Future<>`) explicitly?

**Review by vlad20012 — APPROVED** [review]

**Comment by dima74** [comment]
bors retry
