### PR TITLE
GRAM: fix `&raw` expression parsing

### LINKED ISSUE #5105: Failure to parse reference to variable named raw
## Environment

* **IntelliJ Rust plugin version:** 0.2.119.3016-193-nightly
* **Rust toolchain version:** 1.42 stable / 1.43 nightly 2020-03-11
* **IDE name and version:** IntelliJ IDEA 2019.3.3 Ultimate
* **Operating system:** Windows 10 x64

## Problem description
Plugin fails to parse a reference to a variable named raw.

## Steps to reproduce

```rust
fn main() {
    let raw = "text".to_owned();
    let mut new = String::with_capacity(raw.len() + 2);
    new.push('"');
    new.push_str(&raw);
    new.push('"');
    println!("{}", new);
}
```

The `r` in `&raw` is highlighted red with `<expr> expected, got 'raw'`. Code compiles and runs without problems. (This is a reduced form of code I wrote earlier today)

### PR DESCRIPTION
**Pull request by vlad20012**
Fixes #5105. The bug was introduced in #5081

### CODE REVIEW

File: src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt [hunk 1]
```diff
@@ -571,14 +571,24 @@ object RustParserUtil : GeneratedParserUtilBase() {
     ): Boolean {
         // Tricky: the token can be already remapped by some previous rule that was backtracked
         if (b.tokenType == elementType ||
-            b.tokenText == keyword && b.tokenType == IDENTIFIER && nextElementPredicate(b.lookAhead(1))) {
+            b.tokenType == IDENTIFIER && b.tokenText == keyword && nextElementPredicate(b.lookAhead(1))) {
```
Comment (vlad20012) [inline src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt]: just swapped text & token type comparison in the condition

File: src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt [hunk 2]
```diff
@@ -571,14 +571,24 @@ object RustParserUtil : GeneratedParserUtilBase() {
...
             b.remapCurrentToken(elementType)
             b.advanceLexer()
             return true
         }
         return false
     }
 
+    private fun contextualKeywordRollbackable(b: PsiBuilder, keyword: String, elementType: IElementType): Boolean {
```
Comment (Undin) [inline src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt]:
```suggestion
    private fun contextualKeywordWithRollback(b: PsiBuilder, keyword: String, elementType: IElementType): Boolean {
```

Maybe it's better?

**Comment by Undin** [comment]
bors r=mchernyavsky
