### PR TITLE
Initial support of multiple module declarations of the same module

### LINKED ISSUE #2586: E0603:  Module is private
It appears that this plugin, when used with PyCharm, is flagging all file-based modules as private with error E0603. It does not flag modules defined in the file being used. This red warning is displayed when importing the module.

Eg: main.rs has 
`mod mymod;`

Another file has
`use mymod;`
or `use mymod::{MyStruct};`

mymod (after use) has the zigzag with E0603 warning.

### LINKED ISSUE #3757: "Module is private" when "mod a;" is in lib.rs and main.rs
## Environment

* **Intellij-Rust plugin version:** v0.2.98.2618-191-nightly
* **Rust toolchain version:** stable
* **IDE name and version:** CLion 2019.1.2
* **Operating system:** Linux

## Problem description
False positive E0603.

## Steps to reproduce
`lib.rs`:
```
use crate::a::x;
mod a;
```
`main.rs`:
```
use crate::a::x;
fn main() {}
mod a;
```
`a.rs`:
```
pub fn x() {}
```
The error message highlights `use crate::a::x` in `main.rs`. Sometimes it happens in `lib.rs` instead.

### PR DESCRIPTION
**Pull request by vlad20012**
Fixes #3757 (fixes #2586) issues "E0603 module is private" when importing a module that is declared multiple times (has multiple `mod foo;` declarations, e.g. in `lib.rs` and `main.rs`). 

Also "Go To Super" action (ctrl+U) now allows choosing a declaration (if multiple):
image

Note that this is a **very** initial support of multiple module inclusions, i.e. now we can just know that a module is declared multiple times and e.g. suppress some inspections in this case.

### CODE REVIEW

File: src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt [hunk 1]
```diff
@@ -3107,6 +3107,18 @@ class RsErrorAnnotatorTest : RsAnnotatorTestBase(RsErrorAnnotator::class) {
         const _: i32 = 1;
     """)
 
+    fun `test no E0603 for module with multiple declarations`() = checkDontTouchAstInOtherFiles("""
+        //- main.rs
+            mod foo;
+            mod bar;
+            mod baz;
```
Comment (Undin) [inline src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt:3114]: Let's drom this line and fix test

File: src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt [hunk 2]
```diff
@@ -3107,6 +3107,18 @@ class RsErrorAnnotatorTest : RsAnnotatorTestBase(RsErrorAnnotator::class) {
         const _: i32 = 1;
     """)
 
+    fun `test no E0603 for module with multiple declarations`() = checkDontTouchAstInOtherFiles("""
+        //- main.rs
```
Comment (Undin) [inline src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt:3111]: nit: Looks like code should be shifted left to have the same style as other tests

File: src/main/kotlin/org/rust/lang/core/psi/ext/RsVisibility.kt [hunk 3]
```diff
@@ -33,6 +33,8 @@ fun RsVisibilityOwner.iconWithVisibility(flags: Int, icon: Icon): Icon =
         icon.addVisibilityIcon(isPublic)
 
 fun RsVisible.isVisibleFrom(mod: RsMod): Boolean {
+    if (this is RsFile && declarations.size > 1) return true
```
Comment (Undin) [inline src/main/kotlin/org/rust/lang/core/psi/ext/RsVisibility.kt:36]: Let's add a TODO comment to fix it because it produces false negative for some cases like
```rust
//- main.rs
use crate::aa::a::x; // <- no error here although compiler produces it

mod aa {
    mod a;
}

fn main() {}

//- lib.rs
use crate::aa::a::x; // <- no error here although compiler produces it

mod aa {
    mod a;
}

//- aa/a.rs
pub fn x() {}
```

Comment (Undin) [reply src/main/kotlin/org/rust/lang/core/psi/ext/RsVisibility.kt:36]: BTW let's add code above as test

File: src/main/kotlin/org/rust/ide/navigation/goto/RsGotoSuperHandler.kt [hunk 4]
```diff
@@ -24,35 +25,40 @@ class RsGotoSuperHandler : LanguageCodeInsightActionHandler {
...
+            1 -> targets.single().navigate(true)
+            else -> NavigationUtil.getPsiElementPopup(targets.toTypedArray(), "Choose module declaration")
+                .showInBestPositionFor(editor)
+        }
     }
 }
 
 @VisibleForTesting
-fun gotoSuperTarget(source: PsiElement): NavigatablePsiElement? {
+fun gotoSuperTarget(source: PsiElement): List<NavigatablePsiElement> {
```
Comment (Undin) [inline src/main/kotlin/org/rust/ide/navigation/goto/RsGotoSuperHandler.kt:39]:
```suggestion
fun gotoSuperTargets(source: PsiElement): List<NavigatablePsiElement> {
```

File: src/test/kotlin/org/rust/ide/navigation/goto/RsGotoSuperHandlerTest.kt [hunk 5]
```diff
@@ -139,19 +99,32 @@ class RsGotoSuperHandlerTest : RsTestBase() {
...
+
     // Navigation from a crate root to Cargo.toml is tested in `CargoTomlGotoSuperHandlerTest`
 
     private fun checkNavigationInFiles(@Language("Rust") fileTreeText: String, expected: String) {
+        checkMultiNavigationInFiles(fileTreeText, expected)
+    }
+
+    private fun checkMultiNavigationInFiles(@Language("Rust") fileTreeText: String, vararg expected: String) {
         fileTreeFromText(fileTreeText).createAndOpenFileWithCaretMarker()
         val target = gotoSuperTarget(myFixture.file)
```
Comment (Undin) [inline src/test/kotlin/org/rust/ide/navigation/goto/RsGotoSuperHandlerTest.kt:119]:
```suggestion
        val targets = gotoSuperTarget(myFixture.file)
```

**Comment by vlad20012** [comment]
bors r=undin
