### PR TITLE
TY: Assume `Self` is always copyable

### LINKED ISSUE #3062: False positive "Cannot move"
## Environment

* **Intellij-Rust plugin version: 0.2.0.2110-182**
* **Rust toolchain version: stable-x86_64-apple-darwin - rustc 1.30.1 (1433507eb 2018-11-07)**
* **IDE name and version: IntelliJ IDEA 2018.2.6 (Ultimate Edition)**
* **Operating system: macOS Mojave 10.14.1**

## Problem description
There is a false positive if you want to dereference a `Copy` type in a generic trait implementation that takes `self` by reference. However since `Self` implements `Copy` this is perfectly valid and compiles fine.

## Steps to reproduce
```rust
trait Dummy where Self: Copy {
    fn dummy(&self) -> Self {
        *self // ← This shows the error "Cannot move" ("Inspection info: Implements simple cases of borrow checking.")
    }
}
```

### PR DESCRIPTION
**Pull request by ortem**
Fixes #3062

### CODE REVIEW

File: src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt [hunk 1]
```diff
@@ -151,11 +151,16 @@ fun Ty.builtinDeref(explicit: Boolean = true): Pair<Ty, Mutability>? =
...
+/**
+ * TODO:
+ * There are some problems with `Self` inference (e.g. https://github.com/intellij-rust/intellij-rust/issues/2530)
+ * so for now just assume `Self` is always copyable
+ */
 fun Ty.isMovesByDefault(lookup: ImplLookup): Boolean =
     when (this) {
         is TyUnknown, is TyReference, is TyPointer, is TyFunction -> false
         is TyTuple -> types.any { it.isMovesByDefault(lookup) }
+        is TyTypeParameter -> this.name != "Self"
```
Comment (vlad20012) [inline src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt]:
```suggestion
        is TyTypeParameter -> this.parameter != TyTypeParameter.Self
```
