### PR TITLE
Fix E0424 False Positive on use with parens

### LINKED ISSUE #1795: E0424 False Positives
These are two false positive cases for the E0424 inspection. The cases are arbitrary and not rustic; they're just for minimal reproduction. `rustc` does not share this false-positive. In particular, the usage of `{}` triggers the false positive, while omitting them and having single imports per line will not trigger the false positive.

```rust
mod e0424 {
    enum T1 { E1, E2 }
    enum T2 { E1, E2 }
    impl T2 {
        pub fn from_t1(t1: &T1) -> Self {
            use self::{T1 as From, T2 as To};
            match t1 {
                &From::E1 => To::E1,
                &From::E2 => To::E2,
            }
        }
    }

    impl T1 {
        pub fn from_t2(t2: &T2) -> Self {
            use self::{T2 as From};
            use self::{T1 as To};
            match t2 {
                &From::E1 => To::E1,
                &From::E2 => To::E2,
            }
        }
    }
}
```

Related: #990 #886.

### PR DESCRIPTION
**Pull request by osialr**
Fixes #1795

### CODE REVIEW

File: src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt [hunk 1]
```diff
@@ -691,6 +691,19 @@ class RsErrorAnnotatorTest : RsAnnotatorTestBase() {
         }
     """)
 
+    fun `testE0424 ignore use self with parens`() = checkErrors("""
+        fn foo() {
```
Comment (vlad20012) [inline src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt]: It's minor, but it would be nice to use less whitespace.
```rust
fn foo() {}
fn bat() {}
...
```

**Comment by vlad20012** [comment]
@osialr Hi! I see it's your first contribution here. We need a CLA signed first.

The CLA process is described in contributing.md. Copy-pasting here:

We require a contributor license agreement for all contributions. You can sign it electronically at https://www.jetbrains.com/agreements/cla/ via DocuSign. The procedure consists of a couple of emails and clicks: no need to scan or print or snail-mail anything :) CONTRIBUTORS.txt file stores GitHub usernames of people who already signed a CLA.

The PR looks great! Could you also add your github nick to https://github.com/intellij-rust/intellij-rust/blob/master/CONTRIBUTORS.txt (the list is sorted alphabetically), and I'd be eager to r+ :)

**Comment by osialr** [comment]
Signed CLA, added to Contributors, reduced whitespace

**Comment by vlad20012** [comment]
bors r+

Thanks!

**Comment by vlad20012** [comment]
Oh, bors seems stalled

bors r-
